### ISSUE TITLE
Score query wrt document or rerank input set of documents wrt query

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#100]
Feature request from @cmacdonald -

Compute scores wrt a set of document specified by the user, i.e., "rerank this set for me". Could decompose into "score this query wrt this document" with an outer loop over documents.

Can be accomplished today by setting _k_ to be a really large value and then filtering results... but having a better implementation of this feature would be generally useful.

**Comment by lintool** [comment]
Closed by #110 - will go out in next PyPI release.

@cmacdonald if you are eager to use, you need to rebuilt yourself fatjar at Anserini current `HEAD` and use current Pyserini `HEAD`.

**Comment by lintool** [comment]
@cmacdonald this is now working and in the 0.9.3.0 release. See: https://github.com/castorini/pyserini/#usage-of-the-index-reader-api

Something like this should work:

```python
query = 'hubble space telescope'
docids = ['LA071090-0047', 'FT934-5418', 'FT921-7107', 'LA052890-0021', 'LA070990-0052']

for i in range(0, len(docids)):
    score = index_utils.compute_query_document_score(docids[i], query)
    print(f'{i+1:2} {docids[i]:15} {score:.5f}')
```

**Comment by thibault-formal** [comment]
hi @lintool , 
I am not sure which BM25 parameters (k1, b) are used when calling `compute_query_document_score` and/or how to specify them ? 
Thanks :)

**Comment by lintool** [comment]
see: https://github.com/castorini/pyserini/blob/8f70f514f7b27a18ce8e74d18f54e30c2b024ed5/pyserini/index/_base.py#L333

**Comment by thibault-formal** [comment]
hi @lintool , thanks for your answer 
I actually saw the `compute_bm25_term_weight` method, but I struggle to understand how it is linked to `compute_query_document_score`..
* maybe it's obvious, but it's not clear to me what is actually happening in `compute_query_document_score`
* is there a way to specify (k1, b) when calling `compute_query_document_score` ?

thanks in advance

**Comment by lintool** [comment]
hi @thibault-formal I'm not sure I understand your question... is the documentation link above not clear?

**Comment by arian-askari** [comment]
> hi @lintool , I am not sure which BM25 parameters (k1, b) are used when calling `compute_query_document_score` and/or how to specify them ? Thanks :)

Hi @thibault-formal,
Probably you have already found the solution as this is an old and closed issue! However, I could not find an answer for that by searching through issues. Therefore, here is the solution for someone else in the future. Here is the way to set b and k1 parameters for computing the BM25 score within a specific query and document:

```
from pyserini.pyclass import autoclass
b = 0.68
k1 = 0.82
similarity_bm25 = autoclass('org.apache.lucene.search.similarities.BM25Similarity')(k1, b)
query = 'hubble space telescope'
docids = ['LA071090-0047', 'FT934-5418', 'FT921-7107', 'LA052890-0021', 'LA070990-0052']
for i in range(0, len(docids)):
    score = index_utils.compute_query_document_score(docids[i], query, similarity= similarity_bm25)
    print(f'{i+1:2} {docids[i]:15} {score:.5f}')
```
