### ISSUE TITLE
Reorg pyserini.dsearch -> pyserini.search.faiss

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1006]
Since `pyserini.search` has been moved to `pyserini.search.lucene`, `pyserini.dsearch` should become `pyserini.search.faiss` as well.

**Comment by lintool** [comment]
`SimpleDenseSearcher` should become `FaissSearcher` as well.

**Comment by lintool** [comment]
@crystina-z is going to take a stab at this.

**Comment by crystina-z** [comment]
@lintool I guess this can be closed with #1028 merged?
