### ISSUE TITLE
Index own data 

### ISSUE THREAD

**Issue by shauryr** [castorini/pyserini#102]
How do I index my own data in Pyserini ? All the notebooks and examples are using prebuilt indexes.

**Comment by lintool** [comment]
We have an outstanding issue #77 on this. In the meantime, consult this guide: https://github.com/castorini/anserini/blob/master/docs/custom-collections.md

**Comment by shauryr** [comment]
Thanks. I am using ElasticSearch for now. I think direct indexing of jsonl files will be very useful.  From: Jimmy LinSent: Tuesday, May 12, 2020 7:45 PMTo: castorini/pyseriniCc: Shaurya Rohatgi; AuthorSubject: Re: [castorini/pyserini] Index own data (#102) We have an outstanding issue #77 on this. In the meantime, consult this guide: https://github.com/castorini/anserini/blob/master/docs/custom-collections.md—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
