### ISSUE TITLE
ModuleNotFoundError: No module named 'pyserini.search.lucene'

### ISSUE THREAD

**Issue by jordane95** [castorini/pyserini#1025]
Hi, I installed your `pyserini` and was trying to run some examples. But the first line
```Python
from pyserini.search.lucene import LuceneSearcher
```
raises the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyserini.search.lucene'
```
Could you help me fix it?

**Comment by lintool** [comment]
Hi @jordane95 - we recently refactored, but haven't pushed out a new pypi artifact yet. Your options are:
(1) run a dev installation: https://github.com/castorini/pyserini/#installation
(2) roll back the docs
