### ISSUE TITLE
Indexing a document for dense retrieval inside python script

### ISSUE THREAD

**Issue by xhlulu** [castorini/pyserini#1034]
I'm interested in using the dense retrieval side of the library, e.g. FAISS and DPR (via huggingface). I don't have Java installed in my container since i'm primarily using pytorch.

I was looking through the readme and only found this: https://github.com/castorini/pyserini#how-do-i-index-and-search-my-own-documents

It seems the instructions only show how to index via lucene (sparse/java) and can only be done via CLI. I'm imagining a scenario where I'd do that in python instead.

```python

docs = [
  "My first document",
  "My second document",
  # ...
]
indices = pyserini.create_index(docs)
searcher = SimpleDenseSearcher.from_memory_index(indices)
searcher.search("my query here")
```

Is that scenario currently supported (or is planned for the future)?

**Comment by lintool** [comment]
For sparse indexes, see #639 - unfortunately, there are no plans to implement in the near future.

For dense indexes, see this guide for how to encode a collection from the command line:
https://github.com/castorini/pyserini/blob/master/docs/usage-encode.md

In general, if your text collection is small enough to fit inline in Python code, then it probably doesn't make sense to build an index... something like brute-force over in-memory structures should suffice. The Pyserini use case is for large (at least GBs) corpora, in which case it wouldn't make sense to define the docs in a Python array.

**Comment by xhlulu** [comment]
> https://github.com/castorini/pyserini/blob/master/docs/usage-encode.md

Thanks for sharing this! Will try that out :)

> The Pyserini use case is for large (at least GBs) corpora

Make sense, thank you for clarifying! My data is large enough to fit in memory (i usually load the data `pandas` or `json`, writing inline was for demo purposes), but at GB scale I think the dense representations will indeed not fit in memory :)
