### ISSUE TITLE
Issues Delegating More GPUs for Dense Encoding

### ISSUE THREAD

**Issue by jonsaadfalcon** [castorini/pyserini#1035]
Hello, when trying to delegate more devices for encoding using pyserini.encode, I receive the following error after running this script:

`python -m pyserini.encode input   --corpus my_corpus.jsonl \
                                  --fields text url title \
                          output  --embeddings my_embeddings \
                                  --to-faiss \
                          encoder --encoder DenseTrainedModels \
                                  --device [cuda:0, cuda:1, cuda:2, cuda:3] \
                                  --fields text \
                                  --batch 32 \
                                  --fp16
`

`Error: usage: __main__.py [-h] {input,output,encoder} ...
__main__.py: error: unrecognized arguments: cuda:1, cuda:2, cuda:3]`

I was wondering how to properly format the '--device' tag since other configurations of the tag, with and without quotes, doesn't seem to work. Thank you!

**Comment by MXueguang** [comment]
Hi @jonsaadfalcon,
our `pyserini.encode` only support single gpu encoding.
e.g.. --device cuda:0

if you want to encode in parallel, have to run multiple individual process.
