### ISSUE TITLE
Clean up LTR and IRST test cases

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1042]
@yuki617 @stephaniewhoo can you do a bit of clean up on the LTR and IRST test cases? E.g., make PEP8 compliant?

https://github.com/castorini/pyserini/blob/master/integrations/sparse/test_ltr_msmarco_document.py
https://github.com/castorini/pyserini/blob/master/integrations/sparse/test_ltr_msmarco_passage.py
https://github.com/castorini/pyserini/blob/master/integrations/sparse/test_transprobability_search.py --> rename to irst?

**Comment by stephaniewhoo** [comment]
done by #1046
