### ISSUE TITLE
Write util to dump out BM25 vectors for a corpus

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1050]
Would be a useful tool to have...

**Comment by lintool** [comment]
Starting point: https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md#how-do-i-compute-the-tf-idf-or-bm25-score-of-a-document

**Comment by manveertamber** [comment]
I can try this out

**Comment by lintool** [comment]
Hey @manveertamber to iterate through all docs in the collection I think you need to do this:

from `stats()`, figure out how many docs there are in the index:
https://github.com/castorini/pyserini/blob/master/pyserini/index/lucene/_base.py#L516

the internal ids are numbered from 1 to _n_: for each, use this method to get the collection doc id:
https://github.com/castorini/pyserini/blob/master/pyserini/index/lucene/_base.py#L516

with the doc id, you can call `get_document_vector()`
https://github.com/castorini/pyserini/blob/master/pyserini/index/lucene/_base.py#L332

Once you figure this out, can you please:
1. add a test case demonstrating this usage here: https://github.com/castorini/pyserini/blob/master/tests/test_index_reader.py
2. add documentation explaining here: https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md
