### ISSUE TITLE
pyserini.index -> pyserini.index.lucene

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1062]
Should `pyserini.index.IndexReader` become:

(1) `pyserini.index.lucene.IndexReader` or 
(2) `pyserini.index.LuceneIndexReader`

My vote is for (1). Thoughts @MXueguang ?

**Comment by MXueguang** [comment]
yeah (1) looks good

**Comment by lintool** [comment]
@MXueguang can you please work on it?

**Comment by MXueguang** [comment]
sure

**Comment by lintool** [comment]
Refactored in #1068

I still keep to clean up documentation. Will close after that's done.

**Comment by lintool** [comment]
I executed the following:

```
find docs/ -name '*.md' | xargs grep 'IndexReader'
```

Seems like all imports have been fixed.
