### ISSUE TITLE
How to normalized unicoil and TcTColBERT scores?

### ISSUE THREAD

**Issue by namespace-Pt** [castorini/pyserini#1080]
In hybrid model, the paper "A Few Brief Notes on DeepImpact, COIL, and a Conceptual Framework for Information Retrieval Techniques" says that you normalize the scores to (0,1) before combining. What function are you using?

**Comment by MXueguang** [comment]
Hi @namespace-Pt 

https://github.com/castorini/pyserini/blob/4c039d0c28f63cb3fa10ca6bd78a58300bfbc7da/pyserini/search/hybrid/_searcher.py#L74-L77

in pyserini implementation here we scale the score to (-0.5, 0.5) but should be equivalent to (0, 1)

**Comment by namespace-Pt** [comment]
Thank you.
