### ISSUE TITLE
pyserini.index structure

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1090]
In `pyserini.index`, `lucene` is a sub-directory, but `faiss` and `nmslib` aren't, even though each form a namespace.

Should we convert `faiss` and `nmslib` into subdirectories also?

@MXueguang @crystina-z thoughts?

**Comment by MXueguang** [comment]
seems faiss/nmslib are not necessary to become a directory since it is actually a single file.
probably we can make it into subdirectories if we have more files for faiss/nmslib in the future.
I feel we can keep it simple for now

**Comment by lintool** [comment]
Okay, in that case, I'll close!
