### ISSUE TITLE
Update example code for using IndexReader

### ISSUE THREAD

**Issue by Shinyu-Mao** [castorini/pyserini#1140]
The code for initialzing the IndexReader as in this page https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md#how-do-i-compute-the-tf-idf-or-BM25-score-of-a-document, should be `from pyserini.index import IndexReader`.

Either `from pyserini.index.lucene import IndexReader` (as the given example) or ` import pyserini.index.lucene.IndexReader` will raise error as `ImportError: cannot import name 'IndexReader' from 'pyserini.index.lucene` or `ModuleNotFoundError: No module named 'pyserini.index.lucene.IndexReader'; 'pyserini.index.lucene' is not a package'. ` under the latest version `pyserini 16.0`.

**Comment by lintool** [comment]
Hi @Shinyu-Mao thanks for noticing. What we have in the documentation is correct because it matches `HEAD` (i.e., dev installation).
