### ISSUE TITLE
Break README.md into document subpages?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#119]
Main `README.md` is getting pretty long. Should we break into separate pages?

+ Usage of the Analyzer API
+ Usage of the Query Builder API
+ ...

@Chriskamphuis @PepijnBoers @x65han thoughts?

**Comment by lintool** [comment]
cf. https://github.com/castorini/pyserini/pull/163#discussion_r434584234

@rodrigonogueira4 I assume you'd support this?

**Comment by rodrigonogueira4** [comment]
Yes, sure

**Comment by Chriskamphuis** [comment]
Sorry missed this earlier, I agree to split
