### ISSUE TITLE
Cannot import AnceEncoder from transformers package

### ISSUE THREAD

**Issue by NoB0** [castorini/pyserini#1230]
## Problem
I want to use [ance-msmarco-passage model](https://huggingface.co/castorini/ance-msmarco-passage). The class AnceEncoder cannot be imported.

## Reproduce problem
Python version: 3.7.12
transformers version: 4.9.0

```
>>> from transformers import AnceEncoder
ImportError: cannot import name 'AnceEncoder' from 'transformers' (/home/stud/nbernard/miniconda3/envs/treccast/lib/python3.7/site-packages/transformers/__init__.py)
```

## Question
Should the version of Python and/or transformers be updated?

**Comment by w32zhong** [comment]
make sure you have installed `transformers`, and then do
```py
from pyserini.encode import AnceEncoder
```
