### ISSUE TITLE
TCT-ColBERTv2 Code

### ISSUE THREAD

**Issue by r1ckC139** [castorini/pyserini#1246]
Hi team,
Do you guys have a plan to release TCT-ColBERTv2 Code (training, indexing, searching,..)? (I'm really sorry because this question isn't related to this repo but I found that you guys are the author of "In-Batch Negatives for Knowledge Distillation with Tightly-Coupled
Teachers for Dense Retrieval" paper)

**Comment by jacklin64** [comment]
Hi @r1ckC139, we have TCT-ColBERTv2 training and inference instruction in other repo (https://github.com/castorini/tct_colbert), where we developed TCT using tensorflow. Maybe in the future, we'll have the one using pytorch + huggingface.

**Comment by r1ckC139** [comment]
@jacklin64, thanks for your answer, hope you guys can release pytorch + huggingface version in the future.

**Comment by r1ckC139** [comment]
Hi @jacklin64, if I want to use TCT-ColBERT with pyserini dense search, then I need to convert tensorflow model (trained by your code) to pytorch version right?

**Comment by jacklin64** [comment]
yes, correct. But if you don't mind, you can directly use the pytorch models transformed by us here: https://huggingface.co/castorini/tct_colbert-v2-hnp-msmarco

**Comment by r1ckC139** [comment]
I train TCT-ColBERT with my own dataset (in Vietnamese language) so i can't use these English models, Do you know any convenient tool or way to convert?

**Comment by jacklin64** [comment]
You can use this script in huggingface https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py. Just make sure you get the weights of student model rather teacher model.

**Comment by r1ckC139** [comment]
I'll try it, thank you so much for your quick and helpful replies
