### ISSUE TITLE
Please add requirements.txt to sdist

### ISSUE THREAD

**Issue by shaileshj2803** [castorini/pyserini#1257]
The sdist does not contain the required file "requirements.txt" which is read by [setup.py](http://setup.py/) - https://github.com/castorini/pyserini/blob/master/setup.py#L6
please fix the sdist to include requirements.txt.

**Comment by lintool** [comment]
Hi @shaileshj2803 thanks for filing the issue. I believe this is closed by #1258 ?

Please reopen issue if otherwise.
