### ISSUE TITLE
Number of encoders in ANCE 

### ISSUE THREAD

**Issue by zhiqihuang** [castorini/pyserini#1260]
Hi,

I have a question after loading the [ANCE](castorini/ance-msmarco-passage) model.

It seems that the ANCE model on hugging face only has one RobertaModel. Do the query and document encoders share parameters? 

From the DPR paper, the model should contain separate encoders. One for the query and another one for the document.
In the ANCE repo, they also initialized the model with different encoders [here](https://github.com/microsoft/ANCE/blob/39258f5824d00fede624f11caaccab15bc254502/model/models.py#L252).

I think this choice makes a big difference since the dual approach doubles the parameter size of the Siamese approach,

**Comment by MXueguang** [comment]
Hi @zhiqihuang,

I think they are using this implementation while training ANCE for msmarco passage.
https://github.com/microsoft/ANCE/blob/39258f5824d00fede624f11caaccab15bc254502/model/models.py#L137
So q-encoder and p-encoder share parameters.

**Comment by zhiqihuang** [comment]
I see. Thank you.
