### ISSUE TITLE
Extend Trec to DPR Run Converter to use Custom Topics ?

### ISSUE THREAD

**Issue by ToluClassics** [castorini/pyserini#1290]
The file [convert_trec_run_to_dpr_retrieval_run.py](https://github.com/castorini/pyserini/blob/master/pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py) only allows the conversion of topics currently checked into anserini. 

I guess we can open this up to use custom query files also?

https://github.com/castorini/pyserini/blob/2673031f6b202941fe0f9953c9b876e6d4f1e653/pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py#L26-L37

I can see it's possible using this function:

https://github.com/castorini/pyserini/blob/2673031f6b202941fe0f9953c9b876e6d4f1e653/pyserini/search/_base.py#L391-L407

**Comment by ToluClassics** [comment]
@MXueguang

**Comment by MXueguang** [comment]
yeah, that's a good idea. I guess we can first check if the "name" is a path, and if it is, load it using `get_topics_with_reader`, otherwise, assume it is self contain topic file
