### ISSUE TITLE
MIRACL 2CR: rotate the table?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1309]
Looking at this: https://castorini.github.io/pyserini/2cr/miracl.html

Would it make sense to rotate the table, so that rows are languages, and columns are the methods? Then we can make the repro matrix look very close to the results table in the paper.

Thoughts, @crystina-z ?

**Comment by crystina-z** [comment]
maybe after we have more baselines? right now it would only have 4 columns (including both ndcg@10 and recall) and the table might look very thin and possibly odd... I'm thinking this version is good based on what we have so far?

**Comment by lintool** [comment]
Scratch this idea...
