### ISSUE TITLE
removing or excluding documents from the index

### ISSUE THREAD

**Issue by shmsw25** [castorini/pyserini#1311]
Hi! Thank you for this great library. I am curious if there is a way to remove the documents from the index that is already built, or alternatively exclude a set of documents from results when searching. I am specifically looking for this feature with a sparse index. 

It will still be possible to get results with larger K first and exclude those results later, but I found it quite inefficient when I have a large number of documents to remove/exclude.

**Comment by lintool** [comment]
Yes, there is a way to remove documents in Lucene, but unfortunately the hooks are not exposed from the Java end. Can you describe your use case?

Can you file an issue, and we'll prioritize wrt the rest of our tasks...

**Comment by shmsw25** [comment]
Thanks! I think there will be many use cases, but the specific case of mine is to group a large set of documents into different batches that share high similarity scores.

For instance, if we want N batches with K docs per batch, where there're N*K docs in the index, we might want to do the following:
```python
batches = []
for _ in range(N):
    id = searcher.sample() # randomly sampling a doc from the index
    hits = searcher.search(documents[id], K)
    retrieved_ids = [hit.id for hit in hits]
    batches.append(retrieved_ids) # include them in the batch
    searcher.remove(retrieved_ids) # remove them from the index if they're already included in the batch
```
(There might be other ways to do it efficiently, other than using the removal function, but can't think of it now...)

Is there a guidance on how to officially file an issue? I'll do it if needed. Thanks!

**Comment by lintool** [comment]
So, basically, dedupping? For that, an index-based solution isn't the best... you want something like a hash-based solution - something simple like minhash or something more complex like LSH forests (e.g., with random projects).

**Comment by shmsw25** [comment]
Ah I see, thanks for the suggestion! 

I actually managed to make it work by using batch operations -- seems to work fast enough in my use case. I'll close the issue for now since it's not urgent for me. Great tool!! :)
