### ISSUE TITLE
Add MIRACL dev set bindings, update regressions

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1317]
With [Anserini v0.16.0](https://repo1.maven.org/maven2/io/anserini/anserini/0.16.0/), we can now update MIRACL bindings and regressions.

**Comment by ToluClassics** [comment]
Hi @lintool , are  we making this `experiments-miracl-v1.0-ar.md` per language instead of `experiments-miracl-v1.0.md` for everything?

**Comment by lintool** [comment]
Sorry, I should have been more clear. I think we need to do:

(1) add the topic bindings: https://github.com/castorini/pyserini/blob/master/tests/test_load_topics.py#L23

(2) add `experiments-miracl-v1.0.md` (yea, one file is fine - do what @crystina-z does with like a `$lang` code in the docs) -  this page will primarily add indexing instructions

(3) tweak 2CR to use (1)

**Comment by lintool** [comment]
Closed by #1319
