### ISSUE TITLE
There some minor mistakes in `index.lucene._base.Posting`

### ISSUE THREAD

**Issue by Koistory** [castorini/pyserini#1328]
In the file `index.lucene._base.py` I find the comment of class `Posting` has some mistakes which will cause some trouble when using the package when I try to calculate the tf-idf score of the document. The attribute `docid` with data type `int` acctually refers to Lucene internal ``docid`` but not External collection ``docid`` whose data type is `str` according to the comment. The result should be applied by the function `convert_internal_docid_to_collection_docid` so that I can get the collection ``docid`` to visit the documents in the collection.

**Comment by lintool** [comment]
Hi @Koistory thanks for opening this issue - I hope that you're finding our toolkit useful!

> The attribute docid with data type int acctually refers to Lucene internal docid but not External collection docid whose data type is str according to the comment.

This is actually the desired behavior - and is consistent with implementations of most IR engines.

However, you make a good point in that the documentation can be improved to clarify this possible point of confusion. Would you be wiling to send a PR?

**Comment by Koistory** [comment]
OK, I get it. Thank you for your patient answering! Your pakage is really awesome and it helps me a lot in my work. I will close the issue soon, but I am sorry that I may not send a PR for I actually run out of time at present. Best wishes!

From: Jimmy Lin ***@***.***>
Date: 2022-11-01 00:15:50
To: castorini/pyserini ***@***.***>
Cc: Koistory ***@***.***>,Mention ***@***.***>
Subject: Re: [castorini/pyserini] There some minor mistakes in `index.lucene._base.Posting` (Issue #1328)

Hi @Koistory thanks for opening this issue - I hope that you're finding our toolkit useful!
The attribute docid with data type int acctually refers to Lucene internal docid but not External collection docid whose data type is str according to the comment.
This is actually the desired behavior - and is consistent with implementations of most IR engines.
However, you make a good point in that the documentation can be improved to clarify this possible point of confusion. Would you be wiling to send a PR?
