### ISSUE TITLE
mDPR using cls or pooler_output

### ISSUE THREAD

**Issue by zhiqihuang** [castorini/pyserini#1333]
About mDPR model, does it use CLS token or pooler_output?

In _searcher.py, DprQueryEncoder uses the pooler_output [here](https://github.com/castorini/pyserini/blob/d128563d1c49948c4144badf62436c5c43dd3fc1/pyserini/search/faiss/_searcher.py#L138) and  AutoQueryEncoder uses the CLS token [here](https://github.com/castorini/pyserini/blob/d128563d1c49948c4144badf62436c5c43dd3fc1/pyserini/search/faiss/_searcher.py#L324). I wonder which is used by mDPR.

Thanks.

**Comment by crystina-z** [comment]
Hi @zhiqihuang!

If you are using our hgf models like [mdpr-tied-pft-msmarco](https://huggingface.co/castorini/mdpr-tied-pft-msmarco) or so, it would be the `AutoQueryEncoder` which means the CLS token representation.

**Comment by zhiqihuang** [comment]
> Hi @zhiqihuang!
> 
> If you are using our hgf models like [mdpr-tied-pft-msmarco](https://huggingface.co/castorini/mdpr-tied-pft-msmarco) or so, it would be the `AutoQueryEncoder` which means the CLS token representation.

Yes, that's exactly what I'm looking for. Thanks.
