### ISSUE TITLE
Retire technical debt for TfidfVectorizer

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#136]
+ Write test cases: you can assume the CACM test index: https://github.com/castorini/pyserini/blob/master/tests/test_indexutils.py#L31
+ Write docstrings
+ Add boilerplate at top of source

**Comment by x65han** [comment]
@lintool  what do you mean by write docstrings here?

**Comment by lintool** [comment]
Like https://www.python.org/dev/peps/pep-0257/ class and method docs?
