### ISSUE TITLE
Retire technical debt for pysearch.search __main__

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#137]
Arg layout should be consist with anserini structure: change `-prf` to `-prcl` since we've decided to name the class `PseudoRelevanceClassifierReranker`

Args should be grouped, e.g., `-prcl.r`, `-prcl.n`, `-prcl.alpha`

---

use [tqdm](https://github.com/tqdm/tqdm) for progress indicator

---

Write test case: you can assume the CACM test index: https://github.com/castorini/pyserini/blob/master/tests/test_indexutils.py#L31

This would be similar to the commit hook in anserini: https://github.com/castorini/anserini/blob/master/.travis.yml#L20

---

I think output file should be obligatory.

**Comment by x65han** [comment]
I used to have -output as a mandatory arg. But then later implemented the logic to build an
 output path based on the input args.

e.g.:
- core18_bm25.txt
- robust04_lr_A0.5_bm25.txt

**Comment by lintool** [comment]
> I used to have -output as a mandatory arg. But then later implemented the logic to build an output path based on the input args. So that the user doesn't have to worry about naming the output especially when running multiple configurations. What do you think?
> 
> e.g.:
> 
> * core18_bm25.txt
> * robust04_lr_A0.5_bm25.txt

I think that's fine, but a few tweaks, should be collection, model, and then additional params.

So: `core18-bm25-prcl.r_10-prcl.n_100-prcl.alpha_0.5.txt`

Windows doesn't allow `=` in filenames, so I use `_` instead.

**Comment by x65han** [comment]
Sorry, I didn't see your comment on the output_path tweak. I will make this change in a separate PR.

Here's a few examples of the resulting file name:
- core18-bm25+rm3-svm+lr-prcl.r_10-prcl.r_100-prcl.alpha_0.2.txt
- core18-bm25-svm-prcl.r_10-prcl.r_100-prcl.alpha_0.2.txt
- core18-bm25.txt
- core18-bm25+qld.txt
