### ISSUE TITLE
Importing LuceneSearcher relies on FAISS and Torch

### ISSUE THREAD

**Issue by cakiki** [castorini/pyserini#1375]
Currently, importing `LuceneSearcher` fails if faiss and torch aren't installed. (They aren't installed by design because they're platform-specific, see: https://github.com/castorini/pyserini#installation)

This is likely caused by the imports in the following init file: https://github.com/castorini/pyserini/blob/master/pyserini/search/__init__.py#L23-L26

A fix would need to modularize those imports.

If no one gets to it before me, I will attempt to send a PR to fix this.

**Comment by MXueguang** [comment]
yeah, PR is welcomed!

**Comment by lintool** [comment]
See #2009 - this has been resolved by #1997
