### ISSUE TITLE
Issue with VM during pysearch import

### ISSUE THREAD

**Issue by MadanKrishnan97** [castorini/pyserini#139]
I am trying to import pysearch from pyserini.search. I set the JAVA_HOME variable to jdk11. I am running this using Jupyter Notebook and I am getting the error as shown.

```python
import os
os.environ['JAVA_HOME'] = '/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home'

from pyserini.search import pysearch
```

The error is:

```
ValueError: VM is already running, can't set classpath/options; VM started at  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
```

I initially was running in a virtual environment (conda environment). I tried coming out of it and execute, but I am still getting the same issue. Any workarounds? Or am I missing something?

I am using MacOS Catalina.

**Comment by lintool** [comment]
You've somehow already initialized pyjnius, which fires up a JVM, so you can't do it again...

We don't seem to have that issue with our notebooks: https://github.com/castorini/anserini-notebooks

Unclear what you're doing differently...

**Comment by MadanKrishnan97** [comment]
I tried stopping jupyter server and started again. It seems to work now with the same code snippet.
