### ISSUE TITLE
Download url for unicoil index is invalid

### ISSUE THREAD

**Issue by yhy-2000** [castorini/pyserini#1415]
I want to download the index provided in this document(https://github.com/castorini/pyserini/blob/master/docs/experiments-unicoil.md), the url it provided is https://rgw.cs.uwaterloo.ca/JIMMYLIN-bucket0/data/msmarco-doc-segmented-unicoil.tar， however, when I visit this url, there is 503 net error. I tried in different computers and meet the same error, so I guess it may not be my problem.

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/52754849/212599741-ab69f534-3229-4b3a-8d9e-a4c40b62f3be.png">

Could you please update a new url or fix this problem?

**Comment by lintool** [comment]
We had a transient issue with our servers... should be good now. Please re-open issue if it still doesn't work?
