### ISSUE TITLE
add contriever 2CR

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#1423]
add contriever experiments for 2CR.

1. contriever on BEIR
2. mcontriever on MIRACL
3. contriever-ft on BEIR
4. mcontriever-ft on MIRACL

indexes for 1) and 2) are ready on orca

We can start with MIRACL
The command below should be able to run mcontriever on miracl-ar-dev
```
python -m pyserini.search.faiss \
  --encoder-class contriever \
  --encoder facebook/mcontriever \
  --topics miracl-v1.0-ar-dev \
  --index /mnt/users/x93ma/miracl-mcontriever-faiss/faiss.miracl-v1.0.0-ar.mcontriever.20230124 \
  --output run.miracl.contriever.ar.dev.txt \
  --batch 128 --threads 16 --hits 1000
```

**Comment by lintool** [comment]
Old issue... appears to have been done.
