### ISSUE TITLE
[Question] Load custom topic file through CLI

### ISSUE THREAD

**Issue by AmenRa** [castorini/pyserini#1439]
Hi, can I load a custom topic file through CLI? If so, how should it be formatted?
Sorry if it is already explained somewhere, I could not find it.

Example:
```sh
python -m pyserini.search.lucene \
    --threads 16 --batch-size 128 \
    --index msmarco-v1-passage-slim \
    --topics <CUSTOM_TOPICS> \
    --output msmarco-v1-passage/bm25-pyserini/k1=0.9-b=0.4/dev.trec \
    --bm25 --k1 0.9 --b 0.4
```

**Comment by ToluClassics** [comment]
Hi @AmenRa,

You can store your custom topics as a `tsv` with the first column being the topic_id and the second column is the topic.
Here's [an example](https://github.com/castorini/anserini/blob/master/src/main/resources/topics-and-qrels/topics.miracl-v1.0-en-dev.tsv) of that it should look like .

**Comment by AmenRa** [comment]
Thank you very much! :)

**Comment by pcvishak** [comment]
Hi,
The link is not accessible. Could you provide another example?

**Comment by lintool** [comment]
Fixed link: https://github.com/castorini/anserini-tools/blob/master/topics-and-qrels/topics.miracl-v1.0-en-dev.tsv

**Comment by pcvishak** [comment]
Thanks so much.
