### ISSUE TITLE
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file

### ISSUE THREAD

**Issue by Wenze7** [castorini/pyserini#1440]
My doc-vectors is 6.2G, and the rest space in my machine is 43G, but i got the following warning:
![image](https://user-images.githubusercontent.com/55132749/217265793-ac382a86-e2a5-4cd1-a0ed-41a0186cd1b8.png)

I want to know whether this warning will affect my results?

**Comment by lintool** [comment]
We've upgraded to JDK 21 recently, so this might not be an issue anymore. Please reopen otherwise.
