### ISSUE TITLE
Adding one document to an existing index

### ISSUE THREAD

**Issue by Hazoom** [castorini/pyserini#1443]
Hi,

I have an index with many document that I built, and I want to add one document to it.
The naive approach will be of course to run the `index` command on all my documents together with the next index, but the issue is that my system runs in production environment and I cannot allow it because it takes too much time.

Could you please assist?

**Comment by duongkstn** [comment]
same issue. any advice ?

**Comment by e-tornike** [comment]
I tried the following, but it seems to overwrite the index at each run:

```python
>>>from pyserini.index.lucene import LuceneIndexer, IndexReader
>>>indexer = LuceneIndexer("existing-index")
>>>indexer.add("{'id': '0', 'contents': 'Document 0'}")
>>>indexer.close()
>>>reader = IndexReader("existing-index")
>>>print(reader.stats())
{'total_terms': 2, 'documents': 1, 'non_empty_documents': 1, 'unique_terms': 2}

>>>indexer = LuceneIndexer("existing-index")
>>>indexer.add("{'id': '1', 'contents': 'Document 1'}")
>>>indexer.close()
>>>reader = IndexReader("existing-index")
>>>print(reader.stats())
{'total_terms': 2, 'documents': 1, 'non_empty_documents': 1, 'unique_terms': 2}

>>>indexer = LuceneIndexer("existing-index")
>>>indexer.add("{'id': '0', 'contents': 'Document 0'}")
>>>indexer.add("{'id': '1', 'contents': 'Document 1'}")
>>>indexer.close()
>>>reader = IndexReader("existing-index")
>>>print(reader.stats())
{'total_terms': 4, 'documents': 2, 'non_empty_documents': 2, 'unique_terms': 3}
```

Source: #1344 & [index_msmarco_passage.py](https://github.com/castorini/pyserini/blob/master/scripts/msmarco-passage/index_msmarco_passage.py)

**Comment by lintool** [comment]
Hi all, thanks for all your interest! If this is a feature that many people want... then we'll be happy to prioritize!

**Comment by lintool** [comment]
Hi @Hazoom @duongkstn @e-tornike I think this is what you're looking for? https://github.com/castorini/pyserini/pull/1451

**Comment by e-tornike** [comment]
Awesome! Thanks a lot for the quick implementation!
