### ISSUE TITLE
Download speed low for dense indices

### ISSUE THREAD

**Issue by EntilZha** [castorini/pyserini#1471]
Hi, I'm going through the install instructions to setup a dense prebuilt index, but finding that the download speed for the index downloaded here as part of test to see everything works to be quite slow (200-350kB/s).

```
python -m pyserini.dsearch \
    --topics msmarco-passage-dev-subset \
    --index msmarco-passage-tct_colbert-v2-bf \
    --encoded-queries tct_colbert-v2-msmarco-passage-dev-subset \
    --batch-size 36 \
    --threads 12 \
    --output runs/run.msmarco-passage.tct_colbert-v2.bf.tsv \
    --output-format msmarco
```
Is there a way to speed up the download?

**Comment by lintool** [comment]
Hi @EntilZha thanks for your interest in our work! Which URL exactly is slow to download (so we can better diagnose)? You're trying to download from Seattle?

**Comment by EntilZha** [comment]
Hi, while I am in Seattle :), the download should originate from 208.53.44.121 if `curl ifconfig.me` is accurate, so Utah. The downloads to Seattle seem to be normal speed FWIW.

**Comment by lintool** [comment]
Hrm... odd... we've never had issues with this host before. @MXueguang @jacklin64 @alexlimh have you had issues from Seattle before?

**Comment by MXueguang** [comment]
Weird, I didn't got this issue before. @EntilZha are you looking for just a specific index? we can upload it to dropbox for you.

**Comment by lintool** [comment]
Seeing no follow up, closing issue!
