### ISSUE TITLE
Add SLIM and Aggretriever to MS MARCO 2CR

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1485]
SLIM documentation is here:
https://github.com/castorini/pyserini/blob/master/docs/experiments-slim.md

As it as a condition here?
https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html

**Comment by alexlimh** [comment]
Created PR #1488

**Comment by lintool** [comment]
@jacklin64 can we add for Aggretriever also please?

**Comment by lintool** [comment]
Old issue... but appears to have been done?
