### ISSUE TITLE
Using FaissSearcher leads to FileIOError

### ISSUE THREAD

**Issue by Saatvik-droid** [castorini/pyserini#1511]
I am trying to initialize FaissSearcher using both prebuilt indices as well as providing a manual location after downloading the index tar file as stated in the docs. Both the times it looks for a `/path/to/file/.../index` that does not exist. 
eg: 
```
searcher = FaissSearcher.from_prebuilt_index('msmarco-v1-passage', encoder)
```
or 
```
wget https://git.uwaterloo.ca/jimmylin/anserini-indexes/raw/master/index-msmarco-passage-20201117-f87c94.tar.gz
tar xvfz /content/index-msmarco-passage-20201117-f87c94.tar.gz.1 -C indexes


searcher = FaissSearcher('/indexes/index-msmarco-passage-20201117-f87c94', encoder)
```
which results in `Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open /root/.cache/pyserini/indexes/lucene-index.msmarco-v1-passage.20221004.252b5e.c697b18c9a0686ca760583e615dbe450/index for reading: No such file or directory` and similiar for the second code too.

**Comment by lintool** [comment]
Seems like you're trying to initialize Faiss with a Lucene index...
Try one of the guides here for entry points of using dense indexes: https://github.com/castorini/pyserini/#dense-retrieval
