### ISSUE TITLE
Add index for surprise languages for miracl

### ISSUE THREAD

**Issue by aamir-s18** [castorini/pyserini#1526]
Hey, it would be great if you could add the sparse index for the surprise languages [here](https://github.com/castorini/pyserini/blob/master/docs/experiments-miracl-v1.0.md).

Thank you :)

**Comment by lintool** [comment]
Hi @aamir-s18 yup, doc seems to need update - for now, look at https://castorini.github.io/pyserini/2cr/miracl.html

**Comment by aamir-s18** [comment]
Cool, I will try it out. It would also be nice to add the benchmarks there to have a baseline.

If you'd like, you can close the issue here. Thank you!

**Comment by aamir-s18** [comment]
@lintool ah, thank you!
