### ISSUE TITLE
Difference in BM25 performance for BEIR Collections

### ISSUE THREAD

**Issue by cramraj8** [castorini/pyserini#1527]
I am trying to reproduce the BEIR collections (TREC-COVID, TREC-NEWS, and NQ) scores reported in their paper table. But the scores I get by using your pre-built indexes seem somewhat lower than the report score in terms of nDCG@10 and R@100. Is there any details that I am missing here like using multi-field search such like that ?

**Comment by lintool** [comment]
@thakur-nandan this must be the capped recall issue? I suppose our 2CRs don't implement it?

**Comment by davidmrau** [comment]
is there any update on this?

**Comment by davidmrau** [comment]
@cadurosar Thanks!

**Comment by lintool** [comment]
Issue resolved, closing.
