### ISSUE TITLE
Unrecognized indexes

### ISSUE THREAD

**Issue by AmenRa** [castorini/pyserini#1533]
I am trying to [reproduce ADORE experiments](https://github.com/castorini/pyserini/blob/master/docs/experiments-adore.md) with the latest `pyserini` version, but I get this error message:

```
Using pre-defined topic order for msmarco-passage-dev-subset
Attempting to initialize pre-encoded queries adore-msmarco-passage-dev-subset.
Unrecognized query name adore-msmarco-passage-dev-subset
Attempting to initialize pre-built index msmarco-passage-adore-bf.
Unrecognized index name msmarco-passage-adore-bf
```

Were ADORE files renamed?

Thank you,

Elias

**Comment by AmenRa** [comment]
I get similar errors for `Aggretriever-DistilBERT` and `Aggretriever-coCondenser` following the scripts reported [here](https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html).

```
Attempting to initialize pre-built index msmarco-passage.aggretriever-distilbert.
Unrecognized index name msmarco-passage.aggretriever-distilbert
```

```
Attempting to initialize pre-built index msmarco-passage.aggretriever-cocondenser.
Unrecognized index name msmarco-passage.aggretriever-cocondenser
```

**Comment by AmenRa** [comment]
Ok, thank you very much for the clarification.
Do you have an approximate ETA for the next release?

**Comment by lintool** [comment]
Nope... we don't have anything planned for a while...
