### ISSUE TITLE
How to get hint's raw text for DPR.

### ISSUE THREAD

**Issue by XZhang97666** [castorini/pyserini#1548]
I found there is no raw text from DenseSearchResult. How could I get corresponding text from retrieved results.

**Comment by w32zhong** [comment]
One way around is to download a paired inverted (sparse) index (for DPR: https://github.com/castorini/pyserini/blob/master/docs/experiments-dpr.md):
```
python -m pyserini.search.hybrid \
  dense  --index wikipedia-dpr-100w.dpr-multi \
         --encoded-queries dpr_multi-nq-test \
  sparse --index wikipedia-dpr-100w \
  fusion --alpha 1.3 \
  run    --topics dpr-nq-test \
         --output runs/run.dpr.nq-test.multi.bf.bm25.trec \
         --batch-size 36
```
and fetch the document by ID via inverted index: https://github.com/castorini/pyserini/blob/master/docs/usage-fetch.md

**Comment by lintool** [comment]
Seems to be resolved, but could be a point of improvement. Opened issue.
