### ISSUE TITLE
Install pyserini on MacOS

### ISSUE THREAD

**Issue by nightlessbaron** [castorini/pyserini#1551]
Hi, 

I am using conda environment to install pyserini on MacOS. However, I am getting the following error:
`ERROR: Could not build wheels for nmslib, which is required to install pyproject.toml-based projects`
This happens when installing `nmslib` package.

Can anyone please suggest how do I resolve this issue?

Thank you!

**Comment by nightlessbaron** [comment]
Further digging into the issue let me to this: https://github.com/nmslib/nmslib/issues/476#issuecomment-876094529
Following the steps does do resolve the issue. However, it's a hack and I would leave this issue open to get a better solution for this error.

**Comment by sueszli** [comment]
@nightlessbaron – none of the `nmslib` solutions mentioned in the comment worked for me. May I ask you what machine / os you're building in?

Thanks

**Comment by nightlessbaron** [comment]
I believe at the time of installation, I was using Ventura 13 (MacOS)

**Comment by sueszli** [comment]
Thank you - I will retry on an older machine to see if it's specific to the M2 chip or the 14. version of the OS.

**Comment by lintool** [comment]
I've included M-proc installation instructions here: https://github.com/castorini/pyserini/blob/master/docs/installation.md

Do they not work?

**Comment by sueszli** [comment]
@lintool the build in the conda environment doesn't work on my machine – but I have a feeling this is because I didn't build anserini with Java11

I will come back to this issue as soon as I figured this out
