### ISSUE TITLE
Pre-built indexes throws value error.

### ISSUE THREAD

**Issue by mrdrozdov** [castorini/pyserini#1563]
When calling:

```
LuceneSearcher.list_prebuilt_indexes()
```

I get this ValueError:

```
File ~/miniconda3/envs/torch-latest/lib/python3.9/site-packages/pyserini/search/lucene/_searcher.py:93, in LuceneSearcher.list_prebuilt_indexes()
     90 @staticmethod
     91 def list_prebuilt_indexes():
     92     """Display information about available prebuilt indexes."""
---> 93     get_sparse_indexes_info()

File ~/miniconda3/envs/torch-latest/lib/python3.9/site-packages/pyserini/util.py:193, in get_sparse_indexes_info()
    190 for index in df.keys():
    191     df[index]['downloaded'] = check_downloaded(index)
--> 193 with pd.option_context('display.max_rows', None, 'display.max_columns',
    194                        None, 'display.max_colwidth', -1, 'display.colheader_justify', 'left'):
    195     print(df)

File ~/miniconda3/envs/torch-latest/lib/python3.9/site-packages/pandas/_config/config.py:444, in option_context.__enter__(self)
    441 self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
    443 for pat, val in self.ops:
--> 444     _set_option(pat, val, silent=True)

File ~/miniconda3/envs/torch-latest/lib/python3.9/site-packages/pandas/_config/config.py:160, in _set_option(*args, **kwargs)
    158 o = _get_registered_option(key)
    159 if o and o.validator:
--> 160     o.validator(v)
    162 # walk the nested dict
    163 root, k = _get_root(key)

File ~/miniconda3/envs/torch-latest/lib/python3.9/site-packages/pandas/_config/config.py:882, in is_nonnegative_int(value)
    879         return
    881 msg = "Value must be a nonnegative integer or None"
--> 882 raise ValueError(msg)

ValueError: Value must be a nonnegative integer or None
```

Was able to fix locally by changing -1 in pd.option_context to None.

**Comment by lintool** [comment]
@mrdrozdov thanks for your report. However, I wasn't able to reproduce the bug:

```python
from pyserini.search.lucene import LuceneSearcher
LuceneSearcher.list_prebuilt_indexes()

from pyserini.index.lucene import IndexReader
IndexReader.list_prebuilt_indexes()
```

These all work fine for me.

```
% pip list | grep pandas
pandas             1.5.2
```

This is the version of pandas I'm on - perhaps it's a pandas version issue?

**Comment by mrdrozdov** [comment]
I see. It does look like an issue with newer pandas version:

```
$ pip list | grep pandas
pandas                       2.0.2
```

If the initial comment wasn't clear, the cause of Value error is `'display.max_colwidth', -1`. According to some pandas discussion, it seems like -1 was meant to be deprecated in favor of None in newer versions. References:

* https://github.com/pandas-dev/pandas/issues/31532
* https://github.com/pandas-dev/pandas/commit/78e6ec08cc6b2d9f7d42d8ae87fb7431721e7af6
* In v2.0.0 pandas officially stop supporting -1. https://github.com/pandas-dev/pandas/pull/49295/files

I "think" it's safe for pyserini to switch over to None. Here's the relevant line in pandas v1.4.0 that shows None is supported:

* https://github.com/pandas-dev/pandas/blob/1.4.x/pandas/core/config_init.py#L396

Since pyserini install with pandas >= v1.4.0, I also "think" (not 100% sure) other users may run into this problem. Switching to None seems a little cleaner than adding a pandas >= 1.4.0 & pandas < 2.0.0 constraint.
