### ISSUE TITLE
Add utility methods/class (?) for manipulating TREC runs

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#158]
We have scripts here and there for reading in TREC runs, interpolating runs, etc. Should we add them into pyserini, organized under a nice API?

Would be better than an endless proliferation of scripts...

Thoughts @rodrigonogueira4 @x65han ?

**Comment by rodrigonogueira4** [comment]
Yes, I'm all for it!

**Comment by x65han** [comment]
Sounds good to me! 💪

**Comment by x65han** [comment]
We should be able to close since we have implemented [TrecRun class](https://github.com/castorini/pyserini/blob/5eb654fa3830a5ad37f87a6096eead92a0b1f51b/pyserini/trectools/_base.py#L33). 

I am going to close this. Feel free to open if we need more than what we currently have.
