### ISSUE TITLE
Implement searcher that searches multiple indexes and fuses the results

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#160]
Call it `FusionSearcher` or something like that. Combines results via RRF by default.

**Comment by stamatisvas** [comment]
What about also include basic DIR algorithms implementation like CORI?

**Comment by lintool** [comment]
Additional code contributions always welcome!

**Comment by lintool** [comment]
Done!

**Comment by isekulic** [comment]
@lintool 
thanks for the `SimpleFusionSearcher`. I am trying to use it on two indexes with RM3. Is this a correct way to do this:
```
for s in searcher.searchers:
    s.set_rm3(10, 10, 0.5)
```

Thanks!

**Comment by lintool** [comment]
hi @isekulic - referring you to @x65han who implemented it...
