### ISSUE TITLE
Resolve unittest issues

### ISSUE THREAD

**Issue by ArthurChen189** [castorini/pyserini#1616]
inconsistent method names with `test_encoder.py`, due to refactoring the ONNX query encoder in Anserini

**Comment by lintool** [comment]
Unit tests for me... did you update your branch?

**Comment by ArthurChen189** [comment]
Hrmm weird. And yeah, my branch is up-to-date with the castorini upstream

**Comment by ArthurChen189** [comment]
I ran the unittest with anserini 0.22.0's fatjar on both my local end and ORCA....

**Comment by SumonKantiDey** [comment]
How much time does it take to complete the unit test? I am trying the unit test with ```anserini-0.22.1-SNAPSHOT-fatjar.jar``` but somehow it takes a significant amount of time.

**Comment by lintool** [comment]
```
Ran 308 tests in 321.069s

OK
```

On my main dev machine:

<img width="270" alt="Screen Shot 2023-09-04 at 5 31 20 PM" src="https://github.com/castorini/pyserini/assets/313837/516ea0ba-badb-4c33-8160-0db131e23412">

**Comment by lintool** [comment]
Closing issue since #1617 has been merged.
