### ISSUE TITLE
Error for SPLADE on-the-fly encoding with pytorch  

### ISSUE THREAD

**Issue by ArthurChen189** [castorini/pyserini#1625]
command used:
```bash
python -m pyserini.search.lucene --threads 12 --batch-size 128 \
  --index msmarco-v1-passage-splade-pp-ed \
  --topics msmarco-passage-dev-subset \
  --encoder naver/splade-cocondenser-ensembledistil \
  --output run.msmarco-v1-passage.splade-pp-ed-pytorch.dev.txt \
  --hits 1000 --impact
```

error message:
> ...
>   File "/home/arthur/workplace/pyserini/pyserini/encode/_splade.py", line 28, in encode
>     raw_weights = self._output_to_weight_dicts(batch_token_ids, batch_weights)
> NameError: name 'batch_token_ids' is not defined

**Comment by lintool** [comment]
Confirmed that I can reproduce the bug.

Interestingly, from here - https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html

We have "SPLADE++ SelfDistil: query inference with ONNX" as a condition, but *not* "SPLADE++ SelfDistil: query inference with PyTorch."

**Comment by ArthurChen189** [comment]
> Confirmed that I can reproduce the bug.
> 
> Interestingly, from here - https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html
> 
> We have "SPLADE++ SelfDistil: query inference with ONNX" as a condition, but _not_ "SPLADE++ SelfDistil: query inference with PyTorch."

I will add all entries mentioned in the paper once all results are reproduced.

**Comment by lintool** [comment]
I will add this condition to 2CR before closing this issue.
