### ISSUE TITLE
DPR encoder seemingly missing attention mask

### ISSUE THREAD

**Issue by searchivarius** [castorini/pyserini#1683]
Hi, is it intentional that the DPR encoder doesn't use the attention mask?

https://github.com/castorini/pyserini/blob/f1d623cdcb12c3083ff1db8aed4b84e81951a18c/pyserini/encode/_dpr.py#L50

**Comment by lintool** [comment]
@MXueguang thoughts here? if no longer relevant, let's close?

**Comment by MXueguang** [comment]
https://github.com/huggingface/transformers/blob/97c00cdfe132164dbd793447a088432fa359fd36/src/transformers/models/dpr/modeling_dpr.py#L488

DPR create mask attention automatically

**Comment by searchivarius** [comment]
@MXueguang I did not dive that deep and missed this fact: thank you for clarifying!
