### ISSUE TITLE
duplicate query encoder code 

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#1728]
https://github.com/castorini/pyserini/blob/master/pyserini/encode/__init__.py

https://github.com/castorini/pyserini/blob/master/pyserini/search/faiss/_searcher.py

we want to use the encoder defined in pyserini/encode

need a clean up.

**Comment by lintool** [comment]
I've started doing prep work for this, via #2003 and #2004 - making sure only dense retrieval models still work, updating docs there. Otherwise, we have no guardrails to check whether the refactoring is actually correct.

**Comment by lintool** [comment]
cf. #1812

**Comment by lintool** [comment]
Closed by #2008
