### ISSUE TITLE
Access term frequencies in index

### ISSUE THREAD

**Issue by stamatisvas** [castorini/pyserini#174]
I need to access statistics of my index like tf, tf-idf etc. I want to answer questions like: In how many documents does a spesific term occur in? What documents does a spesific term occur in? What terms occur in the 1st document. Is there any way to do this using pyserini? Thanks!

**Comment by lintool** [comment]
These features are explained in the documentation: https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md
