### ISSUE TITLE
How to build collections using msmarco and beir

### ISSUE THREAD

**Issue by BeastyZ** [castorini/pyserini#1751]
Hi, I see that you provide faiss-based preindex, can you provide collections for building preindex? If it is not convenient, can you tell us what fields are used for each dataset to build the collections?
I want to use these collections to build an index on the new retriever.

**Comment by MXueguang** [comment]
Hi, we get the collections from the beir github repo https://github.com/beir-cellar/beir
title are prepended to the text body when it is available.

**Comment by BeastyZ** [comment]
I didn't realize that you were also a major contributor to this repository, thanks again for your help.
