### ISSUE TITLE
trec_eval error

### ISSUE THREAD

**Issue by BeastyZ** [castorini/pyserini#1756]
Hi, I'm using trec_eval to get the results of climate-fever dataset. However, the following error was encountered：
pandas.errors.ParserError: Error tokenizing data. C error: Expected 6 fields in line 28, saw 7

I checked line 28, and it looks like this：
2790 Q0 IPCC_supplementary_report,_1992 8 174.5734100341797 rank

My execution script is as follows：
`python -m pyserini.eval.trec_eval -c -m ndcg_cut.10 beir-v1.0.0-climate-fever-test results/climate-fever/retriever_llm_top10_trec`

By the way, after removing the comma in line 28, I re-executed the script and encountered the same error on the new line.

Is there a solution?

**Comment by BeastyZ** [comment]
When I tried to reproduce the results you provide in [BEIR](https://castorini.github.io/pyserini/2cr/beir.html), I encountered the same error mentioned above.

Specific scripts are below:
```
python -m pyserini.search.faiss \
  --threads 16 --batch-size 512 \
  --encoder-class contriever --encoder facebook/contriever-msmarco \
  --index beir-v1.0.0-climate-fever.contriever-msmarco \
  --topics beir-v1.0.0-climate-fever-test \
  --output run.beir.contriever-msmarco.climate-fever.txt \
  --hits 1000 --remove-query

python -m pyserini.eval.trec_eval \
  -c -m ndcg_cut.10 beir-v1.0.0-climate-fever-test \
  run.beir.contriever-msmarco.climate-fever.txt
```

**Comment by MXueguang** [comment]
Hi @BeastyZ,
What is your pandas version? mine is pandas 2.1.1

**Comment by BeastyZ** [comment]
I changed the pandas version to 2.1.1, but it didn't work.

**Comment by MXueguang** [comment]
I just found a relevant issue here https://github.com/castorini/pyserini/issues/1658
are you using latest pyserini code?

**Comment by BeastyZ** [comment]
Now, my pandas version is 2.1.1 and pyserini version is 0.22.1 which is the latest one, I still got the same error.

**Comment by BeastyZ** [comment]
Hi @MXueguang 
You are right! I re-examined the contents to be evaluated, and found that there were something irrelevant in it, which should be caused by my improper operation before. Now commas don't interfere with normal evaluation. Thank you for your timely help.
