### ISSUE TITLE
ValueError: Topic beir-v1.0.0-robust04.test.splade-pp-ed Not Found

### ISSUE THREAD

**Issue by ChuanMeng** [castorini/pyserini#1782]
Hi,
When I try to replicate the result of splade-pp-ed on robust04 following https://castorini.github.io/pyserini/2cr/beir.html, I used the commands:
`python -m pyserini.search.lucene \
  --threads 16 --batch-size 128 \
  --index beir-v1.0.0-robust04.splade-pp-ed \
  --topics beir-v1.0.0-robust04.test.splade-pp-ed \
  --output run.beir.splade-pp-ed.robust04.txt \
  --output-format trec \
  --hits 1000 --impact --remove-query
`
But, I got the following error:
`
raise ValueError(f'Topic {collection_name} Not Found')
ValueError: Topic beir-v1.0.0-robust04.test.splade-pp-ed Not Found
`
I used the latest version, pyserini-0.24.0.

Best wishes,
Chuan

**Comment by lintool** [comment]
Hi @ChuanMeng sorry for the late reply on this: it may be the case that the run you references has been been published on PyPI (yet) - it should work fine on the "dev" install.
