### ISSUE TITLE
how to use trained retriever?

### ISSUE THREAD

**Issue by stellakke** [castorini/pyserini#1787]
Hello! Previously, I was able to load a pre-trained model to perform retrieval using the following code segment:
```
encoder = AutoQueryEncoder('facebook/contriever', pooling='mean', device='cuda:0')
searcher = FaissSearcher(index_dir, encoder)
```
How can I use a trained contriever checkpoint (for example, how to specify the path)?
Thank you!

**Comment by MXueguang** [comment]
I think it should work by just replacing the huggingface model name by the checkpoint path. Let me know if there is any issue.

**Comment by lintool** [comment]
@stellakke seeing no further follow-up, closing... please re-open if needed.
