### ISSUE TITLE
Missing MS MARCO v2 doc 2CRs

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1809]
Here: https://castorini.github.io/pyserini/2cr/msmarco-v2-doc.html

We're missing uniCOIL (noexp) and uniCOIL (w/ doc2query-T5) for TREC 2023.

@MXueguang can you please add this?

**Comment by lintool** [comment]
@sahel-sh I added the Qrels bindings for DL23 here? https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/eval/Qrels.java#L51

**Comment by sahel-sh** [comment]
Yyou are right about Qrels, but the topics are not added in the cl[1]
and because of that, I didn't add them in the pyesrini cl either[2]
[1]https://github.com/castorini/anserini/pull/2403/files#diff-95ab9a3ffbdf23186b81145976d876c86b59672a00040ddae7054276032a7a00
[2]https://github.com/castorini/pyserini/pull/1804/files

**Comment by lintool** [comment]
Topic bindings appear to be there already... https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/topicreader/Topics.java#L88 

Must have been added in another PR?

**Comment by lintool** [comment]
Hi @sahel-sh with this PR https://github.com/castorini/anserini/pull/2414

I've added the missing uniCOIL conditions for MS MARCO v2 passage: https://castorini.github.io/pyserini/2cr/msmarco-v2-passage.html

<img width="1330" alt="Screen Shot 2024-03-26 at 7 19 19 AM" src="https://github.com/castorini/pyserini/assets/313837/aba11aa7-94b9-433f-8ca5-d3ab6edf8821">

I think we can fill in the missing conditions now?

**Comment by sahel-sh** [comment]
taking this over after chatting with @lintool, I will work on it this weekend

**Comment by lintool** [comment]
Closed by #1844
