### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by stamatisvas** [castorini/pyserini#182]
Hi. I getting the error "ImportError: DLL load failed: The specified module could not be found." when trying to import both of:
from pyserini.search import pysearch
from pyserini.search.pysearch import SimpleSearcher

The modules have installed and they are recommended from the editor when typing them. I am using pycharm, python 3.7.6 and tried both pyserini==0.9.0.0 pyserini==0.9.3.0.

**Comment by rodrigonogueira4** [comment]
I'm getting this error too when installing via pip. I tried on different python envs and OSes (mac and ubuntu).

However, it works fine if I follow dev instructions (https://github.com/castorini/pyserini/#development-installation).

**Comment by lintool** [comment]
Yes, correct - the instructions no longer align with the PyPI package due to recent refactoring. We're cleaning up a few loose ends and then pushing a new package soon...

**Comment by rodrigonogueira4** [comment]
Got it!

**Comment by stamatisvas** [comment]
It seems it was an enviroment issue. I was using linux subsystem in windows. When I changed to full Linux at least I am able to import SimpleSearcher. The unittests cannot be passed though. I am running "python -m unittest" in the top folder of pyserini and the main issues is:
AttributeError: 'io.anserini.search.SimpleSearcher' object has no attribute 'getTotalNumDocuments'. I am getting the same error when trying:
 "searcher = SimpleSearcher('/home/split1_sgml_anserini_indices/A')". 
The full file with the erros of the unitests is here:

[pyserini_errors.txt](https://github.com/castorini/pyserini/files/4763006/pyserini_errors.txt)

**Comment by lintool** [comment]
That method definition is here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L342

Did you copy the fatjar over from Anserini? Do an `ls` on `pyserini/resources/jars/` and report back what you have in there?

**Comment by stamatisvas** [comment]
I moved to google colab and everything seems to work by now. Yes I copy the fatjar file from anserini. I have attached a screenshot of the jars folder. 

![Capture](https://user-images.githubusercontent.com/35704488/84392954-acab2c80-ac03-11ea-8cfa-328ca1fae0ea.PNG)

**Comment by lintool** [comment]
Glad you got everything worked out, but it looks like you didn't pull the latest branch from the anserini repo. We up to 0.9.3 now, so the jar should be `0.9.4-SNAPSHOT`.
