### ISSUE TITLE
Pyserini library not working in google colab

### ISSUE THREAD

**Issue by bhavikchandana** [castorini/pyserini#1862]
while import pyserini library, I am getting this error

JavaException: JVM exception occurred: io/anserini/eval/Qrels has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0 java.lang.UnsupportedClassVersionError
Can you tell how to solve this problem??

**Comment by bhavikchandana** [comment]
Got the solution. Just go back to older version of pyserini :). Pls look into this...

**Comment by lintool** [comment]
You need to upgrade your JVM to JDK 21. Per the README:

<img width="846" alt="Screen Shot 2024-04-13 at 11 21 07 AM" src="https://github.com/castorini/pyserini/assets/313837/f6e4aea0-318a-47d4-bdda-44401574211c">

**Comment by bhavikchandana** [comment]
Yeah thanks the upgrading is not happening on colab from my side... Still downgrading pyserini version worked

**Comment by felixsteinerpy** [comment]
Upgrading to JDK21 with the following commands worked for me.

```
%%capture output
import os

!apt-get install openjdk-21-jre-headless -qq > /dev/null
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"
!update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
!java -version

!pip install pyserini
```
