### ISSUE TITLE
Does pyserini.search include deep learning 2023 (dl23) track of the TREC dataset?

### ISSUE THREAD

**Issue by sina-nabavi** [castorini/pyserini#1878]
I can only retrieve up to `dl20` with `get_topics` and `get_qrels`. Could you please resolve this?

**Comment by lintool** [comment]
I do see later topics:
https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L84

And qrels:
https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L416

What version of the code are you running?

**Comment by sina-nabavi** [comment]
I was using `pyserini==0.24.0`. I will update it. Thank you!
