### ISSUE TITLE
Access Index from colab

### ISSUE THREAD

**Issue by stamatisvas** [castorini/pyserini#189]
Hi. I have an anserini index trying to access its stastistics so I am following this:
https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md

when I type:
from pyserini import analysis, index
index_reader = index.IndexReader()
I am getting:
AttributeError                            Traceback (most recent call last)
<ipython-input-45-adb8071daf26> in <module>()
      1 from pyserini import analysis, index
      2 
----> 3 index_reader = index.IndexReader()

AttributeError: module 'pyserini.index' has no attribute 'IndexReader'

**Comment by lintool** [comment]
@stamatisvas As we've already mentioned, the PyPI version is out of date with respect to the latest documentation. To use the features in the latest documentation, you'll need the Development Installation, as we outlined here: https://github.com/castorini/pyserini/#development-installation

Or you can wait until we release a new PyPI version which hopefully will happen some time later today.
