### ISSUE TITLE
Create a `Rerank` module in Pyserini

### ISSUE THREAD

**Issue by ToluClassics** [castorini/pyserini#1926]
Currently we are able to do `pyserini.search.faiss.FaissSearcher` for dense retrieval and `pyserini.search.lucene.LuceneSearcher` for sparse retrieval.

I think it would be nice to have a module like `pyserini.rerank.......` that takes in a query and a set of documents and maybe uses `rankllm` and whatever reranker is implemented to return a reranked set.

**Comment by lintool** [comment]
We've actually discussed this idea within the group - the conclusion, iirc, was to put reranking functionality in another package (e.g., `rank_llm`) and let pyserini focus on 1st stage retrieval.

Ref: https://github.com/castorini/rank_llm/issues/109
