### ISSUE TITLE
PyPI Installation with issue with nmslib

### ISSUE THREAD

**Issue by natek-1** [castorini/pyserini#1961]
I am working using an M1 Pro MacBook Pro, however when following the installation instructions using python 3.10, I get an error when doing the following command:

```
conda install -c conda-forge lightgbm nmslib -y 
```

Here is what the error looks like

```
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - nmslib

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I tried various ways to install nmslib. However even if those methods work It still creates an error when running the following command

```
pip install -e .
```

**Comment by lintool** [comment]
Interesting... recent updates may have rendered our docs out of date. Looking at: https://anaconda.org/conda-forge/nmslib

Doesn't seem to provide arm architecture for osx (anymore)?!

However, `nmslib` still seems to be available here:
https://anaconda.org/anaconda/nmslib

@natek-1 try installing from there?

**Comment by natek-1** [comment]
It seems to work. 
For clarification I used the following cmd
```
conda install anaconda::nmslib
```
thank you @lintool !
