### ISSUE TITLE
Dump out tf-idf document vectors in pyserini

### ISSUE THREAD

**Issue by alirezamirzaeiyan** [castorini/pyserini#2]
Is it possible to dump out tf-idf document vectors for retrieved documents in pyserini?

**Comment by lintool** [comment]
hi @zeynepakkalyoncu - let's see if we can make this happen?

**Comment by lintool** [comment]
So, if we just want td-idf values, it'll be fairly easy, we can just compute the td-idf values in Python.

However, if we want accurate BM25 values, we'll have to do something like this:
https://github.com/castorini/anserini/blob/master/src/test/java/io/anserini/integration/IndexerTest.java#L264

... which will be slow.

**Comment by alirezamirzaeiyan** [comment]
Could you please describe your solution to compute tf-idf values in python?

**Comment by lintool** [comment]
hi @alirezamirzaeiyan 

We just need to port this over to Java:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexUtils.java#L219

It's on @zeynepakkalyoncu 's todo list, but if you want to do it yourself, code contributions are welcome!
