### ISSUE TITLE
faiss is not the same as faiss-cpu, or - I hate Python dependencies

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#2023]
On Mac ARM, the current Pyserini recipe is:

```
conda deactivate
conda env list
conda create -n pyserini-pypi-test python=3.10 -y
conda activate pyserini-pypi-test

conda install -c conda-forge openjdk=21 maven -y

conda install -c conda-forge lightgbm -y
conda install -c anaconda nmslib -y
conda install -c pytorch faiss-cpu -y

pip install 'pyserini[extras]==0.42.0'

# seems like we need to explicitly downgrade in this case
pip install numpy==1.26.4

conda deactivate
conda env list
conda env remove --name pyserini-pypi-test
```

If you follow the above, you end up in this state:

```bash
% pip list | grep faiss
faiss              1.9.0
faiss-cpu          1.9.0
```

Basically, weird interactions between the two packages that manifests in JVM errors.

Why does this happen? It's because this command:

```
conda install -c pytorch faiss-cpu -y
```

Installs `faiss`, even though you'd think it installs `faiss-cpu`... but wait, `faiss-cpu` is an actual PyPI package, so when you go and install Pyserini:

```
pip install 'pyserini[extras]==0.42.0'
```

You end up with an _actual_ package named `faiss-cpu`.

I _think_ the solution is to change `faiss-cpu` back to `faiss` in `pyproject.toml`? This is because installing `faiss` via conda is probably preferred, and so when we get to the `pip` install, the dependency is already satisfied?

**Comment by lintool** [comment]
Indeed, before this spate of recent package refactoring, in the old `requirements.txt`, it was indeed:

```
faiss>1.7.0
```

See: https://github.com/castorini/pyserini/pull/2019

Don't recall the rationale for changing to `faiss-cpu`, but reverting should fix.

**Comment by maximilianmordig** [comment]
This is broken. There is no faiss>1.7.0 on pypi, only 1.5.3
But it would work if reverted back to faiss-cpu.
