### ISSUE TITLE
search different fields

### ISSUE THREAD

**Issue by luomancs** [castorini/pyserini#203]
Hi, 

I wonder if pyserini allows us to search different fileds? for example, if I have "title" and "content", can I specify which field I want to search? 

Thank you

**Comment by lintool** [comment]
This can be done already, you just have to assemble the pieces. Use this as a starting guide: https://github.com/castorini/pyserini/blob/master/docs/usage-querybuilder.md

In particular, change the field here when creating a term query:
https://github.com/castorini/pyserini/blob/master/pyserini/search/querybuilder.py#L56

**Comment by lintool** [comment]
Having heard nothing further on this, closing issue.
