### ISSUE TITLE
SimpleSearcher.search() Hanging

### ISSUE THREAD

**Issue by theshevon** [castorini/pyserini#220]
I've been working on a website where the front-end is `React` app and the Back-end is a `Flask` API, both of which are deployed via an `nginx` reverse proxy on a `CentOS RHEL 7.8` server.

The website features a search engine, which a user can utilise in order to find published literature sourced from a Lucene-based index. To do this, we made use of Pyserini on our Flask API to extract the search results (prior to processing it and sending back to the user). What we have noticed is that `SimpleSearcher.search()` hangs in production, especially for search queries that yield a large number of hits (Nonsense queries like `"asd"`, which yielded ~8 results worked fine, but legitimate queries like `"virus"`, which yielded 100+ results caused the function to hang). 
The code snippet of interest from our controller for the `/search` route is as follows:

```
from pyserini.search import SimpleSearcher

MAX_SEARCH_RESULTS = 200

dirname = os.path.dirname(__file__)
index_dir = os.path.join(dirname, '../search/index/')
searcher = SimpleSearcher(index_dir)

def get_search_results(query):
 
    # retrieve the results
    hits = searcher.search(query, k=MAX_SEARCH_RESULTS)

    # process the results
    ...
```

I tried to reproduce the issue on a standalone `.py` file but failed to do so. 

Therefore, in order to prevent our uwsgi workers from hanging (and consequently causing the entire website to hang for all subsequent queries), I tried to trap the error within a `try/ except` block by making use of the  `func_timeout` module.

```
from func_timeout import func_set_timeout, FunctionTimedOut
from pyserini.search import SimpleSearcher

MAX_SEARCH_RESULTS = 200
MAX_SEARCH_TIME = 10

dirname = os.path.dirname(__file__)
index_dir = os.path.join(dirname, '../search/index/')
searcher = SimpleSearcher(index_dir)

def get_search_results(query):
 
    # retrieve the results
    @func_set_timeout(MAX_SEARCH_TIME)
    def get_hits(query):
        hits = searcher.search(query, k=MAX_SEARCH_RESULTS)
        return hits

    try:
        hits = get_hits(query)
    except Exception as e:
        raise Exception("Timed out while searching :(")
    
    # process the results
    ...
```

However, once I did this, even the nonsense queries caused the function to hang, leading me to believe that the issue might be happening because `SimpleSearcher.search()` is run within a process (and so, might be related to #15). Given that each uwsgi is technically a process, it further backs my theory that this issue is related to multiprocessing. It also explains why I couldn't reproduce the issue in an isolated `.py` file.

**Comment by lintool** [comment]
Hi @theshevon - thanks for your detailed report. I've asked @edwinzhng to comment. In the meantime, you might want to take a look on how we build an end-to-end application in Covidex: https://github.com/castorini/covidex

**Comment by edwinzhng** [comment]
Hey @theshevon, do you mind sending the Flask code to run with? I think you're right in that it's related to Python multiprocessing but I can't seem reproduce it locally right now.

For Covidex (mentioned above) we used the FastAPI framework which runs an ASGI server called [Uvicorn](https://www.uvicorn.org/), instead of the Flask UWSGI server, and this doesn't seem to hang at all for us. If you have the ability to move away from Flask for now, maybe you could try that instead? I'll take a closer look later this week

**Comment by theshevon** [comment]
Hi @lintool @edwinzhng, I'm extremely sorry for the late response- I kept getting side-tracked with some other commitments, unfortunately! 

With the Pyserini issue persisting, I implemented a workaround by building an index on neo4j and just running search queries through that. However, my team and I would prefer to have Pyserini working as we believe it will provide more relevant results.

@edwinzhng Just so we're on the same page, did you want access to the implementation of the entire Flask API, or did you want me to send a specific snippet of code? I don't think we will be able to move away from Flask given that so much has been done already and refactoring it would not be an ideal use of time.

**Comment by edwinzhng** [comment]
Hey @theshevon, just a functional snippet (maybe a basic Flask setup that would reproduce the issue) would be great!

**Comment by theshevon** [comment]
Hi @edwinzhng, apologies for the late response- I'll be much more responsive from hereon out.

Regarding the Flask snippet, I haven't been able to reproduce the issue on my local machine, even with a `func_timeout` decorator, so I don't think sending you a functional snippet will serve much of a purpose. It does however seem to occur when I use a Flask UWSGI server, so might be specific to that use case.

**Comment by theshevon** [comment]
Hi @edwinzhng, just wanted to follow up and ask if there is anything else I could provide that may help with debugging?

**Comment by edwinzhng** [comment]
hey @theshevon, sorry I've been super busy with other stuff, I'll get back to you on this when I get a chance
