### ISSUE TITLE
build index with multiple fields. 

### ISSUE THREAD

**Issue by luomancs** [castorini/pyserini#221]
Hi, 

In my data, there are multiple fields rather than id and contents only, for example, I have "title" filed, how can I build index such that it also includes the title information? If I use the following command that you shown in the readme, I can not get the title filed by search.doc(docid).get("title"), which I guess "title" is not indexed. 

python -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator \
 -threads 1 -input integrations/resources/sample_collection_jsonl \
 -index indexes/sample_collection_jsonl -storePositions -storeDocvectors -storeRaw

**Comment by lintool** [comment]
There are two options:

(1) preprocess your corpus to stick whatever you want to index into the contents field.

(2) write custom code. This can't be done in Python - you'll need to write a custom generator in Anserini (Java) that takes the right fields and sticks it into the index. See sample classes:
https://github.com/castorini/anserini/tree/master/src/main/java/io/anserini/index/generator

If you go down this route, check out the test cases to guide you.

**Comment by luomancs** [comment]
Hi 

Thanks for your quick response, I had written a generator for my dataset, but how can I use this generator to build the index? and what is the test cases that you mention? 

thank you

**Comment by lintool** [comment]
Use the generator in the `-generator` option. To do this from Python I would suggest indexing from Anserini (in Java), not Python. To expose the Java class in Python you'll have to do this: https://github.com/castorini/pyserini/#development-installation

Test cases:
https://github.com/castorini/anserini/tree/master/src/test/java/io/anserini/index/generator
https://github.com/castorini/anserini/tree/master/src/test/java/io/anserini/integration

**Comment by luomancs** [comment]
thanks!

**Comment by lintool** [comment]
Closing.
