### ISSUE TITLE
Can't get any hits

### ISSUE THREAD

**Issue by yy147** [castorini/pyserini#224]
Hello, I tried to apply Pyserini to retrieve documents from Wikipedia. I used Lucene 7.0.0 to parse the latest wiki dumps file: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2. However, when I tried to run the code, it can't get any hits. I'm not sure if it is because of my Lucene version or something else. I played with some existing indexes, which are all working well. Would you mind giving me some advice? Thanks a lot.

**Comment by lintool** [comment]
Hi @yy147 can you explain what you mean by "used Lucene 7.0.0 to parse the latest wiki dumps file"?

Did you follow these instructions? https://github.com/castorini/pyserini/#how-do-i-search-my-own-documents

**Comment by yy147** [comment]
Hello Jimmy, Thanks for your quick reply. I will have a look at the instruction. Regarding my above question, generally, I downloaded the latest wiki dumps file from https://dumps.wikimedia.org and then indexed the document using Apache.Lucene (version 7.0.0). I supposed to generate indexes just like `lucene-index-covid-paragraph-2020-04-10`. However, after I got the latest index, I pass it through `Pyserinir.search` but nothing searched. Is that because of the format of the original document (Wikipedia)? Or should I try a different version of Apache.Lucene?

**Comment by lintool** [comment]
Yes, correct - the indexes that you've generated are not compatible with the schema expected by Pyserini.

Write a Python script (e.g., with https://github.com/attardi/wikiextractor ) to convert the wikimedia dumps into the format Pyserini expects, and that should work. If you manage to do this, we'd appreciate a pull request  and a contribution back to the code base. Seems like a common-enough feature that others will find useful.

Let me know if there's anything else. Closing issue for now.
