### ISSUE TITLE
Not all Collection/Generator classes from Anserini is available in Pyserini

### ISSUE THREAD

**Issue by adamyy** [castorini/pyserini#231]
I was going to use the [collection/generator API](https://github.com/castorini/pyserini/blob/master/docs/usage-collection.md) to generate Lucene documents from for the ACL collection. However I noticed that we only export a [subset](https://github.com/castorini/pyserini/blob/master/pyserini/collection/_base.py#L31) of collection and generator classes in Anserini, and `AclAnthology` happens to be excluded.

Was there a reason for this? Am I free to add `AclAnthology` and `AclAnthologyGenerator`?

**Comment by lintool** [comment]
Yes, please do. Only reason they're not in Pyserini is because we haven't had the needs until now...

**Comment by lintool** [comment]
Closing issue. Resolution is "we'll add bindings as they are needed..."
