### ISSUE TITLE
get -1 unique terms in index stats 

### ISSUE THREAD

**Issue by qguo96** [castorini/pyserini#236]
For indexes `ms-marco-passage` and `ms-marco-doc`:
                  When `index_reader.stats()` is executed, we get unique terms is `-1`.
There might be an issue with an underlying method.

**Comment by lintool** [comment]
This isn't a bug, as I explain here: https://github.com/castorini/pyserini/blob/master/docs/usage-indexreader.md#how-do-i-access-basic-index-statistics

Unless the index has been "optimized", i.e., merged into a single segment, the number of unique terms is not available.
