### ISSUE TITLE
Lucene Document is empty

### ISSUE THREAD

**Issue by DragonYyc** [castorini/pyserini#242]
Hello, 

I'm working on a new index from Wikipedia datasets using `python3 -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator -threads 2 -input ${DOWNLOAD_PATH} -index ${DOWNLOAD_PATH} -storePositions -storeDocvectors -storeRaw`. 

Here is my data structure is stored in a .jsonl file: 
```
{
"id": "621.0005", 
"contents": “…”, 
"title": “…”
}
{
"id": "622.0001”, 
"contents": “…”, 
"title": “…”
}
```

But when we look at the hit's information, the title and contents are all `None`. Does anyone know what happens here? Thanks for all your help.

**Comment by lintool** [comment]
Try adding `-storeContents`?

**Comment by DragonYyc** [comment]
Aha, thanks a lot, Jimmy. yes, it works now.
