### ISSUE TITLE
`from_prebuilt_index` doesn't exist?

### ISSUE THREAD

**Issue by scottpchow23** [castorini/pyserini#246]
Hi there!

I was toying around with pip installation of pyserini (0.9.4.0) and was having trouble with the following code snippet:

```python
from pyserini.search import SimpleSearcher

searcher = SimpleSearcher.from_prebuilt_index('trec45')
hits = searcher.search('hubble space telescope')

# Print the first 10 hits:
for i in range(0, 10):
    print(f'{i+1:2} {hits[i].docid:15} {hits[i].score:.5f}')
```

When I run it with Python 3.9.0, I get the following error:

```
Traceback (most recent call last):
  File "spike.py", line 3, in <module>
    searcher = SimpleSearcher.from_prebuilt_index('trec45')
AttributeError: type object 'SimpleSearcher' has no attribute 'from_prebuilt_index'
```

Any ideas what I might be doing wrong, or did I misinterpret the documentation [here](https://github.com/castorini/pyserini#how-do-i-build-searchers):

> There are two ways to build searchers.
>    To build a searcher with a path to a directory containing the index.
>     ```searcher = SimpleSearcher('indexes/index-robust04-20191213/')```
>    To build a searcher with the index's identifier name.
>     ```searcher = SimpleSearcher.from_prebuilt_index('trec45')```

I am able to verify that `SimpleSearcher` works like a charm when provided a path to a local index.

**Comment by lintool** [comment]
Hi @scottpchow23 - `from_prebuilt_index` hasn't been published on pypi yet... sorry, we're running a bit behind on pushing out the latest features... so you'll need to do a dev install from master HEAD: https://github.com/castorini/pyserini/#development-installation

**Comment by scottpchow23** [comment]
All good! I was just worried something was going wrong in my environment. I'll live with my local index for the moment 👍

**Comment by lintool** [comment]
hi @scottpchow23 the pre-built index feature is now available in the latest release! https://pypi.org/project/pyserini/0.10.0.0/

If you'd like to give it a test drive, please let us know if you run into any issues.
