### ISSUE TITLE
Using pre-built indexes from command-line

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#248]
Currently, we can do this:

```
python -m pyserini.search --topics msmarco_doc_dev \
 --index indexes/index-msmarco-doc-20201117-f87c94 \
 --output runs/run.msmarco-doc.dev.bm25.txt --bm25
```

But this isn't set up to take advantage of pre-built indexes.

@qguo96 would you mind working on this?

**Comment by qguo96** [comment]
Sure, do you think this looks ok?
```
python -m pyserini.search --topics msmarco_doc_dev \
 --output_directory runs --bm25
```

**Comment by lintool** [comment]
Let's keep the `--index` option?

```
python -m pyserini.search --topics msmarco_doc_dev \
 --index robust04 \
 --output runs/run.msmarco-doc.dev.bm25.txt --bm25
```

What if we overload the `--index` option - priority is to look for local index, and then checks prebuilt if local isn't found?

**Comment by qguo96** [comment]
Sure, this is a good idea.

**Comment by qguo96** [comment]
PR(#251) to solve this.

**Comment by lintool** [comment]
Done!
