### ISSUE TITLE
Add support for output in MS MARCO in pyserini.search

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#253]
Currently, we can do this, which is great!

```
python -m pyserini.search --topics msmarco_doc_dev \
 --index ms-marco-doc \
 --output runs/run.msmarco-doc.dev.bm25.txt --bm25

```

However, we can't do this for MS MARCO passage, because it's a different output format, see:
https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md#performing-retrieval-on-the-dev-queries

Can we add a `--msmarco` option to specify output in MS MARCO format? (Leave default as TREC format.)

@qguo96 can you work on this please?

**Comment by qguo96** [comment]
Sure. 
Just to clarify, the output should be in TREC format (like `run.msmarco-passage.dev.small.trec`) with `msmarco` option? Or just `tsv`?

**Comment by lintool** [comment]
Something like this is TREC-eval format:

```
1000000 Q0 D2415605 1 9.812300 Anserini
1000000 Q0 D2056829 2 9.738900 Anserini
1000000 Q0 D1192522 3 9.645700 Anserini
1000000 Q0 D1382478 4 9.515900 Anserini
1000000 Q0 D1985588 5 9.458100 Anserini
1000000 Q0 D3019499 6 9.456600 Anserini
1000000 Q0 D1003149 7 9.432000 Anserini
1000000 Q0 D2263688 8 9.356400 Anserini
1000000 Q0 D1280733 9 9.346100 Anserini
1000000 Q0 D1671758 10 9.340400 Anserini
```

This is MS MARCO format:

```
188714	4321742	1
188714	4321745	2
188714	569374	3
188714	6442308	4
188714	894638	5
188714	2966215	6
188714	747661	7
188714	448748	8
188714	8029904	9
188714	5838198	10
```

Got it?

**Comment by qguo96** [comment]
I understand, thanks!

**Comment by qguo96** [comment]
Make PR(#255) for this.

**Comment by lintool** [comment]
#257 resolved, so this issue is wrapped up.
