### ISSUE TITLE
Tiny difference in MRR@10 for MS MARCO passage using pyserini.search

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#257]
hey @qguo96 - here's what I'm getting:

```
$ python -m pyserini.search --topics msmarco_passage_dev_subset --index ms-marco-passage --output runs/run.msmarco-passage.2.txt --msmarco --bm25
$ python tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.2.txt
#####################
MRR @10: 0.18741227770955543
QueriesRanked: 6980
#####################
```

Although note that the MRR@10 here (https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md) is:

```
#####################
MRR @10: 0.18741227770955546
QueriesRanked: 6980
#####################
```

Note the tiny difference in the final digit. Would you mind looking into this? Diff the actual output from both cases and try to see what's going on? Just wanted to make sure this wasn't a bug...

**Comment by qguo96** [comment]
Sorry, I noticed the difference before, but I remember that we can ignore such a tiny difference (in tr4tr book).
Sure I will look at it.

**Comment by lintool** [comment]
This is actually quite remarkable:

```
$ python -m pyserini.search --topics msmarco_passage_dev_subset --index ms-marco-passage --output runs/run.msmarco-passage.2.txt --msmarco --bm25
$ python tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.2.txt
#####################
MRR @10: 0.18741227770955543
QueriesRanked: 6980
#####################

$ python tools/scripts/msmarco/retrieve.py --hits 1000 --threads 4 \
   --index ~/.cache/pyserini/indexes/index-msmarco-passage-20201117-f87c94.1efad4f1ae6a77e235042eff4be1612d/ \
   --queries tools/topics-and-qrels/topics.msmarco-passage.dev-subset.txt \
   --output runs/run.msmarco-passage.3.txt
$ python tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.3.txt
#####################
MRR @10: 0.18741227770955546
QueriesRanked: 6980
#####################
```

So, we notice that the MRR is different: look at the last digit in the metric.
One obvious difference is the iteration order in which we go through the queries.
Okay, so let's just factor that out by sorting the runs:

```
$ sort runs/run.msmarco-passage.2.txt > runs/run.msmarco-passage.2.sorted.txt
$ sort runs/run.msmarco-passage.3.txt > runs/run.msmarco-passage.3.sorted.txt
$ diff runs/run.msmarco-passage.2.sorted.txt runs/run.msmarco-passage.3.sorted.txt
```

... which means, the runs are identical, and the metric differences are attributable to the iteration order of the queries...
So we're bumping into a floating point issue.

**Comment by qguo96** [comment]
I randomly shuffled the order of queries, and I got different metrics each time.
To get the metric as the experiment document, we may need to modify this method `getTopicsWithStringIds(Topics topics)` in anserini.
If we use `LinkedHashMap` instead of `HashMap`, we can maintain the queries' order and get the same metric number.

I notice that you are preparing the next release of anserini, can I make PRs in anserini now?

**Comment by qguo96** [comment]
May I ask why we use a sorted map of ids to topics in Anserini's TopicReader class? Is there any reason we have to do this?

**Comment by lintool** [comment]
> May I ask why we use a sorted map of ids to topics in Anserini's TopicReader class? Is there any reason we have to do this?

No specific rationale. I think I made a bad choice in the beginning to implement topics as a sorted map. I've previously thought about fixing it, but there are too many dependencies throughout the codebase for this to be worthwhile... :(

**Comment by qguo96** [comment]
Let me fix this? Like, change sorted map to hash map?
If I can fix that, We can easily solve this issue ...

**Comment by okhat** [comment]
(Sorry to interject!) Since the difference is 3e-17, isn't the problem rather about the unrounded precision of the eval script, much more than anything else? Differences due to order seem expected (if only, in part, with hindsight!) and they're in fact smaller than I'd have guessed personally.

**Comment by lintool** [comment]
> (Sorry to interject!) Since the difference is 3e-17, isn't the problem rather about the unrounded precision of the eval script, much more than anything else? Differences due to order seem expected (if only, in part, with hindsight!) and they're in fact smaller than I'd have guessed personally.

Agreed, but for replicability purposes we'd ideally want results to be _exactly_ the same, and if they're not, we should at least understand why.
