### ISSUE TITLE
Searching with TFIDF score for multi-field documents

### ISSUE THREAD

**Issue by Joohee-Park** [castorini/pyserini#268]
Hello :)
First of all, thank you castroni team for developing anserini and pyserini.

I am wondering if there is a way to search documents with TF-IDF scores, not BM25.
Actually, what I exactly want to do is

1. Calculate BM25 score for field A
2. Calculate TF-IDF score for field B
3. Retrieve the documents according to the score `[score of field A] + \lambda * [score of field B]`
(No overlapping vocabulary between field A and B)

Since `\lambda` can be implemented through query term boosting because field A and B have independent vocab sets,
all I need is different scoring functions for different fields.
It would be great if I can do this with pyserini.

Thank you!

**Comment by lintool** [comment]
Glad you find the package helpful.

The feature you mentioned does not currently exist, but should be possible to implement - see this as a starting point:
https://github.com/castorini/pyserini/blob/master/pyserini/search/_searcher.py#L169

**Comment by lintool** [comment]
Seeing no further follow up, closing issue.
