### ISSUE TITLE
Class not found b'org/apache/lucene/search/Query'

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/pyserini#276]
Dear All
I have installed pyserini using Anaconda 4.9.2 to avoid any problems with installing pyjnius 
I use Windows 10 with jdk 11 , python 3.9 , Anaconda 4.9.2 inside ubuntu in it and 
Ubuntu App with python 3.8 + jdk 10.2 insode anaconda

I got this message which I think it is about finding Anserini library 

I renamed anserini-master to anserini
I put both folders inside site-packages ( pyserini & Anserini) 
I generated mvn target files without testing 
I could not find query folder from pyserini 

`mvn clean package appassembler:assemble -DskipTests -Dmaven.javadoc.skip=true
`

![img](https://user-images.githubusercontent.com/47518534/102160574-9796ab00-3e7d-11eb-998a-ecc2ed81ff1f.png)

Thanks anyway 
Regards

**Comment by lintool** [comment]
Did you do this?

> After you've successfully built Anserini, copy the fatjar, which will be target/anserini-X.Y.Z-SNAPSHOT-fatjar.jar into pyserini/resources/jars/.

Try the pip install option also...?

**Comment by ABDULAZIZALQATAN** [comment]
All done Already of course sir
is it because I am using Ubuntu App in Windows with long file path like this ? 
"C:\Users\kkb19103\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\kkb19103\anaconda3\lib\python3.8\site-packages" >>> because this is the default path of ubuntu inside windows >>> if not how can I refer to another path besides python site-packacges

**Comment by lintool** [comment]
Yea, I think you need JDK 11...

**Comment by ABDULAZIZALQATAN** [comment]
In order to save time >>> All what I need now from pyserini is a simple dataframe text files
For AQUAINT (Robust 05) [ default Anserini index ] 
For each document > two columns ( docID - doc Length)
and if you are generous add one more file 
For each term : ( term - term/frequency - document frequency )
and I will be grateful to anybody who can do this simply (with pyserini) and send the text files here

**Comment by lintool** [comment]
This can be done with Anserini: https://github.com/castorini/anserini/tree/master/src/main/java/io/anserini/util

**Comment by ABDULAZIZALQATAN** [comment]
Thanks >>> I will check it
