### ISSUE TITLE
Add in sparse + dense hybrid

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#295]
Dense TCT-ColBERT + doc2query-T5!

**Comment by lintool** [comment]
This is the prebuilt index you want for MS MARCO passage: https://github.com/castorini/pyserini/blob/master/pyserini/prebuilt_index_info.py#L40

**Comment by MXueguang** [comment]
so basically we want a class say `HybridSearcher` which takes a dense searcher and a sparse searcher and does the search under the hybrid rule right?

**Comment by lintool** [comment]
Yea, something like that... I'll leave the design in your capable hands... :)

Draft a PR and let's discuss...

**Comment by MXueguang** [comment]
sg

**Comment by lintool** [comment]
Closed by #299
