### ISSUE TITLE
Hybrid search: parameter design

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#302]
Pulled out comment from #299 

I was thinking, for hybrid search, an implementation with multiple subcommands, e.g.

```
python -m pyserini.hsearch --topics msmarco_passage_dev_subset 
 dense --index ... [all the usual dense options...]
 sparse --index ... [all the usual sparse options...]
 fusion [fusion options, like fusion weights, etc.]
```

See: https://stackoverflow.com/questions/10448200/how-to-parse-multiple-nested-sub-commands-using-python-argparse

This way, we don't need to re-implement options, just "dispatch" the the dense and sparse searchers.

We could design so that the dense/spare searchers take `--index` etc. options in a constructor. Alternatively, if this were Java, this would be a factory/builder class, but I don't know if this is idiomatic Python.

**Comment by MXueguang** [comment]
looks good, will do that in the next iteration (after integrating query encoder). 
I feel its good to do subcommands for hybrid search like that.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/330
