### ISSUE TITLE
Dense search replication, starting from hgf model

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#303]
Here's I think our end target: start with hgf model from model hub - assume that's fix.

1. Be able to encode corpus and queries - scripts for doing so should be in https://github.com/castorini/pyserini/tree/master/scripts
2. Scripts for building hnsw index, also in `scripts/`
3. (1) and (2) are what we store as "pre-built".

This will allow replication and bring every part of the pipeline in sync - other than training the encoder model.

@MXueguang @justram @jacklin64 thoughts?

**Comment by MXueguang** [comment]
sgtm.

btw, do we encode the corpus&queires into tfrecord format as we did before? Is pickle a better choice here?

**Comment by lintool** [comment]
Your choice - we can re-design from scratch, if @justram @jacklin64 agree -

The "interface" is at the encoder model, on hgf. Training it will be handled separately. But once it's fixed - encoding docs and queries, search, indexing, etc. should be done in pyserini.

**Comment by justram** [comment]
SGTM

**Comment by lintool** [comment]
@MXueguang As a sanity check, try taking the model and encoding a few queries and documents using TF. The output should match the original TF records @justram @jacklin64 passed to you, right? If they match, we can rule out "wrong model" - the difference are likely due to TF/PT implementations?

**Comment by jacklin64** [comment]
I think I can help check the output between TPU, GPU and CPU. I just forgot to mention that, previously, I found the output from TPU is slightly different from the one from GPU (or CPU). And now our TF records is from TPU, so maybe this is one of the difference.

**Comment by lintool** [comment]
Ah, TPU vs. GPU, yet another difference... How's this: @jacklin64 -

1. same a few queries and docs
2. encode on TPU and GPU using TF, check against the TF records.

This will at least allow us to isolate TPU vs. GPU differences.

**Comment by jacklin64** [comment]
Agree !

**Comment by lintool** [comment]
We seem to have sorted through the differences!
https://github.com/castorini/pyserini/issues/293#issuecomment-756952035

**Comment by MXueguang** [comment]
yeah. I think we can use current pytorch ckpt for hgf?
It should be 'fix' as long as we dont have another option of tensorflow ckpt

And I will create the embeddings & index next

**Comment by lintool** [comment]
Okay, so the final remaining issue is which version we use for the official pre-built index and pre-encoded queries. I think it should be PT on GPU?

**Comment by MXueguang** [comment]
yes!

**Comment by MXueguang** [comment]
created `msmarco-passage-tct_colbert-bf` index, which is encoded by PT ckpt on GPU,

dense retrieved by queries encoded on CPU on the fly
```
#####################
MRR @10: 0.33497794151089133
QueriesRanked: 6980
#####################
```

**Comment by MXueguang** [comment]
should we create `encoded_queries` on GPU or CPU?

**Comment by lintool** [comment]
My vote would be CPU. I think that's the most common usage scenario?

So, at the end of the day, we would have

(1) bf index, pre-encoded queries (CPU)
(2) bf index, one-the-fly encoded queries (CPU)
(3) bf index, one-the-fly encoded queries (GPU)
(4) hnsw index, pre-encoded queries (CPU)
(5) hnsw index, one-the-fly encoded queries (CPU)
(6) hnsw index, one-the-fly encoded queries (GPU)

(1) should be identical to (2) and (4) to (5) - and that's would we would have in our replication docs?

**Comment by MXueguang** [comment]
yeah, I am adding the support for one-the-fly encoded queries (GPU).
hnsw index will be created after around 10 hours

**Comment by MXueguang** [comment]
replicated result on my machine: ubuntu20.04, i7-8700k, 12 cores, rtx2080
```
hnsw pre 6980/6980 [02:50<00:00, 41.01it/s]
#####################
MRR @10: 0.3344676399690711
QueriesRanked: 6980
#####################

hnsw cpu 6980/6980 [12:34<00:00,  9.26it/s]
#####################
MRR @10: 0.3344676399690711
QueriesRanked: 6980
#####################

hnsw gpu  6980/6980 [04:07<00:00, 28.15it/s]
#####################
MRR @10: 0.3345032860326541
QueriesRanked: 6980
#####################

bf pre batch 36 thread 12 194/194 [06:11<00:00,  1.92s/it]
#####################
MRR @10: 0.3349694137444839
QueriesRanked: 6980
#####################

bf cpu batch 36 thread 12 194/194 [10:25<00:00,  3.22s/it]
#####################
MRR @10: 0.3349694137444839
QueriesRanked: 6980
#####################

bf gpu batch 36 thread 12   194/194 [07:24<00:00,  2.29s/it]
#####################
MRR @10: 0.3349479237731372
QueriesRanked: 6980
#####################

```

**Comment by MXueguang** [comment]
yeah, i think so!
