### ISSUE TITLE
pyserini.search multi-threaded performance notes

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#317]
Performance notes for multi-threaded `pyserini.search`:

```
python -m pyserini.search --topics msmarco_doc_dev --index msmarco-doc --output run.msmarco-doc.doc.txt --bm25 --hits 1000

 --threads 4 --batch-size 4     5193/5193 [05:16<00:00, 16.39it/s]
 --threads 4 --batch-size 8     5193/5193 [04:27<00:00, 19.39it/s]
 --threads 4 --batch-size 16    5193/5193 [04:14<00:00, 20.40it/s]
 --threads 4 --batch-size 32    5193/5193 [04:05<00:00, 21.12it/s]
 --threads 4 --batch-size 64    5193/5193 [03:48<00:00, 22.74it/s]

 --threads 8 --batch-size 8     5193/5193 [03:19<00:00, 26.03it/s]
 --threads 8 --batch-size 16    5193/5193 [02:55<00:00, 29.66it/s]
 --threads 8 --batch-size 32    5193/5193 [02:44<00:00, 31.57it/s]
 --threads 8 --batch-size 48    5193/5193 [02:34<00:00, 33.56it/s]
 --threads 8 --batch-size 64    5193/5193 [02:36<00:00, 33.20it/s]

 --threads 16 --batch-size 16   5193/5193 [02:23<00:00, 36.13it/s]
 --threads 16 --batch-size 32   5193/5193 [02:10<00:00, 39.72it/s]
 --threads 16 --batch-size 64   5193/5193 [02:03<00:00, 42.11it/s]
 --threads 16 --batch-size 96   5193/5193 [02:00<00:00, 42.93it/s]
```

This is on my iMac Pro (2017): 2.3 GHz Intel Xeon W (18 cores).

The way to understand these parameter settings is: run each batch containing X queries using Y threads. X should be larger than Y, otherwise threads will be idle. X should be a small-ish multiple of Y (~4 works well); beyond that, you get diminishing returns in terms of performance.

@mrkarezina Do you agree with this analysis? Do you have any performance numbers to share also?

**Comment by mrkarezina** [comment]
I didn't try many combinations and don't have the results saved from testing. I was mainly testing `--threads 4` and the it/s would even start to drop for larger batch sizes iirc.

On my MacBook Air (8GB RAM) I would run into a `java.lang.OutOfMemoryError: Java heap space` for larger batch sizes, e.g: `--threads 4 --batch-size 100`
