### ISSUE TITLE
get_document_vector vs get_postings_list

### ISSUE THREAD

**Issue by Oulaolay** [castorini/pyserini#32]
hello! Thank u for your work !
I have some issues and I am not sure whether It's a bug in the API or It's due to my misunderstanding of some semantics related to the API..
When I run these two programs, and analyze the frequency of the term "standard" in some documents like this:
- Program 1:
doc_vector = index_utils.get_document_vector(XXX)
Output  : {"...",'standard': 3, "..."}
- Program 2:
postings_list = index_utils.get_postings_list('standard')
Output: docid=XXX, tf=1, pos=[26]

In fact, for the same document id, i get for the first program 3 terms, and the second 1 term frequency. The term "standard" was used here just for illustration, but I encounter the same problem for other terms.

I will be very grateful to get a feedback about this issue.

Best regards,

**Comment by lintool** [comment]
Hi @Oulaolay - those two should indeed match. Can you provide a concrete example where they don't that I can reproduce? For example, on the MS MARCO dataset?

**Comment by Oulaolay** [comment]
Hi @lintool ! Thanks you for your quickly reply. 
I have the same issue with MS MARCO & robust04 : 
For example, on MS MARCO :
searcher = pysearch.SimpleSearcher('index-msmarco-passage-20191117-0ed488')
hits = searcher.search('black')
for i in range(0, 10):
    print('{} {} {}'.format(i + 1, hits[i].docid, hits[i].score))
Output : 1 4910711 4.250199794769287
              2 7795365 4.221499919891357
              ... 
So, i use the doc id  "7795365" : 
doc_vector = index_utils.get_document_vector("7795365")
Output : jnius.JavaException: JVM exception occurred: Document vector not stored!

Second example, on Robust04 :
hits = searcher.search('black')
for i in range(0, 10):
    print('{} {} {}'.format(i + 1, hits[i].docid, hits[i].score))
Output : 1 LA102989-0166 3.0659000873565674
              2 LA052189-0089 3.0517001152038574
doc_vector = index_utils.get_document_vector("LA052189-0089")
Output : Output : {"...",'black': 64, "..."} 
postings_list = index_utils.get_postings_list('black')
Output : #The index key does not match on this word

I have the impression that they are not the same indexes. In fact, postings_list returns the doc ids like this: {2993,3010, ...} It is different from "LA052189-0089".

Thanks!

**Comment by lintool** [comment]
hi @Oulaolay I understand the issue now.

In the MS MARCO case, the index we provide doesn't store the doc vector (otherwise, too large to share easily).

In the Robust04 case, the confusion is between internal and external docids - I've summarized in #33 and created an issue for myself. We need to expose the proper internal methods to make the conversion easier.

Let me know if you have any additional questions!

**Comment by lintool** [comment]
Closing issue. Please reopen if there's anything further.

**Comment by Oulaolay** [comment]
Hi @lintool ! It's perfect !  The #33 works fine! 
Thanks you! 

You can close this issue.
