### ISSUE TITLE
Fold qrels into pyserini directly

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#320]
Follow up to #310 - there, we folded the eval scripts directly into pyserini. Now let's do the same with the qrels.

In actuality, the qrels are already in the anserini jar, since this entire directory is included in the fatjar:
https://github.com/castorini/anserini/tree/master/src/main/resources/topics-and-qrels

Trick is how to get the qrels out...

This is, in fact, how we can access the topics in anserini:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/topicreader/Topics.java#L22
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/topicreader/TopicReader.java#L143

And pyserini just wraps the Java methods above.

---

With that background, I propose to apply the same treatment to qrels.

1. Add a method in Anserini (on the Java end) to read qrels from `resources/topics-and-qrels/` into a String. We can use the same "ids" as the topics. Build around here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/util/Qrels.java
2. On the Python end, we call the Java method, which reads the qrels as a string. Then we write back the string into `~/.cache/pyserini`.
3. Our eval scripts can then reference `~/.cache/pyserini`.

---

And at the end of the day, we'll be able to do this directly:

```
$ python -m pyserini.search --topics robust04 --index robust04 --output run.robust04.txt --bm25
$ python -m pyserini.eval.trec_eval --qrels robust04 -m map -m P.30 run.robust04.txt
```

(With no need to download any intermediate data... everything is self contained!)

@MXueguang thoughts? Do you like it? Any better way?

**Comment by MXueguang** [comment]
I have two concerns:

1. if we are hiding the qrels and topics too much. At least for me, when I do experiments, I usually look at the qrels and topic files directly, via bash. I actually prefer they are placed in my work directory. I even hack the topics sometimes.
2. if we are adding unnecessary coupling to anserini. Comparing to auto download in python directly, it seems to make things more complicated. 

Why don't we handle the qrels and topics the same as the way we handle index?

**Comment by lintool** [comment]
Good points. Responses:

re: (1) - this is primarily convenience for PyPI installation, for people who are _using_ pyserini, not hacking on it. If you're hacking on pyserini, you probably have a dev clone, in which case you have the topics/qrels in a convenient place already.

re: (2) - the fatjar is already part of the PyPI distribution and we already have this coupling for topics/queries... so IMO it doesn't make it any worse...

A few more advantages of this approach:

(1) This tight coupling is more future proof - the way we do eval script downloading now depends on a potentially unstable URL. For example, if the eval script is renamed (like recently). Unless we preserved old versions of scripts at fixed URLs, older PyPI versions might break. We do have people using us as a package already: https://github.com/castorini/pyserini/network/dependents?package_id=UGFja2FnZS02ODE5MDkxNjU%3D

(1a) Note that downloading URLs is not really testable, because you can still pass tests, publish package, and have the URLs change/break.

(2) Like topics right now, qrels become JUnit testable - at least for sanity checking.

(3) We can call the functionality from Java, e.g., `java -cp foo extractQrels ...`. I like features that are mirror both in Java and Python.

**Comment by MXueguang** [comment]
I see. make sense!
will make qrels similiar to topics

**Comment by lintool** [comment]
Great! Draft PR on the Anserini side and we'll flesh it out together.

**Comment by MXueguang** [comment]
unlike topics, all the qrels are with the same format?

**Comment by lintool** [comment]
Correct, either space sep or tab sep, please allow both variants.

**Comment by MXueguang** [comment]
https://github.com/castorini/anserini/blob/master/src/main/resources/topics-and-qrels/prels.mq.1-10000.txt

this is a bit different, but should be supported too right?

**Comment by lintool** [comment]
Nah, that's ignore this now. `prels` aren't really used much anymore... they work a bit different from `qrels`...

**Comment by MXueguang** [comment]
The java part, we only read qrels file as string without parse it?
like this https://github.com/castorini/anserini/pull/1457

**Comment by lintool** [comment]
Nahh, I think we should keep the existing API, so that we have parallel functionality in Java and Python. Maps in Java translate automatically into Dicts in Python.

Just add an additional method that reads the entire qrels file as a string - call this from Python to write out the qrels file into `.cache/`.

This is what I had originally in mind, but open to suggested alternatives?

**Comment by MXueguang** [comment]
Ah, I see. make sense!

**Comment by MXueguang** [comment]
where should i place the `get_qrels` in pyserini?
together with `get_topics`? i.e. in `pyserini.search._base`

**Comment by lintool** [comment]
Together with `get_topics` would make sense.

**Comment by MXueguang** [comment]
I am a bit unsure about the relationships:
`topics.covid-round3-udel.xml`
`topics.covid-round3.xml`
`qrels.covid-round3-cumulative.txt`
`qrels.covid-round3.txt`

**Comment by lintool** [comment]
Unrelated.

These are different ways of generating queries:
```
topics.covid-round3-udel.xml
topics.covid-round3.xml
```

Different qrels:

```
qrels.covid-round3-cumulative.txt
qrels.covid-round3.txt
```
"cumulative" means rounds 1, 2, 3 put together.

You can mix and match. All combinations are meaningful (answering different research questions).

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/333
