### ISSUE TITLE
Hybrid retrieval currently can't specify pre-encoded queries vs. on-the-fly encoding

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#329]
Currently, hybrid retrieval uses pre-encoded queries, and there's no way to change, right?

We need to add in this option sooner or later, but perhaps this should be done along with #302?

**Comment by MXueguang** [comment]
we should be able to it rn. I'll update the document.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/330
