### ISSUE TITLE
create anserini index for dpr wikipedia 

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#331]
In DPR, they split wikipedia into 100word passages as corpus, we want a anserini index using the identical corpus.

download the corpus from the dpr repo here: https://github.com/facebookresearch/DPR/blob/f403c3b3e179e53c0fe68a0718d5dc25371fe5df/data/download_data.py#L26
follow the anserini's index custom collection document, https://github.com/castorini/anserini/blob/master/docs/custom-collections.md to index the above wikipedia collection. i.e. convert to jsonl format, and then index

**Comment by KaiSun314** [comment]
On it, ETA <1 hour

**Comment by MXueguang** [comment]
close since @KaiSun314 created the index
