### ISSUE TITLE
Dashes vs. underscores in prebuilt names

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#334]
This looks odd:

```
$ python -m pyserini.search \
     --topics msmarco_passage_dev_subset \
     --index msmarco-passage \
     --output run.msmarco-passage.txt --bm25 --msmarco
```

In that we have `msmarco_passage_dev_subset` and `msmarco-passage`: dashes vs. underscores. We should:

(1) Standardize on one convention in documentation (i.e., all dashes or all underscores).
(2) In the code, allow both. (i.e., a simple regex substitution will do).

My vote for (1) is dashes because I think it looks better... any thoughts? @MXueguang @ronakice @rodrigonogueira4

**Comment by ronakice** [comment]
I prefer dashes too!

**Comment by rodrigonogueira4** [comment]
me too!
