### ISSUE TITLE
replicate the result for the MS MARCO Passage Retrieval Task

### ISSUE THREAD

**Issue by KaishuaiXu** [castorini/pyserini#343]
Hello,

I am trying to learn to use the pyserini tool. However, I encountered a problem as follows.
> % python -m pyserini.eval.trec_eval -m map -m P.30 robust04 run.robust04.txt
/Users/kaishuai/opt/anaconda3/bin/python: Error while finding module specification for 'pyserini.eval.trec_eval' (ModuleNotFoundError: No module named 'pyserini.eval')

It seems that the "eval" file is not installed when I install the package using "pip".

After I download the "eval" file in GitHub, there is another problem.

> % python -m pyserini.eval.trec_eval -m map -m P.30 robust04 run.robust04.txt
Traceback (most recent call last):
  File "/Users/kaishuai/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kaishuai/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kaishuai/opt/anaconda3/lib/python3.8/site-packages/pyserini/eval/trec_eval.py", line 5, in <module>
    from pyserini.search import get_qrels
ImportError: cannot import name 'get_qrels' from 'pyserini.search' (/Users/kaishuai/opt/anaconda3/lib/python3.8/site-packages/pyserini/search/__init__.py)

So, does the code in Replication Guides still work?

**Comment by lintool** [comment]
Ah, good point, we should clarify. The guides require a development installation: https://github.com/castorini/pyserini/#development-installation

**Comment by KaishuaiXu** [comment]
> Ah, good point, we should clarify. The guides require a development installation: https://github.com/castorini/pyserini/#development-installation

Thanks a lot for your reply! I have built my own searcher following the instruction. It works! :)

**Comment by lintool** [comment]
Clarified in #344
