### ISSUE TITLE
DPR documentation notes

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#347]
Hey @MXueguang comments about documentation, please work on as part of the next iteration.

1. Can you reference the comparable numbers in the paper - e.g., this is comparable to the single condition for NQ in Table 2; FB reports X but report Y, etc.

2. Retrieval with brute force index should probably come first?

3. We want to add other collections... so `--index wikipedia-dpr-bf` should probably be `--index wikipedia-dpr-nq-bf` instead... since the encoders are collection specific, right? (this requires renaming the pre-built index, changing dropbox links, etc.)

**Comment by lintool** [comment]
One more - add links to both TCT-ColBERT and DPR on main `README.md`, under replication guide.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/354
