### ISSUE TITLE
Use case for dump_document_vectors in IndexReaderUtils?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#35]
Hi @zeynepakkalyoncu - do we have an actual use case for `dump_document_vectors` in `IndexReaderUtils`? I'm trying to write a use case for it, and I can't seem to even get it to work? Throws a mysterious `jnius.JavaException: JVM exception occurred` error.

If you're using this feature somewhere (in a notebook), we should make sure it works and write a test case... otherwise I would suggest removing it until a real use case comes up.

**Comment by zeynepakkalyoncu** [comment]
I think we wrote that as a temporary fix at some point. We aren't currently using it, it can be removed.

**Comment by lintool** [comment]
Okay, I'll work on this!
