### ISSUE TITLE
Consistent naming of prebuilt indexes

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#350]
Our Lucene prebuilt indexes have ids like `msmarco-passage-slim` and map to physical directories like `index-msmarco-passage-slim-20201202-ab6e28`. This is good.

Naming of dense indexes is a bit inconsistent, e.g., we have `msmarco-passage-tct_colbert-hnsw` but that maps to `dindex-hnsw-msmarco-passage-20210112-be7119`. I like separating dense indexes from Lucene indexes with the `index` vs. `dindex` prefix.

But currently, the "schema" of the name is inconsistent.

I propose making it consistent, using a scheme like `{corpus}-{encoder}-{type}` that would map to `dindex-{corpus}-{encoder}-{type}-{date}-{checksum}`.

So `msmarco-passage-tct_colbert-hnsw` -> `dindex-msmarco-passage-tct_colbert-hnsw-20210112-be7119`.

In terms of the "ordering" of the schema, the question I ask myself is - "if I do an `ls` on an index directory, how do I want to see the indexes grouped together?"

I'd say, the thing I care about the most is separating dense from bow indexes. The I would want all the indexes of the same corpus to be grouped together, then encoder. Finally, the least important distinction is `hnsw` vs. `bf`. Open to discussion on this point though...

**Comment by MXueguang** [comment]
close by https://github.com/castorini/pyserini/pull/359
