### ISSUE TITLE
Update documentation for searching to incorporate dense and hybrid

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#353]
Hey @MXueguang - your lobster roll example would work well in our doc page:
https://github.com/castorini/pyserini/#how-do-i-search

We should add to the above section dense and hybrid retrieval as well. Please update the docs with your PR? Take a first stab at rewriting docs - I can follow up with revisions after.

**Comment by MXueguang** [comment]
close by https://github.com/castorini/pyserini/pull/354
