### ISSUE TITLE
SimpleSearcher.list_prebuilt_indexes() lists dense indexes as well

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#360]
Should only list bow sparse indexes

**Comment by MXueguang** [comment]
https://github.com/castorini/pyserini/blob/6170fc12d3eee8b15cdf4adf06f33f5270e34460/pyserini/prebuilt_index_info.py#L1
maybe store their info in two dictionary is better?
i.e. INDEX, DINDEX
or otherwise, we add a field in INDEX, e.g.. `is_dense: False`

**Comment by lintool** [comment]
> maybe store their info in two dictionary is better?
> i.e. INDEX, DINDEX

Agreed.

**Comment by MXueguang** [comment]
close by https://github.com/castorini/pyserini/pull/363
