### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by kruthikakr** [castorini/pyserini#383]
from pyserini.search import pysearch
  File "/home/kruthika/PycharmProjects/SentimentalanalysisFin/venv/lib/python3.6/site-packages/pyserini/search/pysearch.py", line 25, in <module>
    from ..pyclass import JSearcher, JResult, JDocument, JString, JArrayList, JTopics, JTopicReader
  File "/home/kruthika/PycharmProjects/SentimentalanalysisFin/venv/lib/python3.6/site-packages/pyserini/pyclass.py", line 51, in <module>
    JDefaultEnglishAnalyzer = autoclass('io.anserini.analysis.DefaultEnglishAnalyzer')
  File "/home/kruthika/PycharmProjects/SentimentalanalysisFin/venv/lib/python3.6/site-packages/jnius/reflect.py", line 229, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: io/anserini/analysis/DefaultEnglishAnalyzer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 java.lang.UnsupportedClassVersionError

**Comment by kruthikakr** [comment]
Java -version 
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

**Comment by lintool** [comment]
We should clarify, but Pyserini requires Java 11.

**Comment by lintool** [comment]
https://github.com/castorini/pyserini/pull/384

**Comment by goldenretriever98** [comment]
Hey, I got this error too, but I have installed openjdk 11 on my mac m1, and still getting the same error. 
Could you please tell how to diagnose this issue ?

**Comment by Xnhyacinth** [comment]
> We should clarify, but Pyserini requires Java 11.

when I use java 11, it meets the error too:
jnius.JavaException: JVM exception occurred: io/anserini/eval/Qrels has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 55.0 java.lang.UnsupportedClassVersionError.

Could you please tell how to diagnose this issue ?

Thanks a lot. @lintool

**Comment by lintool** [comment]
In the main README.md, it clearly says the following:

> ❗ Anserini was upgraded from JDK 11 to JDK 21 at commit [272565](https://github.com/castorini/anserini/commit/39cecf6c257bae85f4e9f6ab02e0be101338c3cc) (2024/04/03), which corresponds to the release of v0.35.0. Correspondingly, Pyserini was upgraded to JDK 21 at commit [b2f677](https://github.com/castorini/pyserini/commit/b2f677da46e1910c0fd95e5ff06070bc71075401) (2024/04/04).
