### ISSUE TITLE
Pyjnius Error "PermissionError: [WinError 5] Access is denied"

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/pyserini#386]
Dear All
I am trying to install pyserini and use it because it allows to specify term weights on Anserini indexes   [Here](https://github.com/castorini/anserini/issues/1480)

I installed pyserini + all related packages including pyjnius 
![image](https://user-images.githubusercontent.com/47518534/108565740-1a643800-72fd-11eb-883f-876d26dfcd7d.png)

The problem is that java classes are not recognized in Pyjnius and I cannot upgrade pyjnius to the latest version  1.3 

Cannot Upgrade pyjnius 
![image](https://user-images.githubusercontent.com/47518534/108566096-be4de380-72fd-11eb-9ca1-6c7719a26039.png)

Cannot Use Pyjnius 
![image](https://user-images.githubusercontent.com/47518534/108571849-f4dd2b80-7308-11eb-9fdd-c3f5ba8bce34.png)

Environment Variables are Set correctly 
![image](https://user-images.githubusercontent.com/47518534/108572090-6321ee00-7309-11eb-9714-e8c4f968906e.png)

Run cmd as Administrator 

Everything is almost done >>> pyjnius is not working which makes pyserini not working too

**Comment by lintool** [comment]
Could this be an issue with Windows? Do you have access to a Linux or macOS machine you can try?

**Comment by ABDULAZIZALQATAN** [comment]
Thank sir >> You are absolutely right 👍  >> I used Ubuntu App in Windows >>> 
![image](https://user-images.githubusercontent.com/47518534/108586338-a39f5d00-7345-11eb-8f6c-96d0218226a3.png)

It is better for me to use windows or many things would change >>> I will try conda or I will figure a solution with Linux 

Regards

**Comment by ABDULAZIZALQATAN** [comment]
I think it is solved now in Windows 
1- Use Ubuntu App for Windows 
2- Install Python3 inside Ubuntu App 
3- Install Pip3 inside Ubuntu App and all of your Ubuntu Things 
4- Access your Ubuntu Interpreter from Windows Using WSL Interpreter 
5- Enjoy your Ubuntu code from Windows 

![image](https://user-images.githubusercontent.com/47518534/108586795-9041c100-7348-11eb-957f-d323aae15ca9.png)

**Comment by lintool** [comment]
Great, thanks for the info! This will be helpful for other Windows users as well.
