### ISSUE TITLE
DPR documentation: --batch vs. --batch-size

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#388]
hey @MXueguang, DPR doc for `dsearch` says `--batch`: https://github.com/castorini/pyserini/blob/master/docs/experiments-dpr.md#natural-questions-nq

But actual option appears to be `--batch-size`:
https://github.com/castorini/pyserini/blob/master/pyserini/dsearch/__main__.py#L79

But appears to work... so this is flexibility in Python's arg parsing?

**Comment by MXueguang** [comment]
yeah, it is a 'feature' of argparse. when a prefix is unique, it will get identified.
we can change the doc to `--batch-size` to make everything identical
