### ISSUE TITLE
Lucene Analyzer is not found 

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/pyserini#398]
Dear All 
I would like to run simple search method over local Lucene Index and get the hits 
Currently , the problem I have is that I cannot find Lucene Analyzer 
![image](https://user-images.githubusercontent.com/47518534/109404123-15396580-795b-11eb-8d3f-2a3a06b6ab87.png)

I tried to set classpath to 
Lucene Fatjar File but The Analyzer could not be found

**Comment by MXueguang** [comment]
Hi, have you tried to copy the fatjar file from `anserini/target` to `pyserini/resources/jars/` ?

**Comment by ABDULAZIZALQATAN** [comment]
Sure sir and I moved my anserini with all indexes to Site-packages folder of python to be with pyserini

![image](https://user-images.githubusercontent.com/47518534/109406394-87687500-7970-11eb-8474-2a131a73e5c2.png)

![image](https://user-images.githubusercontent.com/47518534/109406398-93543700-7970-11eb-8dc8-c05460f2e4ef.png)

**Comment by MXueguang** [comment]
thank you for letting us know!
we will update the document too.
