### ISSUE TITLE
Is PL2 Retrieval Model Supported By Pyserini?

### ISSUE THREAD

**Issue by ABDULAZIZALQATAN** [castorini/pyserini#412]
Dear All 
As far as I can See BM25 and Language Model ( QLD ) are supprted in pyserini but how about PL2 how can I use it ?
What is the default parameters of pyserini searcher ?

Regards

**Comment by MXueguang** [comment]
@ABDULAZIZALQATAN 
The default BM25 parameters is (k1=0.9, b=0.4).
PL2 is not supported in pyserini.

**Comment by ABDULAZIZALQATAN** [comment]
Thanks
