### ISSUE TITLE
Model cards on hgf

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#424]
We need model cards, e.g., https://huggingface.co/castorini/tct_colbert-msmarco

Should point back to our repo.

**Comment by MXueguang** [comment]
- ANCE: pointed to their original repo + point to our experiments https://huggingface.co/castorini/ance-dpr-context-multi
- TCT_ColBERT: pointed to our experiments https://huggingface.co/castorini/tct_colbert-msmarco
