### ISSUE TITLE
Class names: DPRQueryEncoder, TCTColBERTQueryEncoder, AnceQueryEncoder, SBERTQueryEncoder

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#429]
Partially stems from #428:

We have: `DPRQueryEncoder, TCTColBERTQueryEncoder, AnceQueryEncoder, SBERTQueryEncoder`

The capitalization is inconsistent - for example if we have `AnceQueryEncoder`, then it should be `DprQueryEncoder`. As ugly as it looks, even hgf uses `Bert` not `BERT`...

So I think consistency wrt hgf makes sense?

Thoughts @MXueguang ?

**Comment by MXueguang** [comment]
yeah
- DPR -> Dpr, SBERT -> SBert, TCTColBERT -> TctColBert ?

**Comment by lintool** [comment]
Agreed.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/450
