### ISSUE TITLE
Add functionality to search without preprocessing

### ISSUE THREAD

**Issue by Chriskamphuis** [castorini/pyserini#43]
We would like to be able to search an index without the query being processed by the stemmer. The specific use-case would be for the background linking task of TREC. We want to use the document vectors (that contain stemmed terms) to construct a new query.

**Comment by lintool** [comment]
I think the simplest approach to expose this is here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleSearcher.java#L110

The `SimpleSearcher` constructor hard codes an analyzer. Let's add in a command-line option to take a custom analyzer.

**Comment by Chriskamphuis** [comment]
Depends on https://github.com/castorini/anserini/issues/1013 
After that is implemented, Pyserini needs to support these functions.
