### ISSUE TITLE
Pyserini versioning: decoupling with Anserini?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#430]
Currently, we use the versioning scheme of _X.Y.Z.W_, where _X.Y.Z_ is just the Anserini version. This made sense when Pyserini was just a lightweight Python wrapper around Anserini. But now, with the addition of dense retrieval, Pyserini has non-trivial capabilities not present in Anserini, so the versioning scheme may not make sense any more...

Should we decouple the versioning between Pyserini and Anserini? We're at Pyserini v0.11.0.0 now, built on Anserini v0.11.0. Assuming we don't publish a new Anserini artifact, should our next version be Pyserini v0.12.0?

Alternatives include keeping our existing scheme (lockstep with Anserini, so Pyserini v0.11.0.1 next), or advance Pyserini deliberately to create some distance, e.g., Pyserini v0.20.0.

@MXueguang thoughts?

**Comment by MXueguang** [comment]
Anserini is more mature than pyserini i feel. Pyserini is likely to have more frequent iterations.
I think we can decoupling and create some distance

**Comment by lintool** [comment]
So Pyserini v0.20.0 for next iteration?

**Comment by MXueguang** [comment]
emm, is the jump from v0.11 to v0.20 too big?
maybe "lockstep with Anserini, so Pyserini v0.11.0.1 next" is better?
but I am fine with either

**Comment by lintool** [comment]
Wait, but you said above you want to decouple versioning?

**Comment by MXueguang** [comment]
sorry I confused myself...
I prefer  v0.12.0 now.... 
v0.20.0 jump too big, and v0.11.0.1 still seems coupling

**Comment by lintool** [comment]
Agreed!

**Comment by lintool** [comment]
This is now complete, per #541
