### ISSUE TITLE
SimpleSearcher.search memory leak

### ISSUE THREAD

**Issue by dmitrijeuseew** [castorini/pyserini#431]
When calling search method of SimpleSearcher I noticed RAM usage increase with every new iteration. Could you tell me please how to decrease memory leak?

**Comment by MXueguang** [comment]
Hi @dmitrijeuseew, I didn't notice an obvious memory leak before. Could you share more info? e.g. your index size, how much RAM the search takes initially, how much RAM increase per iteration, code pieces etc.

**Comment by dmitrijeuseew** [comment]
@MXueguang My code
[pyserini_ranker.txt](https://github.com/castorini/pyserini/files/6141386/pyserini_ranker.txt)

**Comment by dmitrijeuseew** [comment]
I built an index of wikipedia pages (total size of about 13 Gb) using the command:
python3.8 -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator -threads 20 -input wikipedia -index wiki_index -storePositions -storeDocvectors -storeRaw

**Comment by MXueguang** [comment]
Your code seems to be a correct usage. Roughly how much RAM increase per iteration?

**Comment by dmitrijeuseew** [comment]
100 iterations - about 500 Mb increase

**Comment by dmitrijeuseew** [comment]
More than 1 Gb increase for 200 iterations

**Comment by MXueguang** [comment]
with `n_threads = 1, top_n = 5`?

**Comment by dmitrijeuseew** [comment]
I used top_n = 15

**Comment by MXueguang** [comment]
I'll have a run on similar indexs, and then get back

**Comment by dmitrijeuseew** [comment]
Memory increase stops on 2.5 Gb

**Comment by lintool** [comment]
It could be underlying Lucene behavior as it brings more and more of the index into cache?

**Comment by MXueguang** [comment]
yeah, I think that is the reason.
I am not familiar with the underlying Lucene logic but my guess is the maximum to load into RAM is bounded by java MaxHeapSize.
It's more like an upstream _feature_ and seems hard to configure in Pyserini.

**Comment by lintool** [comment]
@dmitrijeuseew also, how are you measuring memory usage? could there also be underlying OS-level caching? If so, that's not really an issue since the OS will cache-evict when needed...

**Comment by dmitrijeuseew** [comment]
I launch document search in Docker container and use command
docker stats
to measure RAM usage

**Comment by lintool** [comment]
I believe those measurements include OS-level caches inside the docker container.

**Comment by lintool** [comment]
Hearing no further updates, closing issue...
