### ISSUE TITLE
Integrate Margin-MSE trained DistilBERT dense retrieval model

### ISSUE THREAD

**Issue by sebastian-hofstaetter** [castorini/pyserini#432]
Hi,

I just published our Margin-MSE ensemble-trained, DistilBERT-based checkpoint for dense passage retrieval here: https://huggingface.co/sebastian-hofstaetter/distilbert-dot-margin_mse-T2-msmarco

Would be cool if we could integrate that model in pyserini! I created a minimal usage example here: https://github.com/sebastian-hofstaetter/neural-ranking-kd/blob/main/minimal_bert_dot_usage_example.ipynb

Best,
Sebastian

**Comment by MXueguang** [comment]
@lintool I think this issue can be close by https://github.com/castorini/pyserini/pull/433?
CC: @sebastian-hofstaetter

**Comment by lintool** [comment]
👍
