### ISSUE TITLE
Efficiently compute BM25 scores between a collection of queries and documents

### ISSUE THREAD

**Issue by ccsasuke** [castorini/pyserini#437]
Hi,

I have a number of `X` queries and a collection of `Y` documents, and I'd like to compute the BM25 score for each pair of them (resulting in a `X by Y` matrix). And I need to do this many times, each time with different queries and documents.

Is there any way to do this efficiently? The only function for computing BM25 score that I could find (https://github.com/castorini/pyserini/blob/48126de83ee54f8f77592d3d5b5386ad0a2ddf71/pyserini/index/_base.py#L440) calculates the score for a single pair, and cannot be parallelized. (It caused a deadlock when I use multiprocessing on top of it --- probably related to #15 )

Is there any way I can speed up the computation by somehow processing this in batch? 
For instance, can I do search within a specific subset of the documents by supplying the docids? If so, I can solve this by doing a batch search within a restricted index containing only those `Y` documents.

**Comment by lintool** [comment]
Unfortunately, adding this feature is a bit more involved... due to the jankiness of multi-processing, an efficient parallel implementation needs to be done on the Java side, and then with "batch" bindings on the Java end.

We won't have cycles to do this in the short term, but if you're interested in adding this implementation, I can guide you through it...

**Comment by ccsasuke** [comment]
Thank you for the prompt response.

I see that this `compute_query_document_score` was implemented in a way that adds "an additional filter clause that restricts consideration to only the docid in question".

Can this be extended to support a set of docids? If so, I guess instead of parallelizing the computation in a straightforward way, we can perform a search within this restricted index?

**Comment by lintool** [comment]
Yes, that's probably the way to implement it - on the Java Anserini end:

https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexReaderUtils.java#L638

Add a variant of the `computeQueryDocumentScore` method to take a list of docids. And then you'll have to add corresponding bindings on the Python Pyserini end.

This will probably scale to a certain level... up to the limits of Lucene queries (IIRC, there's a size upper bound in number of clauses)... but beyond that, you'll need to do multi-threading in Java, I think...

Send a PR?

**Comment by lintool** [comment]
That's the basic idea... you basically got a formulate a new boolean clause that's the disjunct (OR) of all the docids.

If you're going to do some coding, let this test case guide you? https://github.com/castorini/anserini/blob/master/src/test/java/io/anserini/index/IndexReaderUtilsTest.java#L510

**Comment by MXueguang** [comment]
@ccsasuke Implement docid list in Anserini should be the best option to improve efficiency.
But with current Pyserini, see if this vectorizer API can help you save some time of computing the scores.
https://github.com/castorini/pyserini/blob/dd7d18c4e99a57dc1923cd3c7d5ff0eee45bb9d8/pyserini/vectorizer/_base.py#L139
The BM25Vectorizer contains two methods:
-  `get_vectors(self, docid_list, norm=None)`, calculate the BM25 weights for documents
-  `get_query_vector(query)` gives the term frequency vector for query.
You can use `get_vectors` to get a sparse matrix M1 for your X documents, with shape(|X|, d).
and use `get_query_vector` to get a sparse matrix M2 for your Y queries, with shape(|Y|, d).
By dot product these two sparse matrices, you will get the BM25 score matrix in shape(|X|, |Y|). 
This process may save your time of calculating the score one by one.

**Comment by ccsasuke** [comment]
@MXueguang Thanks for the suggestion. This sounds very promising!

I'm using the pre-trained "wikipedia-dpr" index provided by Pyserini, but I ran into this exception:
```
JavaException: JVM exception occurred: Document vector not stored! io.anserini.index.NotStoredException
```

Is there a prebuilt BM25 index with DPR documents that stored the document vectors?

**Comment by lintool** [comment]
hey @MXueguang this should be easy enough for you to build for @ccsasuke ? We should probably supply this version anyway?

**Comment by MXueguang** [comment]
@ccsasuke 
https://www.dropbox.com/s/kgz1fc3dsqbfpjw/index-wikipedia-dpr-full-20210323-059b5d.tar.gz?dl=0
This is a wikipedia-dpr index with Docvectors stored.
(It is not registered in the current release, but we probably supply this in prebuilt index soon as @lintool 
 said. )

**Comment by ccsasuke** [comment]
@MXueguang  @lintool Thank you both for your help!

**Comment by ccsasuke** [comment]
@MXueguang I tried this approach, but it is actually slower than computing individual BM25 scores one by one.. 

I experimented with 128 queries and 256 documents: Calling `compute_query_document_score` 128*256 times took 3-4 seconds on my machine, while using this matrix product method took 18 seconds.
(It seems getting the vectors is much slower than getting the BM25 score directly, plus it's not batched at the back end -- a for loop is used to get document vectors one by one.)

**Comment by MXueguang** [comment]
> plus it's not batched at the back end 
emm, yeah, I was hoping the `get_document_vector` has same efficiency to `compute_query_document_score`.
but seems not :( and even worse.
maybe we have to add feature in Anserini end then...

**Comment by zmzhang2000** [comment]
> @ccsasuke https://www.dropbox.com/s/kgz1fc3dsqbfpjw/index-wikipedia-dpr-full-20210323-059b5d.tar.gz?dl=0 This is a wikipedia-dpr index with Docvectors stored. (It is not registered in the current release, but we probably supply this in prebuilt index soon as @lintool said. )

Hi @MXueguang, I also would like to use wikipedia-dpr index with Docvectors stored, but only to find the file in dropbox is deleted.

Would you please share the index again?

**Comment by lintool** [comment]
No one's looked at this in a while... closing.
(I think batch querying remains the solution here.)
