### ISSUE TITLE
Index my own data

### ISSUE THREAD

**Issue by claeyzre** [castorini/pyserini#439]
Even though this issue is a duplicate from [102](https://github.com/castorini/pyserini/issues/102) I was wondering if it was still possible to index my own data from pyserini.

[102](https://github.com/castorini/pyserini/issues/102)  was solved by exposing `JIndexCollection` in the `pyclass.py` file at the time. 
It has been removed ever since and is not accessible anymore.

The only way I found to index data is to call the main within pyserini/index with command line arguments but I might be missing something.

There is also a hidden exposure of `IndexCollection` in `JCounters` within pyserini/index/__base.py  but not accessible from the code. 

Is there still a programmatic way to index my data using pyserini ?

**Comment by lintool** [comment]
Does this not meet your needs? https://github.com/castorini/pyserini#how-do-i-search-my-own-documents

**Comment by claeyzre** [comment]
Sorry, by programmatic I meant that I could write code like this for example:
```
def fn(myargs:List[str]):
       # perform custom validation over my args , customize the number of threads for example
       IndexCollection(myargs)
       # continue on using the newly created index.
```
IMHO `IndexCollection` should not be hidden and accessible from the code. In your example it seems I can only access it by command line which is not ideal compared to the other JClasses.

**Comment by lintool** [comment]
Ah, I see... Pyserini doesn't current support that...

Can you describe your use case?

Pyserini is mostly used for IR research on static collections, so for the most part `IndexCollection` is enough...

**Comment by claeyzre** [comment]
I want to build an application that could automatically build  multiple index on a given dataset to do IR research with different settings. My goal is to use those index later to automatically run evaluation on it. I want to spare me and my users the pain to use a CLI in the middle to build the lucene indices.

The thing is Pyserini actually does support it, it's just not exposed through code but only with a CLI as in your example. I was wondering why is that. From the [PR 179](https://github.com/castorini/pyserini/pull/179) I saw that IndexCollection is exposed in pyclass.py ([commit](https://github.com/castorini/pyserini/pull/179/commits/e3493b3b17bd472bc296c0ecf55d1704b7582bf5#diff-e0838a1236eb44d97d5eb73ca3590e66d1999ee8df12e5efde05551176ac7904R68)) then only exposed in the main in the following commit ([here](https://github.com/castorini/pyserini/pull/179/commits/22d76620f0772b8ff7eb7223bb943c94a3e106c5)) and thushidden from the user and I was wondering why is that ? The feature is actually here but not enabled.

I would just need to call `from pyserini.index import JIndexCollection` or `IndexCollection` if it was exposed in the __base for example

**Comment by lintool** [comment]
tbh, I don't remember the design rationale... but nothing comes to mind as to why we hid the functionality you need...

Seems like this is a relatively small fix? Would you be willing to send a PR and we can discuss more concretely?

**Comment by lintool** [comment]
hi @claeyzre do we have a follow up here? We're happy to take a look at a PR from you...

**Comment by lintool** [comment]
Hearing no follow up, closing.
