### ISSUE TITLE
About use Vectorizer as search indexer

### ISSUE THREAD

**Issue by svjack** [castorini/pyserini#442]
As your example , it is suitable to use Vectorizer as feature generator of machine learning model.
And i test to use bm25 vector as sparse indexer, the conclusion can not beat use searcher directly.
I can understand this conclusion. because truly score in lucene consider text length and other text 
feature.
My problem is Dose it exist a method to use vector as indexer that can beat to solely equal with 
lucene search (not by calculate bm25 score), if can learn a model is also a solution.
only use bm25 vector as feature.
i also know that i can use sentence-embedding and other deep learning model based on BERT.
But i only want to have a sparse indexer based on bm25 vector.
Can you introduce me some projects ?

**Comment by svjack** [comment]
Except use SVD to produce a LSA like model.
Can some sense to use bm25 vector to learn to approximate some gold BERT embedding
in some supervised manner ?

**Comment by lintool** [comment]
LSI, unfortunately, doesn't work very well: https://dl.acm.org/doi/abs/10.1145/1964897.1964900

This is why researchers had largely abandoned this approach, with sparse BM25 vectors. We needed dense vectors and better encoders (e.g., BERT) for the idea to work.
