### ISSUE TITLE
Generalize tokenize_json_collection to non-English languages

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#454]
Let's take this: https://github.com/castorini/pyserini/blob/master/pyserini/tokenize_json_collection.py

And make sure it works for non-English languages - e.g., XLMR, mBERT, etc.

cc/ @keleog

**Comment by lintool** [comment]
@crystina-z can we close this issue now? seems to have been done?

**Comment by crystina-z** [comment]
yea agreed
