### ISSUE TITLE
Support for Dense capable indexing

### ISSUE THREAD

**Issue by spacemanidol** [castorini/pyserini#464]
Hello,
First off, great library! I am toying around with the CLEF HEALTH corpus and I have created a static index(I can upload it to your dropbox if that is desired) but am unable to get the dense or hybrid retriever working as it needs a separate index. Can you add docs on how to generate said index or point to the tools used to generate the index?

Daniel

**Comment by lintool** [comment]
@MXueguang can walk you through the steps... although the encoding will need to be zero-shot using existing encoders...

Re: CLEF HEALTH sparse retrieval - would you be willing to prepare a guide along the lines of the MS MARCO guide? https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-doc.md

If so, please send a PR? Without appropriate documentation, a pre-built index isn't particularly helpful...

**Comment by MXueguang** [comment]
Hi @spacemanidol,
For example, you can use this script to create the dense index using the ANCE checkpoint (`castorini/ance-msmarco-passage`) which is trained on MS MARCO.
https://github.com/castorini/pyserini/blob/master/scripts/ance/encode_corpus_msmarco_passage.py
It requires the input corpus to have the `jsonl` format, 
i.e. 
```
  {"id": "doc1", "contents": "this is the contents1."}
  {"id": "doc2", "contents": "this is the contents2."}
  {"id": "doc3", "contents": "this is the contents3"}
```

**Comment by spacemanidol** [comment]
I realize that dpr and such will be difficult as they are documents vs vectors. I have made a pull request just for the index. I can't add the associated queries and qrels but please find them and add here [here](https://github.com/spacemanidol/CS510IR/tree/main/Competition/data).

https://github.com/castorini/pyserini/pull/465
