### ISSUE TITLE
Integrate TAS-Balanced trained dense retrieval checkpoint

### ISSUE THREAD

**Issue by sebastian-hofstaetter** [castorini/pyserini#478]
Hi,

The integration for our Margin-MSE checkpoint was super smooth - thanks so much for that :) So I am back with a new model: I just published our TAS-Balanced trained, DistilBERT-based checkpoint for dense passage retrieval here: https://huggingface.co/sebastian-hofstaetter/distilbert-dot-tas_b-b256-msmarco

Would be awesome if we could also integrate that model in pyserini! It should be exactly the same architecture & usage as the previous Margin-MSE model. Just in case here is a minimal usage example here: https://github.com/sebastian-hofstaetter/tas-balanced-dense-retrieval/blob/main/minimal_bert_dot_usage_example.ipynb

Best,
Sebastian

**Comment by MXueguang** [comment]
@sebastian-hofstaetter Thank you for share the checkpoint.
Yes, we will integrate it in pyserini.

**Comment by lintool** [comment]
hey @jacklin64 @justram can you work on this please?

**Comment by justram** [comment]
> hey @jacklin64 @justram can you work on this please?
Ok, we're working on it.
