### ISSUE TITLE
Question on the paper [A Replication Study of Dense Passage Retriever]

### ISSUE THREAD

**Issue by robinsongh381** [castorini/pyserini#480]
Hello

I have a question on the paper [A Replication Study of Dense Passage Retriever](https://arxiv.org/pdf/2104.05740.pdf)

When you trained a Reader model with hybrid of DPR and BM25, did you rerank both train and test files for the Reader model ?
Or just one of them ?

Thank you

**Comment by MXueguang** [comment]
Hi @robinsongh381, we didn't train a Reader model in this replication study.
The Readers in our e2e QA evaluation are identical to the released checkpoints in the original DPR repo.
Concretely, 
For NQ: we used reader checkpoint: `facebook/dpr-reader-single-nq-base`
For TriviaQA: we used reader checkpoint: `facebook/dpr-reader-multiset-base`

**Comment by robinsongh381** [comment]
@MXueguang 
Thank you for your reply.

If I understand correctly, it looks like you just replaced the test dataset with hybrid of DPR and BM25 ?

Am I correct ? 

Thank you

**Comment by MXueguang** [comment]
yes. same reader for BM25, DPR and Hybrid setting
