### ISSUE TITLE
How to reproduce DPR without using model checkpoints?

### ISSUE THREAD

**Issue by ali-abz** [castorini/pyserini#502]
Hi there.
I have recently read your paper on reproducing DPR using Facebook model checkpoints and it was really informative, thanks.
I was wondering if it is possible to do the same experiment without model checkpoints (since I am working on non_English neural IRs)!
I've read the docs provided in GitHub and yet, I don't understand how to 'fine-tune' a model and how to store the dense vectors on FAISS.
So here is my question: Is it possible to leverage pyserini to create a neural IR like DPR from scratch ? if it is possible, Is there a code or documentation that I can read?

**Comment by lintool** [comment]
Unfortunately, our code doesn't provide support for training a DPR model. You'll have to use the original DPR code from Facebook for that.

Once you get the encoder models, you can use Pyserini to build the indexes and do search...

**Comment by ali-abz** [comment]
I see. Thanks.
