### ISSUE TITLE
Broken test case integrations/test_simplesearcher_check_core17.py

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#511]
Hey @MXueguang I think this is related to your recent changes - this and related test case broke: `integrations/test_simplesearcher_check_core17.py`.

This is supposed to verify that anserini and pyserini runs are exactly the same...

```
$ head verify.anserini.core17_bm25.txt 
307 Q0 497476 1 8.950200 Anserini
307 Q0 504815 2 8.886100 Anserini
307 Q0 272661 3 8.822300 Anserini
307 Q0 469928 4 8.767800 Anserini
307 Q0 125806 5 8.664200 Anserini
307 Q0 1674939 6 8.630800 Anserini
307 Q0 520656 7 8.566500 Anserini
307 Q0 5062 8 8.489800 Anserini
307 Q0 302004 9 8.372100 Anserini
307 Q0 477730 10 8.353200 Anserini
$ head verify.pyserini.core17_bm25.txt
393 Q0 157557 1 7.011200 Anserini
393 Q0 473943 2 6.816100 Anserini
393 Q0 789093 3 6.760000 Anserini
393 Q0 35680 4 6.736200 Anserini
393 Q0 1064676 5 6.555000 Anserini
393 Q0 2447 6 6.491500 Anserini
393 Q0 977063 7 6.478900 Anserini
393 Q0 115272 8 6.441500 Anserini
393 Q0 618917 9 6.423600 Anserini
393 Q0 373185 10 6.411000 Anserini
```

The topics don't seem to be coming in the right order in pyserini?

**Comment by MXueguang** [comment]
The issues is because topics should be sorted by id by default (if no predefined order), which was removed in recent changes. Adding it back.

**Comment by lintool** [comment]
If there's no predefined order, can we use the order in the topics file?

That should be the default, no?

**Comment by MXueguang** [comment]
It was sorted in the Anserini end.

**Comment by lintool** [comment]
Okay, sorry, I got confused.

I understand now: At this point, we're only using the id of the test collection, so we don't have access to the "original" topics file. Anserini uses as sorted map to hold the topics, so it's sorted by id.

Yes, default back to the Anserini sort order?

@MXueguang can we add in an additional test on MS MARCO passage to test the ordering?

**Comment by lintool** [comment]
Confirmed.

```
$ python -m unittest integrations/test_simplesearcher_check_core17.py
```

At HEAD `737fc8` passes without issue.
