### ISSUE TITLE
Add sentencepiece to requirements

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#512]
#510 noted that our README doesn't mention sentencepiece. We should add, probably to requirements? @stephaniewhoo ?

@rodrigonogueira4 @MXueguang @ronakice - sentencepiece should be straightforward enough to install that we do so automatically (i.e., transitively)?

**Comment by rodrigonogueira4** [comment]
It should: `pip install sentencepiece` always worked for me.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/536
