### ISSUE TITLE
Separating integration tests

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#515]
Testing is good, but a concern is that running all tests end-to-end is starting to take a long time...

Maybe we should separate into `integration/dense` and `integration/sparse`? Hybrid can go with "dense".

Rationale is that these are mostly distinct code paths, with less chance of interference... so this might help us iterate faster?

**Comment by MXueguang** [comment]
could this closed by https://github.com/castorini/pyserini/pull/517?

**Comment by lintool** [comment]
Yup.
