### ISSUE TITLE
Inconsistency in loading topics

### ISSUE THREAD

**Issue by jayparks** [castorini/pyserini#516]
Currently, there is mismatch in topics loading across search/dsearch/hsearch.

In `pyserini/search/__main__.py`
```
topics = get_topics(args.topics)
````

In `pyserini/dsearch/__main__.py` and `pyserini/hsearch/__main__.py`
```
if os.path.exists(args.topics) and args.topics.endswith('.json'):
        topics = json.load(open(args.topics))
    else:
        topics = get_topics(args.topics)
```

It would be good to allow loading json topics for `search` to ensure consistency.

**Comment by MXueguang** [comment]
Hi @jayparks,
Yes, we have a pending PR which will add this feature back. https://github.com/castorini/pyserini/pull/405
We will merge it once we finish regression tests.

**Comment by MXueguang** [comment]
Hi @jayparks.
https://github.com/castorini/pyserini/pull/405 is merged.
It supports loading from json.
