### ISSUE TITLE
get_topics and get_qrels fails silently

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#559]
```python
from pyserini.search import get_topics, get_qrels

topics = get_topics('blah')
qrels = get_qrels('blah')
```

Currently fails silently. It shouldn't - throw an exception or something?

**Comment by MXueguang** [comment]
> fails silently
it returns empty dict right?
yes we should throw exceptions

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/562
