### ISSUE TITLE
Missing bindings for qrels

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#560]
There are missing bindings for qrels - for example, I can't get TREC 20 DL qrels. They're in Anserini, just not properly exposed in Pyserini.

We should add test cases:
https://github.com/castorini/pyserini/blob/master/tests/test_load_topics.py

Rename `test_load_topics.py` to `test_load_topics_and_qrels.py` and make sure each topics/qrels pair works...

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/562 https://github.com/castorini/pyserini/pull/594
