### ISSUE TITLE
faiss-gpu not supported

### ISSUE THREAD

**Issue by isoboroff** [castorini/pyserini#566]
The README demos for dense and hybrid search work with faiss-cpu, but if I only have faiss-gpu installed, I get:
```
Attempting to initialize pre-built index msmarco-passage-tct_colbert-hnsw.
/local_home/soboroff/.cache/pyserini/indexes/dindex-msmarco-passage-tct_colbert-hnsw-20210112-be7119.7e12ae728ea5f2ae6d1cfb88a8775ba8 already exists, skipping download.
Initializing msmarco-passage-tct_colbert-hnsw...
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-93ed650a7449> in <module>
      5 ssearcher = SimpleSearcher.from_prebuilt_index('msmarco-passage')
      6 encoder = TctColBertQueryEncoder('castorini/tct_colbert-msmarco')
----> 7 dsearcher = SimpleDenseSearcher.from_prebuilt_index(
      8     'msmarco-passage-tct_colbert-hnsw',
      9     encoder

~/pyserini-play/venv/lib/python3.8/site-packages/pyserini/dsearch/_dsearcher.py in from_prebuilt_index(cls, prebuilt_index_name, query_encoder)
    260 
    261         print(f'Initializing {prebuilt_index_name}...')
--> 262         return cls(index_dir, query_encoder)
    263 
    264     @staticmethod

~/pyserini-play/venv/lib/python3.8/site-packages/pyserini/dsearch/_dsearcher.py in __init__(self, index_dir, query_encoder)
    229 
    230     def __init__(self, index_dir: str, query_encoder: QueryEncoder):
--> 231         requires_faiss(self)
    232         self.query_encoder = query_encoder
    233         self.index, self.docids = self.load_index(index_dir)

~/pyserini-play/venv/lib/python3.8/site-packages/transformers/file_utils.py in requires_faiss(obj)
    501     name = obj.__name__ if hasattr(obj, "__name__") else obj.__class__.__name__
    502     if not is_faiss_available():
--> 503         raise ImportError(FAISS_IMPORT_ERROR.format(name))
    504 
    505 

ImportError: 
SimpleDenseSearcher requires the faiss library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/facebookresearch/faiss/blob/master/INSTALL.md and follow the ones
that match your environment.
```

**Comment by isoboroff** [comment]
I’m working in a virtual environment and installing via pip. I might have a versioning issue, or I will try conda instead.

**Comment by isoboroff** [comment]
If I install faiss-cpu, it works, and if I use --encoder and --cuda arguments, it does run on GPU.  So you may need to have both faiss-cpu and faiss-gpu to use GPU.

**Comment by lintool** [comment]
Nice! Can you share with us a performance comparison?

**Comment by MXueguang** [comment]
In the current Pyserini release, we don't support faiss GPU.
Even though the encoding process is run on GPU, the search process is still running on CPU (and uses faiss-cpu).
But I think we can support GPU searching in our next release? @lintool

**Comment by lintool** [comment]
But are our docs not accurate then? https://github.com/castorini/pyserini/blob/master/docs/experiments-tct_colbert.md

>  To perform query encoding on the GPU, use the option --device cuda:0.

**Comment by lintool** [comment]
Closing, as the answer to "faiss-gpu not supported" is "correct". I've clarified in #933. 

If down the road we find a pressing need to support `faiss-gpu`, we can open another issue.

**Comment by EntilZha** [comment]
Out of curiosity/potential interest in implementing gpu addon, is it not supported mainly due to it not being important in the past (so main barrier is time to implement) or is there a technical limitation that makes it challenging?

**Comment by lintool** [comment]
no technical limitation, just implementation time!
