### ISSUE TITLE
add detailed installation guide

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#573]
Now we have a general installation guide in README.md with all related info.
But we also need a more "step by step" setup guide for Windows (or Linux as well).

**Comment by lintool** [comment]
Agreed, but we should have this linked off README to a separate page.

**Comment by MXueguang** [comment]
yeah agreed!

**Comment by lintool** [comment]
This is a reasonable start: https://github.com/castorini/pyserini/blob/master/docs/installation.md

Closing for now.
