### ISSUE TITLE
Sparse retrieval using BM25 on the custom data 

### ISSUE THREAD

**Issue by ddehun** [castorini/pyserini#579]
Hi. First of all, thank you for your helpful project!

I hope to search my own documents using the BM25 algorithm.

I built my own index following the below guideline.
https://github.com/castorini/pyserini#how-do-i-index-and-search-my-own-documents

Now I can search the docs like the below, but I'm not sure whether this "searcher" searches the documents with the BM25 ranking, or other algorithms like the similarity between BoW or TF-IDF representations. 

```
from pyserini.search import SimpleSearcher
searcher = SimpleSearcher('my_custom_index')
hits = searcher.search('my query blah blah')
```
If I hope to retrieve documents using the BM25 algorithm, can I just use the SimleSearch() class and its "search()" function?

Thank you!

**Comment by lintool** [comment]
Yes, `SimpleSearcher` uses BM25.

**Comment by ddehun** [comment]
Thank you!!
