### ISSUE TITLE
Documentation for pre-built indexes

### ISSUE THREAD

**Issue by JMMackenzie** [castorini/pyserini#582]
I think we can improve the documentation for pre-built indexes. For example, following the [TCT-ColBERT examples ](https://github.com/castorini/pyserini/blob/master/docs/experiments-tct_colbert.md), I can successfully reproduce the numbers. However, the HNSW index does not have any parameters documented, including:
  - `M`
 -  `ef_construction`
  - `ef_search`
  
  Currently, these seem to be [hardcoded](https://github.com/castorini/pyserini/blob/master/scripts/msmarco-passage/build_hnsw_index.py), so some documentation would be great, especially since they impact time/space/quality.

**Comment by lintool** [comment]
hey @MXueguang maybe we can document directly in the index metadata? e.g., https://github.com/castorini/pyserini/blob/master/pyserini/prebuilt_index_info.py#L464

As well as in the documentation?

**Comment by lintool** [comment]
Moving forward, we'll document in READMEs like this:
https://github.com/castorini/pyserini/blob/master/pyserini/resources/index-metadata/faiss-hnsw.cast2019.tct_colbert-v2-readme.txt

And these READMEs will get linked to from auto-generated documentation:
https://github.com/castorini/pyserini/blob/master/docs/prebuilt-indexes.md
