### ISSUE TITLE
BM25 w/ ANN (hnsw) - or, more generally - I want to search my own vectors

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#583]
Discussion w/ @JMMackenzie - for reference, we should try BM25 with ANN to compare time/space/quality tradeoffs with inverted indexes.

This was done previously in https://dl.acm.org/doi/abs/10.1145/3409256.3409818 but we should integrate into Pyserini for better comparison.

**Comment by MXueguang** [comment]
I think we will use this dependency https://github.com/nmslib/nmslib
so instead of `/pyserini/search` we need another module for sparse ann? 
what should be the name of the module?

**Comment by lintool** [comment]
Is introducing a new dependency necessary? We can't just use Faiss? Can't either hnsw or bf just work with sparse vectors? Isn't that what the ICTIR paper did?

How about `pyserini/search` but `SimpleAnnSearcher` vs `SimpleSearcher`?

**Comment by MXueguang** [comment]
ICTIR was using `nmslib`
Faiss dont have sparse features

**Comment by lintool** [comment]
<img width="423" alt="Screen Shot 2021-05-18 at 9 55 02 PM" src="https://user-images.githubusercontent.com/313837/118745224-bc73bd80-b823-11eb-8f40-cc76ee9ff347.png">

I think this is what I want, just integrated into Pyserini.

I'm a bit confused though... it says hnsw also... so what's the difference between hnsw in faiss vs. in nmslib?

**Comment by MXueguang** [comment]
- nmslib has faster HNSW on CPU than Faiss
- Faiss has GPU support but nmslib don't
- nmslib support sparse matrix but Faiss dont

https://www.benfrederickson.com/approximate-nearest-neighbours-for-recommender-systems/
https://github.com/erikbern/ann-benchmarks

**Comment by lintool** [comment]
Seems like there's demand for "index your own vectors" #597

**Comment by lintool** [comment]
How about this: in addition to `search`, `dsearch`, we add `vsearch` - for "vector" search. It's the use case where I have my own vector definitions, and I just want to index them.

So, in the case of BM25, we "dump out" BM25-weighted doc vectors, and run through the `vsearch` package - built on nmslib?

I think this separation is reasonable, as we can dump out the encoded transformer representations (e.g., from TCT-ColBERT) and index with `vsearch` - this would give us a head's up comparison between two different hnsw implementations?

When Lucene 9 comes around, `vsearch` can also use the Java-based hnsw implementation.

**Comment by MXueguang** [comment]
sg. I'll take a look at this next, since I have replicated the ICTIR paper with nmslib before.

**Comment by MXueguang** [comment]
My plan is we accept two type of corpus with vectors.
1. dense, 
```
{
  "id": "doc1",
  "contents": "The Manhattan Project and its atomic bomb helped bring an end to World War II. Its legacy of peaceful uses of atomic energy continues to have an impact on history and science.",
  "vec": [ 0.1234, 0.4567, ..., 0.1245 ]
}
```

2. sparse, (BM25)
```
{
  "id": "doc1",
  "contents": "The Manhattan Project and its atomic bomb helped bring an end to World War II. Its legacy of peaceful uses of atomic energy continues to have an impact on history and science.",
  "vec": [ (123, 0.45678), (2445, 1.2456), ..., (11115, 0.1234) ]
}
```

for queries, we stay with current encoded-queries? i.e. store things in pkl file?

**Comment by lintool** [comment]
`vec` -> `vector`: no need to save three characters

I suppose the contract should be that the dimensions of `vector` do not need to have any relationship with the text? Because otherwise you'd need to involve a tokenizer, etc. That is, the dimensions might be arbitrary?

**Comment by MXueguang** [comment]
this can be closed? as we are having new pipeline @lintool ?
