### ISSUE TITLE
Relax tqdm version requirement

### ISSUE THREAD

**Issue by jayparks** [castorini/pyserini#585]
Hello, thanks for the great library.

I was wondering if the version requirement for `tqdm` could be relaxed.
I'm currently using Pyserini and Huggingface [datasets](https://github.com/huggingface/datasets/) for my project.
The problem is `datasets` forces `tqdm < 4.50` for its latest versions due to some permission issues. 
However, pyserini requires `tqdm>=4.56.0`, which gives a version mismatch.

Will lower versions of `tqdm` cause any issue for Pyserini?
If not, can you consider lowering the version requirement for `tqdm`? 

Thanks!

**Comment by MXueguang** [comment]
@jayparks shouldn't have problem unless tqdm version is too old.
yes, we will consider relax the tqdm version

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/587

**Comment by jayparks** [comment]
Thanks :)
