### ISSUE TITLE
Group sync of Python dependencies

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#599]
Let's try to sync version of dependencies across the group:

transformers: 4.6.1
torch: 1.8.1
faiss-cpu: 1.7.0
sentencepiece: 0.1.95

**Comment by stephaniewhoo** [comment]
For ltr, spacy: 3.0.6

**Comment by yuki617** [comment]
spacy: 2.2.3
scikit-learn 0.24.1
lightgbm 3.1.1

**Comment by lintool** [comment]
Latest scikit-learn==0.24.2 - do we just want to upgrade all the way to latest?

**Comment by stephaniewhoo** [comment]
> Latest scikit-learn==0.24.2, lightgbm==3.2.1 - do we just want to upgrade all the way to latest?

Should be ok. I will try with these newest version to see if the score gets diff

**Comment by lintool** [comment]
@MXueguang Can you send a PR to fix the issue:

```
ImportError: cannot import name 'requires_faiss'
```

For `transformers==4.6.1`?

**Comment by MXueguang** [comment]
https://github.com/castorini/pyserini/pull/601

**Comment by lintool** [comment]
Let's upgrade https://pypi.org/project/pyjnius/ while we're at it to 1.3.0?

**Comment by lintool** [comment]
@stephaniewhoo @yuki617 Do we care about the pandas version?

**Comment by lintool** [comment]
I think this is where we're at currently:

```
$ pip list | egrep '(pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy)\s'
faiss-cpu                     1.7.0
lightgbm                      3.2.1
pyjnius                       1.3.0
scikit-learn                  0.24.2
sentencepiece                 0.1.95
spacy                         3.0.6
torch                         1.8.1
transformers                  4.6.1
```

**Comment by stephaniewhoo** [comment]
> @stephaniewhoo @yuki617 Do we care about the pandas version?

Mine is 1.1.4. Reranking uses the most basic pandas ops: read_csv, DataFrame etc. I roughly go through pandas document and it seems ok.

FYI: I tried to update pandas to 1.2.4(latest version) on orca, but did not succeed.

**Comment by yuki617** [comment]
Mine is 1.1.3. I have tried different pandas version before, both of them works. Just like stephanie said, we just use some very basic pandas function, so different version should be fine.

**Comment by lintool** [comment]
I am at on my iMac Pro:

```bash
$ pip list | egrep '(pyjnius|transformers|torch|sentencepiece|faiss-cpu|scikit-learn|lightgbm|spacy)\s'
faiss-cpu                     1.7.0
lightgbm                      3.2.1
pyjnius                       1.3.0
scikit-learn                  0.24.2
sentencepiece                 0.1.95
spacy                         3.0.6
torch                         1.8.1
transformers                  4.6.1
```

At commit `fb97f099`. Dense integrations produce one error, which appears to be unrelated:

```
$ python -m unittest discover -s integrations/dense

.
======================================================================
ERROR: test_msmarco_doc_ance_bf_encoded_queries (test_ance.TestSearchIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jimmylin/workspace/pyserini/integrations/dense/test_ance.py", line 83, in test_msmarco_doc_ance_bf_encoded_queries
    topics = get_topics('maxp-msmarco-doc-dev')
  File "/Users/jimmylin/workspace/pyserini/pyserini/search/_base.py", line 212, in get_topics
    raise ValueError(f'Topic {collection_name} Not Found')
ValueError: Topic maxp-msmarco-doc-dev Not Found

----------------------------------------------------------------------

```

@MXueguang this is a simple typo, I think - please send PR for fix?

However, I am getting this hgf warning:

```
Some weights of the model checkpoint at castorini/tct_colbert-msmarco were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

@jacklin64 @justram this should be okay?

**Comment by lintool** [comment]
On my iMac Pro, everything passed:

```
python -m unittest discover -s integrations/sparse
```

I'm at commit `89f0ced`, so this includes @stephaniewhoo LTR integration test case.

**Comment by justram** [comment]
> However, I am getting this hgf warning:
> 
> ```
> Some weights of the model checkpoint at castorini/tct_colbert-msmarco were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
> - This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> ```
> 
> @jacklin64 @justram this should be okay?

This warning is ok because it is coming from redundant parameters stored in the state dict.

BTW, @MXueguang may I check the checkpoint transform script for tct-colbert?
I think the reason for having redundant parameters is that the dummy model is initialized with [BertForPretraining](https://github.com/huggingface/transformers/blob/73fde1defe9be259a47b9024525882f3ec420994/src/transformers/models/bert/modeling_bert.py#L1006) instead of [BertModel](https://github.com/huggingface/transformers/blob/73fde1defe9be259a47b9024525882f3ec420994/src/transformers/models/bert/modeling_bert.py#L828)

**Comment by MXueguang** [comment]
@justram 
https://github.com/castorini/pyserini/blob/f97b4675e3ce36cb517fae1c28aa11143b14e4fe/pyserini/dindex/_base.py#L30
yes I used BertModel. It is better to chance to BertForPretraining?

**Comment by lintool** [comment]
clprf integrations passed without issue:

```bash
$ python -m unittest discover -s integrations/clprf/
```

🎉 @yuki617

**Comment by yuki617** [comment]
> clprf integrations passed without issue:
> 
> ```shell
> $ python -m unittest discover -s integrations/clprf/
> ```
> 
> 🎉 @yuki617



> clprf integrations passed without issue:
> 
> ```shell
> $ python -m unittest discover -s integrations/clprf/
> ```
> 
> 🎉 @yuki617

Awesome，thanks for checking!

**Comment by lintool** [comment]
FYI -

```bash
$ python scripts/ltr_msmarco-passage/convert_queries.py
2021-05-24 10:32:51.792197: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-24 10:32:51.792235: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "scripts/ltr_msmarco-passage/convert_queries.py", line 27, in <module>
    import spacy
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/spacy/__init__.py", line 14, in <module>
    from .cli.info import info  # noqa: F401
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/scratch2/jimmylin/env/lib/python3.6/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

This appears to be an issue with:

```
$ pip list | grep click
click                   8.0.1
```

Downgrading to 7.1.2 fixes the issue.

**Comment by lintool** [comment]
I've run all three pyserini integration tests on `orca`.

```
nohup python -m unittest discover -s integrations/sparse >& log.sparse &
nohup python -m unittest discover -s integrations/dense >& log.dense &
nohup python -m unittest discover -s integrations/clprf >& log.clprf &
```

All passed, at commit `f97b46` (2021/05/22): `sparse` (30 tests in ~2.7h), `dense` (37 tests in ~25.9h), `clprf` (43 tests in ~25.6h).

I have `sudo pip` installed the packages above so they are now system-wide defaults. For future reference I'm attaching the exact configuration.

[pip-freeze-orca-2021-05-25.txt](https://github.com/castorini/pyserini/files/6541357/pip-freeze-orca-2021-05-25.txt)
[pip-list-orca-2021-05-25.txt](https://github.com/castorini/pyserini/files/6541358/pip-list-orca-2021-05-25.txt)

**Comment by lintool** [comment]
With v0.14.0 release, we're sync'ed up. Closing.
