### ISSUE TITLE
Do we still need tests/test_encoded_queries.py?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#606]
Hi @MXueguang `tests/test_encoded_queries.py` test cases have been moved into the individual dense integration tests right? Do we still need this?

Usually, we want to keep unit tests lightweight and fast, right? Doesn't make sense to test multiple times... should we remove here?

**Comment by MXueguang** [comment]
sure

**Comment by lintool** [comment]
Okay, please confirm that the tests are covered in `integrations/` and then send PR to remove? Thanks!
