### ISSUE TITLE
LTR documentation: split into training and inference

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#608]
Currently, we have: https://github.com/castorini/pyserini/blob/master/docs/experiments-ltr-msmarco-passage.md

Which covers both training and inference... but I can imagine there being two distinct user types, those wanting to just use our model and those who want to train a new model, just like we have people wanting to use monoBERT and others wanting to retrain their own monoBERT.

So, maybe break into two separate READMEs?

+ `experiments-msmarco-passage-ltr-inference.md`
+ `experiments-msmarco-passage-ltr-training.md`

@stephaniewhoo thoughts?

**Comment by stephaniewhoo** [comment]
sg! so in training README, we can reveal more details like sampling num, optimization goal etc

**Comment by stephaniewhoo** [comment]
Close with #636
