### ISSUE TITLE
Tweak tagline in boilerplate

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#609]
Currently, we have in our (source code) boilerplate:

```
#
# Pyserini: Python interface to the Anserini IR toolkit built on Lucene
#
```

This was back when Pyserini was just a wrapper around Anserini... but it's evolved into something way more...

The "tagline" we converged on in the Pyserini SIGIR resource paper was: "Pyserini is a Python toolkit for reproducible information retrieval research with sparse and dense representations."

This is too long for the boilerplate, and line wrapping looks odd.

The best I could come up with is:

```
#
# Pyserini: Reproducible IR research with sparse and dense representations
#
```

I figured that "Python" was kinda redundant since the boilerplate is on source code...

Thoughts? @MXueguang @jacklin64 @justram @rodrigonogueira4 @ronakice ?

**Comment by rodrigonogueira4** [comment]
I think it makes sense.
