### ISSUE TITLE
Boolean retrieval

### ISSUE THREAD

**Issue by Fatima-Haouari** [castorini/pyserini#610]
Hi,
Is boolean retrieval supported by Pyserini? please advise on how can we perform retrieval for queries with AND, OR, and NOT operators using Pyserini.
Many thanks in advance.

**Comment by lintool** [comment]
See https://github.com/castorini/pyserini/blob/master/docs/usage-querybuilder.md

**Comment by Fatima-Haouari** [comment]
Thanks a lot for your quick response. I appreciate it.
