### ISSUE TITLE
MsMarcoPassageLtrSearcher

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#611]
Hi @stephaniewhoo - what do you think about refactoring your LTR code into something like `MsMarcoPassageLtrSearcher` alongside `SimpleSearcher`? https://github.com/castorini/pyserini/blob/master/pyserini/search/_searcher.py#L39

Currently we can do this:

```
$ python -m pyserini.search --topics msmarco-passage-dev-subset --index msmarco-passage --output run.msmarco-passage.txt --bm25 --output-format msmarco
```

We can similarly expose `MsMarcoPassageLtrSearcher`, something like:

```
$ python -m pyserini.msmarco_passage_ltr_search ... --model ...
```

**Comment by stephaniewhoo** [comment]
Close with #636
