### ISSUE TITLE
Unit test temp_dir/ clean-up

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#615]
After running unit tests, `python -m unittest`, there seems to be `temp_dir/` that isn't cleaned up properly.

**Comment by lintool** [comment]
Also, `test_run.msmarco-doc.passage.ance-maxp.otf.txt` seems to be left over from integration tests.

**Comment by MXueguang** [comment]
closed by https://github.com/castorini/pyserini/pull/616
