### ISSUE TITLE
supprt dindex with collection in tsv format

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#644]
currently, we only support jsonl files as input for index.
but I just notice JSON is not the best option for languages other than English...
```
{"id": "7-0", "contents": "\u0627\u0644\u0645\u0627\u0621 }
```
text format, e.g. TSV might be a better option, where people can read the contents, will be easier for debugging etc.
we'd better support TSV as well.

**Comment by lintool** [comment]
Is this a matter of standards compliance or does the JSON parser actually choke on human readable input?

**Comment by lintool** [comment]
Poking around a bit, it _does_ seem like Python can read non-escaped characters:
https://pynative.com/python-json-encode-unicode-and-non-ascii-characters-as-is/

I would be hesitant about adding another input format...

**Comment by MXueguang** [comment]
ah I see.
so simple solution `ensure_ascii=False` while dumping into json

**Comment by MXueguang** [comment]
yeah, we can stay with jsonl only rn.
