### ISSUE TITLE
Missing argument in hybrid retrieval

### ISSUE THREAD

**Issue by jayparks** [castorini/pyserini#653]
The `prefix` argument for `init_query_encoder` is missing in hybrid search.

https://github.com/castorini/pyserini/blob/7f56ecd1210aacbf6f24cd7a724d5562ea671c0d/pyserini/hsearch/__main__.py#L103

**Comment by MXueguang** [comment]
@jayparks should be fixed by https://github.com/castorini/pyserini/pull/655?

**Comment by jayparks** [comment]
Yes it's solved. Thanks
