### ISSUE TITLE
Reorganization of packages for dense retrieval?

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#659]
Hey @MXueguang - since `dindex` is really about encoding the corpus, and we're using `IndexFlatIP` mainly as a data interchange format (as opposed to TF records), does it make sense to reorg the package structure for the next major release?

E.g., something like:

+ `pyserini.encode` - primarily about encoding (bf index is really just a "side effect")
+ `pyserini.findex` - for faiss indexes (e.g., faiss hnsw)
+ `pyserini.nindex` - for nmslib indexes

Or shall we be explicit? e.g., `pyserini.lucene_index`, `pyserini.faiss_index`, `pyserini.nmslib_index`.

And `pyserini.faiss_search` and `pyserini.nmslib_search`.

So, for example, methods in `pyserini.nmslib_index` can either take `IndexFlatIP` as input or a JSON collection with explicit vectors?

Thoughts?

**Comment by lintool** [comment]
Noting apparent code duplication I just discovered:

https://github.com/castorini/pyserini/blob/master/pyserini/dindex/_base.py#L54
https://github.com/castorini/pyserini/blob/master/pyserini/encode/_dpr.py#L22

**Comment by MXueguang** [comment]
@lintool 
The first stage of code reorganization targeting at following current modules:
- `pyserini.dindex`: encoding raw collections in `jsonl` format, store as Faiss flat index. This module currently contains all document encoder class for dense retrieval.
- `pyserini.index`: build lucene index
- `pyserini.dsearch`: do dense search on faiss index. This module currently contains all query encoder class for dense retrieval.

In refactoring, we are trying to do:
- remove `pyserini.dindex`, replace it with `pyserini.encode`: `pyserini.encode` will contains all document encoder and query encoder class for both dense (e.g. dpr) and sparse (e.g. unicoil) model.
- remove the query encoders defined in current `pyserini.dsearch` by class defined in `pyserini.encode`
- `pyserini.encode` will do: a) encode raw collection (in `jsonl` format) into `jsonl` format with vectors (for sparse/dense), b) encode raw collection and store as Faiss Flat index (for dense only).
- will change current `pyserini.index` into `pyserini.index.lucene` `pyserini.index.faiss` and `pyserini.index.nmslib`
- `pyserini.index.lucene` can a). index raw text collection in `jsonl` format into lucene bm25 index. b). index collection with sparse vector (generated by `pyserini.encode` using sparse model, e.g. unicoil) into lucene impact index.
- `pyserini.index.faiss` can a). convert `jsonl` with dense vectors into Faiss index. b) build Faiss PQ/HNSW index from flat index or vector collections in `jsonl` format.
- `pyserini.index.nmslib` can a) build `nmslib` index from Faiss flat index. b). build sparse `nmslib` hnsw index from `jsonl` with sparse vector.

_The above refactoring is already done and ready for submitting PRs._


The second stage of code reorganization may touch the following `search` modules:
- `pyserini.dsearch`: conduct dense search with `faiss` index
- `pyserini.search`: conduct sparse (bm25, impact) search with `lucene` index
- `pyserini.vsearch`: conduct sparse/dense hnsw search with `nmslib` index
- `pyserini.hsearch`: take one class from `dsearch` and one class from `search` and hybrid.

IMO, the key question here is: should we manage search by type or by tool. i.e.:
1. should we do: `pyserini.search.faiss`, `pyserini.search.lucene`, `pyserini.search.nmslib`
2. or : `pyserini.search`, `pyserini.dsearch`
seems (1) will make things more clear?
For interactive API, we can have something like: `from search import SimpleSearcher, ImpactSearcher, SimpleDenseSearcher, NmslibSearcher`?

**Comment by lintool** [comment]
My vote is for (1) `pyserini.search.faiss`, `pyserini.search.lucene`, `pyserini.search.nmslib`

Thus:
+ `SimpleSearcher` -> `LuceneSearcher`
+ `ImpactSearcher` -> `LuceneImpactSearcher`
+ `SimpleDenseSearcher` -> `FaissSearcher`
+ `NmslibSearcher`

We should retain the old names and package locations as facades of the properly refactored structure so that old command still work. However, these old command should throw a deprecation warning.

**Comment by lintool** [comment]
Relevant issues:
+ `pyserini.search` -> `pyserini.search.lucene` #991
+ `pyserini.dsearch` -> `pyserini.search.faiss` #1006
+ `pyserini.hsearch` -> `pyserini.search.hybrid` #1030
+ `pyserini.vsearch` -> `pyserini.search.nmslib` #1032

We're partway through this major refactoring...

**Comment by lintool** [comment]
This was completed and pushed out in v0.16.0 release. Some additional loose ends to tie up here and there, but the bulk of the work is done.
