### ISSUE TITLE
Outdated documents

### ISSUE THREAD

**Issue by x389liu** [castorini/pyserini#67]
pyserini notebooks are not updated with the most recent commit.

For example, in [pyserini_robust04_demo.ipynb](https://github.com/castorini/anserini-notebooks/blob/master/pyserini_robust04_demo.ipynb?short_path=3bb45ad#L229), `hits[0].contents` should be used  instead of `hits[0].content` after this [change]( https://github.com/castorini/anserini/commit/ff96bade6c073335c91e6089f0de1cbda15b9dcd#diff-30310c33f0d9db480ee8a6aec78fef71R112).

**Comment by lintool** [comment]
I've updated the notebooks. Thanks for catching this!
