### ISSUE TITLE
cannot import name 'requires_faiss' from 'transformers.file_utils' 

### ISSUE THREAD

**Issue by CharlotteYang12345** [castorini/pyserini#670]
![WeChatf2631cb2679c58f10f14056db6d46998](https://user-images.githubusercontent.com/32707910/123263592-1174b480-d4f1-11eb-9265-bfdd676b36bf.png)

**Comment by lintool** [comment]
Did you follow the installation instructions on the README?

**Comment by MXueguang** [comment]
@CharlotteYang12345, the `requires_faiss` was removed from latest `transformers`.
To fix this issue, there are two options.
1. downgrade transformers to <=3.4.0
2. pull our latest code and do development installation
