### ISSUE TITLE
Better error message when index doesn't store doc vectors to support RM3 expansion

### ISSUE THREAD

**Issue by rodrigonogueira4** [castorini/pyserini#695]
This allows us to use RM3 query expansion.

**Comment by lintool** [comment]
In more detail:

```python -m pyserini.search \
    --topics dl19-passage \
    --index msmarco-passage \
    --output run.dl19-passage.txt \
    --rm3
```

Gives:

```
java.lang.NullPointerException
        at io.anserini.rerank.lib.Rm3Reranker.createdFeatureVector(Rm3Reranker.java:194)
        at io.anserini.rerank.lib.Rm3Reranker.estimateRelevanceModel(Rm3Reranker.java:151)
        at io.anserini.rerank.lib.Rm3Reranker.rerank(Rm3Reranker.java:83)
        at io.anserini.rerank.RerankerCascade.run(RerankerCascade.java:64)
        at io.anserini.search.SimpleSearcher.search(SimpleSearcher.java:594)
        at io.anserini.search.SimpleSearcher.search(SimpleSearcher.java:546)
```

At the very least, we should have better error messages...

**Comment by HAKSOAT** [comment]
Hello, I spent some time looking into this and can see where the traceback comes from.

https://github.com/castorini/pyserini/blob/a052748ea669125a129138fd2f53402a423b14bb/pyserini/search/lucene/_searcher.py#L131

Which calls this:

https://github.com/castorini/anserini/blob/2e8e9fdfedc1b81522d9e22a805e08e6a7105762/src/main/java/io/anserini/search/SimpleSearcher.java#L583

My intention was to add a test `search` call at the point where RM3 is set which is:

https://github.com/castorini/pyserini/blob/a052748ea669125a129138fd2f53402a423b14bb/pyserini/search/lucene/_searcher.py#L231

This way I should be able to add the custom error message during error handling right at the point where RM3 is being set. Something like:

```
self.object.setRM3(fb_terms, fb_docs, original_query_weight, rm3_output_query, rm3_filter_terms)
i = self.object.search("Test", 1)
# find someway to identify the error here and raise an error with a better error message
# if i has error:
#  raise Index Without DocVectors Don't Support RM3 Expansion
```

However, I noticed:

1. the error does not seem to cause the program to crash
2. I wasn't able to use a try and except to catch the error
3. I couldn't get the error using `traceback`

So, how do I go about triggering something in the actual Python code when something goes wrong in the Java part? Should we be handling this in Pyserini or is it better handled in Anserini?

**Comment by HAKSOAT** [comment]
Better still, am I approaching this the wrong way?

**Comment by lintool** [comment]
> This way I should be able to add the custom error message during error handling right at the point where RM3 is being set. Something like:
> 
> ```
> self.object.setRM3(fb_terms, fb_docs, original_query_weight, rm3_output_query, rm3_filter_terms)
> i = self.object.search("Test", 1)
> # find someway to identify the error here and raise an error with a better error message
> # if i has error:
> #  raise Index Without DocVectors Don't Support RM3 Expansion
> ```

Yup, I was thinking something along these lines. At the point of `setRM3`, determine if RM3 can be successfully executed. If no, then print a warning and the method should be a no-op.

See if there's a way you can introspect the index (i.e., directly find out of doc vectors are stored)... instead of trying a test query and catching an exception.
