### ISSUE TITLE
Unrecognized index name

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pyserini#696]
Hi，sorry to bother you，I met a problem which can be described as follows:

My directory structure looks like this
![11](https://user-images.githubusercontent.com/40745058/125230735-fb962a80-e30b-11eb-8441-5b3b8d533bf8.JPG)

I ran the command correctly yesterday but for today，commands are as follows:
from pyserini.search import SimpleSearcher
searcher=SimpleSearcher.from_prebuilt_index('indexes/index-robust04-20191213/')

when I tried to reload it, The following error occurred：
Attempting to initialize pre-built index indexes/index-robust04-20191213/.
Unrecognized index name indexes/index-robust04-20191213/

I wonder why I can't reload the same index ？can you help me?

**Comment by MXueguang** [comment]
ah if you use custom index, 
please init searcher by
```
searcher=SimpleSearcher('indexes/index-robust04-20191213/')
```

i.e. call constructor directly

`from_prebuilt_index` is for our self-contained indexes

**Comment by XY2323819551** [comment]
> Hi @XY2323819551 if you use custom index,
> please init searcher by
> 
> ```
> searcher=SimpleSearcher('indexes/index-robust04-20191213/')
> ```
> 
> i.e. call constructor directly
> 
> `from_prebuilt_index` is for our self-contained indexes

Thanks for your help! 😁
