### ISSUE TITLE
How can I build an index with pyserini?

### ISSUE THREAD

**Issue by ypapanik** [castorini/pyserini#7]
Hi, congratulations for this work!
I just wanted to ask, if possible, to add an example on how to use pyserini to build a new index. Also, to build my own collection, do I just have to override the Collection class?
Thanks!

**Comment by lintool** [comment]
Unfortunately, we haven't exposed the hooks in Python for indexing. You'll have to do this on the Anserini (Java) end. Take a look at this as an example: https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-passage.md

> Also, to build my own collection, do I just have to override the Collection class?

On the Java end, yes. Pyserini just consists of lightweight Python wrappers... most of the real work is done on the Java end...

**Comment by ypapanik** [comment]
Ok, thank you for clarifying this!
Keep up the good work!
