### ISSUE TITLE
BPR reproduction

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#712]
hey @alexlimh https://github.com/castorini/pyserini/blob/master/docs/experiments-bpr.md

(1) Add a link from the main README?
(2) Can we get someone to reproduce to make sure everything checks out?

**Comment by alexlimh** [comment]
Got it. @MXueguang would upload the pre-built index soon and it should be ready for reproduction after that.

**Comment by lintool** [comment]
Ref #753

Done!
