### ISSUE TITLE
Double check MS MARCO doc v2 corpus segmentation

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#714]
We have a segmentation script for MS MARCO doc v2:
https://github.com/castorini/pyserini/blob/master/scripts/msmarco_v2/segment_docs.py

And we have the generated output on `orca` at `/store/collections/msmarco/msmarco_v2_doc_segmented`.

We should confirm that the script does indeed generate that corpus, i.e., check md5sums. @MXueguang I believe you were going to do it?

Double check - spacy version, filtering heuristics, etc.

**Comment by MXueguang** [comment]
yes

**Comment by lintool** [comment]
This has been confirmed.
