### ISSUE TITLE
Build Sparse Index for NQ

### ISSUE THREAD

**Issue by oriram** [castorini/pyserini#730]
Hi :)

First, many thanks for this awesome library!

I wanted to ask - what is the command to build the sparse index over DPR's data `psgs_w100.tsv` (i.e., reproduce your `wikipedia-dpr` index)?

**Comment by MXueguang** [comment]
Hi @oriram,
psgs_w100.tsv need to be converted to jsonl format first, e.g. https://www.dropbox.com/s/n0c0ypuo25zdks0/wikipedia-dpr-jsonl.tar.gz
and then build the index by following this [guide](https://github.com/castorini/pyserini#how-do-i-index-and-search-my-own-documents)

**Comment by oriram** [comment]
@MXueguang Many thanks for your quick response!
This is what I tried but for some reason the index directory turned out to be around 3.5GB, whereas the cached version of your `wikipedia-dpr` index is 11GB.
Any thoughts?

**Comment by MXueguang** [comment]
@oriram could you double check if you added `-storeRaw` option?
We built the index with raw collection stored in the index.
The raw collection should be than 3.5G. 

Without storing anything additional things (i.e. wtihout storeRaw storeVector etc.) the pure index will  be around 2.5 G

**Comment by oriram** [comment]
When adding `-storeRaw` the index is indeed around 3.5GB. When adding `-storeContents` it grows significantly (to ~20GB). 
Does that make any sense?

**Comment by oriram** [comment]
Your index (in `pyserini/cache/indexes/index-wikipedia-dpr-20210120-d1b9e6.c28f3a56b2dfcef25bf3bf755c264d04`) is 11GB, however.

**Comment by lintool** [comment]
`-storeContents` stores the document vector representations in the index, which enable relevance feedback.

Here's the "model card" for the index:
https://git.uwaterloo.ca/jimmylin/anserini-indexes/-/blob/master/index-wikipedia-dpr-20210120-d1b9e6-readme.txt

If you are able to perform retrieval and get the same level of effectiveness, then you should be good.

**Comment by oriram** [comment]
OK, I think it answers my question :)
Many thanks @MXueguang @lintool!!

**Comment by lintool** [comment]
Hi @oriram - if you are willing, we would appreciate a contribution of how exactly you reproduced this, so that the next person to come along can just copy and paste a bunch of commands to do what you did.

Attached directly to this issue would be a good start. Maybe later we can figure out how to build a document page around it.

**Comment by oriram** [comment]
Sure, I basically created a jsonlines file from `psgs_w100.tsv`, similar to the structure you propose:
`{"id": PSG_ID, "contents": TITLE + "\n" + PSG_TXT}`

I then ran
```
python -m pyserini.index \
-collection JsonCollection \
-generator DefaultLuceneDocumentGenerator \
-threads 50 \
-input JSONL_DIR \
-index OUTPUT_DIR \
-storePositions \
-storeDocvectors \
-storeRaw \
[-storeContents]
```
Where the last flag (`-storeContents`) increased the index from 3.5GB to ~20GB.

@lintool Is this what you had in mind? Any missing details?

**Comment by lintool** [comment]
@oriram thanks!
@MXueguang do we need anything else for reproduction?
