### ISSUE TITLE
About openjdk

### ISSUE THREAD

**Issue by XY2323819551** [castorini/pyserini#731]
Hi, I created my conda env base on the methods you have provided in this file"https://github.com/castorini/pyserini/blob/master/docs/installation.md"，but I still have some questions.
(1)Need I configure JAVA_PATH after using conda to install openjdk? if it is, how should i do that?
(2)Is this openjdk only valid for the current conda environment?

Looking forward for you reply!

**Comment by lintool** [comment]
I don't know off the top of my head... are you getting any errors?

**Comment by MXueguang** [comment]
Hi @XY2323819551 
(1) I think you dont need config JAVA_PATH if you install it via conda
(2) yes I think

**Comment by XY2323819551** [comment]
@MXueguang Thank you !/smile
