### ISSUE TITLE
Supporting K > 10 hits with SimpleSearcher for MSMARCO passage-ranking?

### ISSUE THREAD

**Issue by samjgorman** [castorini/pyserini#743]
Hello! The SimpleSearcher class has been quite helpful for me to generate ranked Top K@10 for a BM25 baseline with MSMARCO passage-ranking. 

It appears that the output of searcher.search() is contained to 10 hits.  Assuming that this will remain so, but wanted to inquire as to whether you plan on supporting K > 10 lookups? This would make the SimpleSearcher class helpful in creating  more robust TopK@50+ lookups for MS-MARCO and make it easier to quickly evaluate BM25 baselines for ranking tasks.  However, can imagine this may substantially increase the size of the pre-built index, so certainly understand rationale against K > 10 as well.  Thank you!

**Comment by MXueguang** [comment]
Hi @samjgorman,
We do support K > 10:
```
hits = searcher.search('what is a lobster roll?', k=100)
```
e.g. this command should give you 100 hits.

Is this what you looking for?

**Comment by samjgorman** [comment]
Yes-- this is exactly what I was looking for.  Just saw that this was mentioned in the release notes of 0.10.0.1.  Perhaps users may benefit from more of an explicit explanation that this is parameterized in the section on SimpleSearch in the readme? Happy to contribute to read.me if helpful. Thank you again!
