### ISSUE TITLE
Tokenization for uniCOIL queries

### ISSUE THREAD

**Issue by ccsasuke** [castorini/pyserini#749]
Hi,

I'm trying to run retrieval on some custom queries on uniCOIL, and I'm wondering how the queries in `topics.msmarco-passage.dev-subset.unicoil.tsv` are tokenized?

It looks like BPE tokens, which makes sense, but each token is also repeated multiple times.
Do you have a minimal working script that can tokenize a query string into the uniCOIL format?

Thank you.

**Comment by MXueguang** [comment]
```python
from pyserini.encode import UniCoilQueryEncoder
encoder = UniCoilQueryEncoder('castorini/unicoil-d2q-msmarco-passage')
encoder.encode('text to encode')
```

**Comment by ccsasuke** [comment]
Thank you for the prompt reply @MXueguang 

I followed the instruction and this is what it gives:
![image](https://user-images.githubusercontent.com/1481766/132074986-ed432b27-cc16-41b0-bd40-a3019e72f840.png)

How do I convert the float weights into integers to generate the tokenized query?

**Comment by MXueguang** [comment]
you can leave it as `float` now since Anserini taking a weights dict
https://github.com/castorini/pyserini/blob/708cf6742f8987fc2519aeb33ef898e3d1a8c13e/pyserini/search/_impact_searcher.py#L108

if you do want to get integers, we did the quantization by `round(x/5**8)`, (since the weights generated by the model are all in the range of (0, 5))

**Comment by MXueguang** [comment]
and you can do the e2e search directly by:
```
python -m pyserini.search --topics msmarco-passage-dev-subset \
                            --encoder castorini/unicoil-d2q-msmarco-passage \
                            --index indexes/lucene-index.msmarco-passage-unicoil-b8 \
                            --output runs/run.msmarco-passage-unicoil-b8.tsv \
                            --impact \
                            --hits 1000 --batch 36 --threads 12 \
                            --output-format msmarco
```

**Comment by ccsasuke** [comment]
Works like a charm! Thank you.
