### ISSUE TITLE
About issue #757

### ISSUE THREAD

**Issue by Pourbahman** [castorini/pyserini#758]
Hi,

Thanks for your reply.
In issue #757, maybe I asked my question badly. I try to ask more precisely. About your answer "You'll have to get the raw text and parse it out manually.", when I extract raw text, it does not contain title and it just contains TEXT tag that is the body of the document. I would appreciate it if you clear your answer.

Thanks in advance,
Kind Regards,
Zahra

**Comment by lintool** [comment]
Somewhere in the TEXT tag is the title of the document. You'll have to parse it out manually - e.g., matching with a regular expression.

**Comment by Pourbahman** [comment]
Thanks.
In Robust04 titles are not a part of TEXT tag. Would you please tell me what is your comment about it?

**Comment by lintool** [comment]
If you can't find the titles there, then the documents must not have titles.

**Comment by Pourbahman** [comment]
Thanks but suppose the following document:
<DOC>
<DOCNO> FBIS3-21770 </DOCNO>
<HT>    "jptdd010__l94075" </HT>


<HEADER>
<AU>   JPRS-TDD-94-010L </AU>
Document Type:JPRS 
Document Title:Narcotics 

<DATE1>  7 March 1994 </DATE1>

</HEADER>

<F P=100> EAST EUROPE </F>
<F P=101> ROMANIA </F>
**<H3> <TI>   Interior Minister Discusses `Explosion' of Mafia-Type Crime </TI></H3>**
<F P=102>  AU0403131594 Bucharest TINERETUL LIBER in Romanian 24 Feb 94 
pp 1, 3 </F>

<F P=103> AU0403131594 </F>
<F P=104>  Bucharest TINERETUL LIBER </F>


**<TEXT>
Language: <F P=105> Romanian </F>
Article Type:BFN 

<F P=106> ["Exclusive Interview with Lieutenant General George Ioan </F>
Danescu, Minister of Interior, for TINERETUL LIBER"; place and 
date not given: "Latest Mafia-Type Armed Confrontations in 
Bucharest"] 
  [Excerpts] [TINERETUL LIBER] Mr. Minister, a new 
phenomenon has appeared in Romania today: Mafia-type crime. 
What action are the police and Ministry of Interior taking to 
prevent and fight this social evil? 
...**

The title is in the <H3> <TI> tag and when we use the following code lines:

from pyserini.index import IndexReader
reader = IndexReader.from_prebuilt_index('robust04')
print(reader.doc('FBIS3-21770').raw())

it returns just the content of the text tag:

<TEXT>\nLanguage: <F P=105> Romanian </F>\nArticle Type:BFN\n\n<F P=106> ["Exclusive Interview with Lieutenant General George Ioan </F>\nDanescu, Minister of Interior, for TINERETUL LIBER"; place and\ndate not given: "Latest Mafia-Type Armed Confrontations in\nBucharest"]\n[Excerpts] [TINERETUL LIBER] Mr. Minister, a new\nphenomenon has appeared in Romania today: Mafia-type crime.\nWhat action are the police and Ministry of Interior taking to\nprevent and fight this social evil?\nDanescu: When you say that we are facing a new\nphenomenon, you are referring to its novelty for the broad\npublic and, maybe, even for you journalists. For us\nprofessionals, however, Mafia-type crime, that is to say\norganized crime, is neither new nor surprising, because signs of\nit existed in Romania even before December 1989, something which\nI also emphasized a year ago at a news conference.\nAs a matter of fact, it was to be expected that certain\nchanges that occurred in Romanian society and its openi...

Would you please tell me your comments about it?

**Comment by Pourbahman** [comment]
Thanks but suppose document with doc-id=FBIS3-21770 the title is **Interior Minister Discusses `Explosion' of Mafia-Type Crime**:
```
<DOC>
<DOCNO> FBIS3-21770 </DOCNO>
<HT>    "jptdd010__l94075" </HT>


<HEADER>
<AU>   JPRS-TDD-94-010L </AU>
Document Type:JPRS 
Document Title:Narcotics 

<DATE1>  7 March 1994 </DATE1>

</HEADER>

<F P=100> EAST EUROPE </F>
<F P=101> ROMANIA </F>
<H3> <TI>   Interior Minister Discusses `Explosion' of Mafia-Type Crime </TI></H3>
<F P=102>  AU0403131594 Bucharest TINERETUL LIBER in Romanian 24 Feb 94 
pp 1, 3 </F>

<F P=103> AU0403131594 </F>
<F P=104>  Bucharest TINERETUL LIBER </F>


<TEXT>
Language: <F P=105> Romanian </F>
Article Type:BFN 

<F P=106> ["Exclusive Interview with Lieutenant General George Ioan </F>
Danescu, Minister of Interior, for TINERETUL LIBER"; place and 
date not given: "Latest Mafia-Type Armed Confrontations in 
Bucharest"] 
  [Excerpts] [TINERETUL LIBER] Mr. Minister, a new 
phenomenon has appeared in Romania today: Mafia-type crime. 
What action are the police and Ministry of Interior taking to 
prevent and fight this social evil? 

```
**If I use the following code lines:**

```
from pyserini.index import IndexReader
reader = IndexReader.from_prebuilt_index('robust04')
print(reader.doc('FBIS3-21770').raw())
```

**it returns the content of text tag that it does not have the title that placed in tag `<H3> <TI>` **

`<TEXT>\nLanguage: <F P=105> Romanian </F>\nArticle Type:BFN\n\n<F P=106> ["Exclusive Interview with Lieutenant General George Ioan </F>\nDanescu, Minister of Interior, for TINERETUL LIBER"; place and\ndate not given: "Latest Mafia-Type Armed Confrontations in\nBucharest"]\n[Excerpts] [TINERETUL LIBER] Mr. Minister, a new\nphenomenon has appeared in Romania today: Mafia-type crime.\nWhat action are the police and Ministry of Interior taking to\nprevent and fight this social evil?\nDanescu: When you say that we are facing a new\nphenomenon, you are referring to its novelty for the broad\npublic and, maybe, even for you journalists. For us\nprofessionals, however, Mafia-type crime, that is to say\norganized crime, is neither new nor surprising, because signs of\nit existed in Romania even before December 1989, something which\nI also emphasized a year ago at a news conference.\nAs a matter of fact, it was to be expected that certain\nchanges that occurred in Romanian society and its open
`

Would you please tell me your comments about it?

**Comment by lintool** [comment]
For whatever reason, we decided only to index the document contents in `<TEXT>`, so the title ("Interior Minister Discusses `Explosion' of Mafia-Type Crime") does not appear to have made it into the index. This decision of what to index is controlled by this: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/collection/TrecCollection.java

So if you really want the title, you'll have to modify the above class and re-index. Quite simply, the titles aren't in the pre-built index.

**Comment by Pourbahman** [comment]
Thanks for your reply.
Have a nice time
