### ISSUE TITLE
how to built indexes

### ISSUE THREAD

**Issue by yashwatwani** [castorini/pyserini#76]
what should I use to make indexes. I was looking at few options -solr,elasticsearch,lucene etc

**Comment by lintool** [comment]
Perhaps you can describe what you are trying to accomplish?

**Comment by lintool** [comment]
Hearing no further follow up, closing issue.

**Comment by keratin7** [comment]
Have a similar doubt. There's no guideline anywhere as to how to build an index on a new dataset and whether that can be done using pyserini or does one have to use anserini/lucene, if it is the latter, the format/template the doc/fields need to be in etc. 
Almost everywhere I've looked, they're working on pre-built indexes. Could you point to some helpful resources?

**Comment by lintool** [comment]
yes, we're working on it in #77 !
