### ISSUE TITLE
Incorrect architecture specified for ANCE DPR context encoder model

### ISSUE THREAD

**Issue by joshdevins** [castorini/pyserini#769]
In the config for your ANCE DPR context encoder in HuggingFace model hub, the architecture is listed as `DPRQuestionEncoder` but it should be `DPRContextEncoder`. This causes a failure when using "reflection" to check the correct model class type to use.

See: https://huggingface.co/castorini/ance-dpr-context-multi/blob/main/config.json
Related: https://github.com/huggingface/transformers/issues/13670

**Comment by lintool** [comment]
@MXueguang this is your code, right? Can you please take a look?

**Comment by MXueguang** [comment]
Yes, @lintool 
@joshdevins, thank you for catching the issue, I'll update the model on hugging face.

**Comment by MXueguang** [comment]
It shouldn't affect results, but I'll rerun to make sure it works.

**Comment by joshdevins** [comment]
Thanks @MXueguang , can you close this issue when the `config.json` is updated? Then I can try it again 🙏

**Comment by MXueguang** [comment]
@joshdevins, I just updated the `config.json`

**Comment by joshdevins** [comment]
Perfect, works for me now, thanks! Note that `AutoModel` still doesn't work but that's related to this HuggingFace bug: https://github.com/huggingface/transformers/issues/13670
