### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'raw'

### ISSUE THREAD

**Issue by yashwatwani** [castorini/pyserini#78]
from pyserini.search import pysearch

searcher = pysearch.SimpleSearcher('/home/ds/anserini/covid-2020-04-17/lucene-index-covid-paragraph-new/')
hits = searcher.search('nsp1 synthesis degradation', 10)

article = json.loads(searcher.doc('42saxb98').raw)

# Uncomment to print the entire article... warning, it's long! :)
#print(json.dumps(article, indent=4))

article['metadata']['title']

error-

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-49-1b08267fb4a5> in <module>()
----> 1 article = json.loads(searcher.doc('42saxb98').raw)
      2 
      3 # Uncomment to print the entire article... warning, it's long! :)
      4 #print(json.dumps(article, indent=4))
      5 

AttributeError: 'Document' object has no attribute 'raw'

**Comment by lintool** [comment]
Are you using the latest version of Pyserini? 0.9.0.0

This seems to work fine: https://github.com/castorini/anserini-notebooks/blob/master/pyserini_covid19_paragraph.ipynb

**Comment by lintool** [comment]
Hearing no further follow up, closing issue.
