### ISSUE TITLE
Integrate ADORE into Pyserini

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#783]
https://github.com/jingtaozhan/DRhard

**Comment by ArvinZhuang** [comment]
PR opened #785 
But there is a problem: due to transformers version mismatch, the on-the-fly scores cannot match preprocessed queries (quite a bit, 1 point lower on ms marco passage). The original model checkpoint requires a tokenizer from `transformers==2.8.0`, but pyserini uses a higher version.
