### ISSUE TITLE
Expose internal Lucene docid number n to the Pysearch

### ISSUE THREAD

**Issue by stephaniewhoo** [castorini/pyserini#79]
Make the internal Lucene docid number n expose to the searcher to make python interface easily iterate in the index file.

**Comment by lintool** [comment]
hi @stephaniewhoo can you work on this issue then?

The Java Method you need is `maxDoc()` from `IndexReader`, and you can get an `IndexReader` from a `IndexSearcher`. I believe this features can be added directly from the Python end, without any additional Java code.

**Comment by lintool** [comment]
Closed by #98
