### ISSUE TITLE
JavaException: JVM exception occurred: Could not load codec 'Lucene84'

### ISSUE THREAD

**Issue by sipah00** [castorini/pyserini#80]
I, first, indexed my docs using `lucene-8.5.1` in java, then after running 
```
searcher = pysearch.SimpleSearcher('/home/sipah00/java_lucene/lucene_idx1/')
```
I got this error, `JavaException: JVM exception occurred: Could not load codec 'Lucene84'.  Did you forget to add lucene-backward-codecs.jar?`
How to resolve this issue? is there any specific version of `lucene` that `pyserini` supports?
Also, how can I index my docs in `pyserini` only?

**Comment by sipah00** [comment]
I looked into `anserini` pom.xml, lucene version is 8.3.0 there, and tried to index my docs using 8.3.0 and this time I didn't get above error but on using `searcher.search('query')`, I got `JavaException: JVM exception occurred: java.lang.NullPointerException` error. I'm new to Java and not able to figure out the problem.

**Comment by lintool** [comment]
How are you building the indexes? Pyserini requires indexes that have been built by Anserini, not just any generic Lucene index...

**Comment by sipah00** [comment]
I was using java lucene package, finally I built `anserini` then used `indexCollection` and every thing worked fine. It would be great if indexing things comes to `pyserini` so anyone can do indexing directly from python.
Thank you very much for making `pyserini`.

**Comment by lintool** [comment]
Glad it worked out for you! #77 we're on it!
