### ISSUE TITLE
Not able to import - from pyserini.search import pysearch

### ISSUE THREAD

**Issue by shauryr** [castorini/pyserini#82]
I was trying to the run the demo code.

importing gives me this error - 
File "jnius/jnius_export_func.pxi", line 28, in jnius.find_javaclass
jnius.JavaException: Class not found b'io/anserini/analysis/DefaultEnglishAnalyzer'

**Comment by lintool** [comment]
What instructions are you following? Have you tried `pip install pyserini==0.9.0.0`?
Might want to try the notebooks first... https://github.com/castorini/anserini-notebooks

**Comment by lintool** [comment]
Seeing no further comments, closing issue.
