### ISSUE TITLE
Pre-tokenized queries for TRECDL

### ISSUE THREAD

**Issue by JMMackenzie** [castorini/pyserini#834]
For most of the examples provided (both here and Anserini), pre-tokenized queries are available for systems like uniCOIL.

I'm wondering if pre-tokenized queries could also be made available for the corresponding TRECDL queries? If not, could you provide guidance on going from the `.tsv` files to the re-weighted/tokenized queries?

**Comment by lintool** [comment]
These have been added, see `pyserini/pyserini/search/_base.py`.
