### ISSUE TITLE
pyserini.search option --min-idf should be --min-df

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#850]
The command:

```
python -m pyserini.search --topics msmarco-v2-passage-dev \
                          --encoder castorini/unicoil-noexp-msmarco-passage \
                          --index msmarco-v2-passage-unicoil-noexp-0shot \
                          --output runs/run.msmarco-v2-passage.unicoil-noexp.0shot.txt \
                          --impact \
                          --hits 1000 \
                          --batch 144 \
                          --threads 36 \
                          --min-idf 1
```

The option `--min-idf` should be `--min-df` instead. The "i" stands for inverse, which is not applicable here.

**Comment by MXueguang** [comment]
we want to filter out the terms have high document frequency. Terms with high document frequency has low inverse document frequency. i.e. stop words have low idf. e.g. "is" have idf close to 0.

**Comment by lintool** [comment]
I see. I had a different interpretation of filtering as "keeping" or "discarding". All good.
