### ISSUE TITLE
dynamically import dependencies 

### ISSUE THREAD

**Issue by MXueguang** [castorini/pyserini#853]
e.g. tevatron uses pyserini for evaluation, EntityQuestion uses pyserini for bm25 search.
in those case, its not make sense to let user install faiss/torch/onnxruntime etc.
we can utilize transformers utils `is_backend_avaliable` and `requires_backend` to dynamically import dependencies

**Comment by lintool** [comment]
Superseded by refactoring in #2006 #2009 and related issues. Closing.
