### ISSUE TITLE
unittest broken

### ISSUE THREAD

**Issue by nimasadri11** [castorini/pyserini#858]
`python -m unittest` fails.

```
  File "/scratch/nsadri/p2/pyserini/tests/test_search.py", line 25, in <module>
    from pyserini.search import Document, SimpleSearcher, JSimpleSearcherResult
ImportError: cannot import name 'Document' from 'pyserini.search' (/scratch/nsadri/p2/pyserini/pyserini/search/__init__.py)
```

**Comment by nimasadri11** [comment]
-- sending PR for the fix

**Comment by MXueguang** [comment]
the issue seems not an unittest issue. running unittest on latest code should solve this problem.
it's actually an environment setup issue, @nimasadri11  updated the installation guide for development installation.
ready for close.
