### ISSUE TITLE
Analysis of length distributions of title, abstract, and full-text in CORD-19

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#88]
@stephaniewhoo Can you share your notebook here and we can discuss?

**Comment by stephaniewhoo** [comment]
https://colab.research.google.com/drive/1-CdFvDAY0YKT2W9NE2fHeClFuNUNRDWq?usp=sharing
Here's the notebook WIP.

**Comment by lintool** [comment]
@stephaniewhoo I had suggested on Slack DM that we should switch over to analyzing the raw collection directly, as opposed to the index, since the index already has a blacklist to discard outlier documents (and we want to retain those for this particular analysis): https://github.com/castorini/pyserini/blob/master/docs/working-with-cord19.md
