### ISSUE TITLE
zsh: killed python3 -m pyserini.dsearch --topics dpr-nq-test --index  --encoded-queries  

### ISSUE THREAD

**Issue by JosieChen1214** [castorini/pyserini#881]
Sorry for bothering you.

When I run python -m pyserini.dsearch --topics ... from the terminal on the MacBookPro with M1, the program always displays zsh: killed python -m Pyserini.dsearch --topics ... 

What should I do for solving this problem?

**Comment by lintool** [comment]
Can you please send us the error trace?

**Comment by JosieChen1214** [comment]
> Can you please send us the error trace?

josiechen@JosiechendeMacBook-Pro ~ % python -m pyserini.dsearch --topics dpr-nq-test \
--index wikipedia-dpr-multi-bf \
--encoded-queries dpr_multi-nq-test \
--output /Users/josiechen/run.dpr.nq-test.multi.bf.trec \
--batch-size 36 --threads 12
Attempting to initialize pre-encoded queries dpr_multi-nq-test.
/Users/josiechen/.cache/pyserini/queries/query-embedding-dpr_multi-nq-test-20210419-9323ec.1791f1ed078beb3a00847f75023eb020 already exists, skipping download.
Initializing dpr_multi-nq-test...
Attempting to initialize pre-built index wikipedia-dpr-multi-bf.
/Users/josiechen/.cache/pyserini/indexes/dindex-wikipedia-dpr_multi-bf-20200127-f403c3.29eb39fe0b00a03c36c0eeae4c24f775 already exists, skipping download.
Initializing wikipedia-dpr-multi-bf...
zsh: killed     python -m pyserini.dsearch --topics dpr-nq-test --index wikipedia-dpr-multi-b


Here's my input and feedback from the terminal. Thanks for your time!!!

**Comment by lintool** [comment]
What machine are you trying to run this on? I suspect it's a memory issue... @MXueguang any ideas?

**Comment by JosieChen1214** [comment]
> What machine are you trying to run this on? I suspect it's a memory issue... @MXueguang any ideas?

I've tried to run this on Linux and MacOS. The above was the result of running on MacOS. And linux also failed because of the problem of server cache. I'm trying to upload the index from the local to the Linux server now.

**Comment by MXueguang** [comment]
Hi @JosieChen1214 
dpr index requires around 64gb RAM.
Could you double check if you have enough RAM?

**Comment by JosieChen1214** [comment]
Thank you for helping me find the cause and for your patience. I'm very sorry for bothering you. Thank you again!!!
