### ISSUE TITLE
No module named pyserini.index.merge_faiss_indexes

### ISSUE THREAD

**Issue by lhuang9703** [castorini/pyserini#884]
When I try to create the full dpr index by merging the sub-indexes by: python -m pyserini.index.merge_faiss_indexes --prefix indexes/dindex-sample-dpr-multi- --shard-num 4
It seems merge_faiss_indexes can not work! I don't find its implementation codes in pyserini/index.

**Comment by MXueguang** [comment]
Hi @lhuang9703, please look at this for now.  
https://github.com/castorini/pyserini/blob/pyserini-0.13.0/pyserini/dindex/merge_indexes.py

pyserini.dindex was removed during refectoring, I'll add the merge_faiss_indexes to pyserini.index soon.

**Comment by lhuang9703** [comment]
Thanks!
