### ISSUE TITLE
Faiss for SimpleSearcher

### ISSUE THREAD

**Issue by neginghasemi** [castorini/pyserini#885]
When I try to import the SimpleSearcher from pyserini.search, I get an error which asks me to install faiss. When I install faiss, I got the error "No module named '_swigfaiss'". This problem appeared when I started using version '0.14.0'.

**Comment by lintool** [comment]
How are you installing Faiss? Have you tried the instructions here? https://github.com/castorini/pyserini/blob/master/docs/installation.md

**Comment by lintool** [comment]
Having heard no follow up, I'm closing issue. Please re-open if there are any questions.

**Comment by chriskamphuis** [comment]
You should not need `faiss` for SimpleSearcher right?

**Comment by lintool** [comment]
The imports might have transitively pulled in things that need faiss..
