### ISSUE TITLE
Question about ImpactSearcher

### ISSUE THREAD

**Issue by namespace-Pt** [castorini/pyserini#889]
In DeepImpact reproduction tutorial, you've mentioned setting `-impact` to enable impact scores instead of BM25. After checking python source code, I have questions about how the `ImpactSearcher` works.

In the original DeepImpact paper, the author summed up the quantized impacts of all matching tokens in the document to generate a document relevance score, which is described as:
>  to compute a query-document score at query processing we can just sum up all the quantized scores of the document terms matching the query.

Therefore, it is assumed that `ImpactSearcher` can automatically 

1. quantize all produced impacts; 
2. locate overlapping tokens between each query-document pair;
3. sum quantized impacts of these tokens to produce a document relevance score;

Am I right? Or is there any extra documentation of how `ImpactSearcher` works?

**Comment by lintool** [comment]
The quantization is handled at the indexing end, specified in the corpus in our jsonl format. So `ImpactSearcher` does not handle (1) above.

Yes, `ImpactSearcher` handles (2) and (3) above. You'll have to look at the Java code to see how the impl actually works: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SimpleImpactSearcher.java

**Comment by namespace-Pt** [comment]
Thanks for your soon reply! Another question, can I directly use token ids of the documents to build index and also search with token ids with `-pretokenized` option?

**Comment by lintool** [comment]
Yes, if the corpus contains token ids and the search queries are also in terms of token ids, it should work. If you are pursuing this route, we would appreciate a test case demonstrating this usage.

**Comment by namespace-Pt** [comment]
Okay thank you again. Actually I'm working on it. Maybe I will turn to you when I meet some problems. I will close this issue.
