### ISSUE TITLE
Entity linking script seems to be outdated

### ISSUE THREAD

**Issue by hsiaoyi0504** [castorini/pyserini#896]
For example, 
https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/tutorials/02_E2E_Entity_Linking.md
The input text format seems to be a dictionary using a list (`[text, []]`) rather than `text` only now.

**Comment by lintool** [comment]
Hi @hsiaoyi0504 thanks for pointing out. Indeed, that's likely the case.

We'd appreciate a PR to update the script!
