### ISSUE TITLE
Clean up sys.path.append

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#917]
We have a bunch of these idioms scattered throughout the code base:

```python
import sys
sys.path.append('.')
```

Since our installation instructions suggest we do:

```bash
$ pip install -e .
```

These can be cleaned up?

**Comment by HAKSOAT** [comment]
Hi @lintool can I work on this? I think it's a good first task.

**Comment by lintool** [comment]
Sure! Any contributions welcome!

**Comment by lintool** [comment]
hi @HAKSOAT - if you're interested in helping out, there are other small tasks that we could use help on...

**Comment by HAKSOAT** [comment]
Hi @lintool Yes, I am very interested. I'd appreciate it if you fill me in.

**Comment by lintool** [comment]
Please ping me on email?

**Comment by HAKSOAT** [comment]
Your uwaterloo email right?

**Comment by lintool** [comment]
Yes please.

**Comment by HAKSOAT** [comment]
Done.
