### ISSUE TITLE
Make methods in IndexReaderUtils more consistent re: Analyzer

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#93]
We have:

```python
# Pass in a no-op analyzer:
analyzer = pyanalysis.get_lucene_analyzer(stemming=False, stopwords=False)
index_utils.get_term_counts(term, analyzer=analyzer)
df, cf = index_utils.get_term_counts(term)
```
Here, we take an `analyzer`.

And:

```python
# Fetch and traverse postings for an analyzed term:
postings_list = index_utils.get_postings_list(analyzed[0], analyze=False)
for posting in postings_list:
    print(f'docid={posting.docid}, tf={posting.tf}, pos={posting.positions}')
```

Here, we take a `bool`. Let's make both consistent?

How about both take `analyzer` and accepts `None`? Passing in a "no-op" analyzer seems a bit janky.

Thoughts? @PepijnBoers @Chriskamphuis

**Comment by PepijnBoers** [comment]
Both taking an `analyzer` makes sense to me, especially since the `getPostingsListWithAnalyzer` method is already available in Anserini.

**Comment by lintool** [comment]
@PepijnBoers do you have cycles to take this on?

**Comment by PepijnBoers** [comment]
@lintool sure!

**Comment by PepijnBoers** [comment]
Currently `get_term_counts` applies Anserini's default Lucene analyzer if no analyzer is specified (`analyzer=None`), then in order to skip term analysis you have to pass a dummy analyzer. Is this the requested behavior or do we want `analyzer=None` to mean that no analysis should take place?

**Comment by lintool** [comment]
I'm thinking:
+ No analyzer specified - use default.
+ `analyzer=foo` - use `foo` as analyzer
+ `analyzer=None` - skip analysis

And we make this behavior across all methods (existing, and in the future).

Thoughts?

**Comment by PepijnBoers** [comment]
I assumed that `None` would be the value for an unspecified analyzer, do you suggest we overload the methods in Pyserini and remove a default value for the `analyzer` parameter?

**Comment by PepijnBoers** [comment]
We could do it like this:

```python
get_term_counts(self, term: str, analyzer='unspecified') -> Tuple[int, int]: 
    if analyzer is 'unspecified'":
        # use default
    elif analyzer is None:
        # skip analysis (pass dummy to Anserini)
    else:
       # perform analysis with given analyzer
    ...
```

**Comment by lintool** [comment]
What about something simpler, like this?

```python
get_term_counts(self, term: str, analyzer=default) -> Tuple[int, int]: 
    if analyzer is None:
        # skip analysis (pass dummy to Anserini)
    else:
       # perform analysis with analyzer (either default or custom)
    ...
```

**Comment by PepijnBoers** [comment]
Looks good, but then we have to specify `default` somewhere, otherwise we face a `NameError`. The question would then also be how/where to define default, right?

**Comment by Chriskamphuis** [comment]
you can just do:
```python
get_term_counts(self, term: str, analyzer=get_lucene_analyzer()) -> Tuple[int, int]: 
    if analyzer is None:
        # skip analysis (pass dummy to Anserini)
    else:
       # perform analysis with analyzer (either default or custom)
    ...
```
