### ISSUE TITLE
Test failure: TestLtrMsmarcoDocument and TestLtrMsmarcoPassage

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#951]
```
======================================================================
FAIL: test_reranking (test_ltr_msmarco_document.TestLtrMsmarcoDocument)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_document.py", line 59, in test_reranking
    self.assertAlmostEqual(float(mrr),0.3090492928920076, delta=0.000001)
AssertionError: 0.30906234846241004 != 0.3090492928920076 within 1e-06 delta (1.3055570402431549e-05 difference)

======================================================================
FAIL: test_reranking (test_ltr_msmarco_passage.TestLtrMsmarcoPassage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_passage.py", line 53, in test_reranking
    self.assertAlmostEqual(float(mrr),0.24709612498294367, delta=0.000001)
AssertionError: 0.24723580979669724 != 0.24709612498294367 within 1e-06 delta (0.00013968481375356556 difference)

```

Seems like the underlying dependencies have changed a bit... this seems like an issue of brittle tests; we probably don't need to hit the score within a delta of 1e-06.

@yuki617 @stephaniewhoo Okay if we dial down the delta a bit? I'll take care of sending PR.

**Comment by stephaniewhoo** [comment]
> ```
> ======================================================================
> FAIL: test_reranking (test_ltr_msmarco_document.TestLtrMsmarcoDocument)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_document.py", line 59, in test_reranking
>     self.assertAlmostEqual(float(mrr),0.3090492928920076, delta=0.000001)
> AssertionError: 0.30906234846241004 != 0.3090492928920076 within 1e-06 delta (1.3055570402431549e-05 difference)
> 
> ======================================================================
> FAIL: test_reranking (test_ltr_msmarco_passage.TestLtrMsmarcoPassage)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_passage.py", line 53, in test_reranking
>     self.assertAlmostEqual(float(mrr),0.24709612498294367, delta=0.000001)
> AssertionError: 0.24723580979669724 != 0.24709612498294367 within 1e-06 delta (0.00013968481375356556 difference)
> ```
> 
> 
>      
>   
> 
> Seems like the underlying dependencies have changed a bit... this seems like an issue of brittle tests; we probably don't need to hit the score within a delta of 1e-06.
> 
> 
> @yuki617 @stephaniewhoo Okay if we dial down the delta a bit? I'll take care of sending PR.

Yes, lgtm! Thx

**Comment by yuki617** [comment]
> ```
> ======================================================================
> FAIL: test_reranking (test_ltr_msmarco_document.TestLtrMsmarcoDocument)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_document.py", line 59, in test_reranking
>     self.assertAlmostEqual(float(mrr),0.3090492928920076, delta=0.000001)
> AssertionError: 0.30906234846241004 != 0.3090492928920076 within 1e-06 delta (1.3055570402431549e-05 difference)
> 
> ======================================================================
> FAIL: test_reranking (test_ltr_msmarco_passage.TestLtrMsmarcoPassage)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/scratch2/jimmylin/pyserini/integrations/sparse/test_ltr_msmarco_passage.py", line 53, in test_reranking
>     self.assertAlmostEqual(float(mrr),0.24709612498294367, delta=0.000001)
> AssertionError: 0.24723580979669724 != 0.24709612498294367 within 1e-06 delta (0.00013968481375356556 difference)
> ```
> 
> Seems like the underlying dependencies have changed a bit... this seems like an issue of brittle tests; we probably don't need to hit the score within a delta of 1e-06.
> 
> @yuki617 @stephaniewhoo Okay if we dial down the delta a bit? I'll take care of sending PR.

Yes, the difference is fairly small. Let's dial down the delta. Thanks!
