### ISSUE TITLE
Add (new) pre-built indexes for MS MARCO (V1)

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#972]
Following the resolution of https://github.com/castorini/anserini/issues/1721 and https://github.com/castorini/anserini/issues/1730 - we need to rebuild new pre-built indexes.

**Comment by lintool** [comment]
@ronakice @MXueguang how would you like me to name them?

Currently, they are:
+ `msmarco-passage`
+ `msmarco-passage-expanded`
+ `msmarco-doc`
+ `msmarco-doc-per-passage`
+ `msmarco-doc-expanded-per-doc`
+ `msmarco-doc-expanded-per-passage`

Should we keep the existing ids and just replace the underlying tarballs? That would be a silent change.

Alternatively, we could use brand new ids, like `msmarco-v1...` and make the names parallel to V2.

Thoughts?

**Comment by ronakice** [comment]
I think perhaps the `msmarco-v1...` path is better, as it also helps disambiguate for the future. As to whether these other ones are required, I don't actually have a strong opinion but I'm leaning toward removing them as they might confuse people.
